// Generated by media/brand-film/mix-product-tour-audio.mjs.
export const PRODUCT_TOUR_ASSET = {
  src: "/brand/toonstudio-product-tour.mp4?v=2c55256eca42c4af",
  bytes: 23469745,
  sha256: "2c55256eca42c4af1b4414c908d145d788f39adace6b0d07c908748ee2b67745",
  revision: "2c55256eca42c4af",
  narrationLocale: "ko-KR",
  hasOriginalBgm: true,
} as const;
