/**
 * Generated by the all-brush screen-fill quality benchmark.
 *
 * Empty by default: automatic rollout remains on the incumbent until a real baseline/GPU run
 * proves live/commit continuity, committed texture non-inferiority, and bounded performance for a
 * particular catalogue id. Explicit development/verification backend selection is independent.
 */
export const STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_SCHEMA_VERSION = 1 as const;
export const STUDIO_BRUSH_GPU_QUALITY_EVIDENCE = Object.freeze({
  schemaVersion: STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_SCHEMA_VERSION,
  generatedAt: null as string | null,
  sourceCommit: null as string | null,
  benchmarkDigest: null as string | null,
  measuredBrushCount: 0,
  approvedBrushIds: Object.freeze([] as string[]),
  rejectedBrushIds: Object.freeze([] as string[]),
});
