/** Shell metadata only. Do not import page/navigation modules into this table. */
export const CREATOR_RESOURCE_TITLES: Record<string, string> = {
  "/make": "만들기",
  "/discover": "찾기",
  "/my": "내 공간",
  "/help": "도움말 센터",
  "/brand-film": "툰스튜디오 브랜드 필름",
  "/product-tour": "툰스튜디오 전체 제품 투어",
  "/accessibility": "접근성",
  "/now": "오늘의 영감",
  "/research": "창작 리서치 데스크",
  "/research/assets": "창작 레퍼런스 아틀라스",
  "/research/catalog": "작품 리서치 랩",
  "/research/catalog/notebook": "작품 비교·기획 노트",
  "/research/books": "글로벌 만화·도서 판본 탐색",
  "/research/3d-assets": "무료 3D·HDRI·텍스처 재료실",
  "/creator-hub": "창작 허브",
  "/opportunities": "작가 기회센터",
  "/creator-hub/references": "창작 레퍼런스 아틀라스",
  "/learn/process": "웹툰 제작 과정",
  "/learn/careers": "웹툰 진로·직무 안내",
  "/learn/education": "웹툰 교육기관 찾기",
  "/learn/resources": "웹툰 교육 자료 허브",
  "/learn/classroom": "웹툰 교육기관 활용",
  "/learn/recipes": "웹툰 제작 레시피",
  "/story-lab": "스토리 연구실",
  "/discover/works": "만화·작법서 탐색",
  "/publishing": "연재·출판 준비실",
  "/studio/3d/dcc/build": "3D 공간 제작",
  "/studio/3d/dcc/cad": "정밀 CAD",
  "/studio/3d/dcc/material": "재질·UV",
  "/studio/3d/dcc/model": "3D 모델링",
  "/studio/3d/dcc/sculpt": "3D 조형",
  "/studio/3d/dcc/shot": "컷·선화",
  "/studio/ai-lab": "AI 실험실",
  "/insights/resources": "공식 자료·API 안내",
  "/about/data": "데이터 출처·상업 이용 준비",
  "/about/crawler": "공개 데이터 수집 정책",
};
