export interface AppRouteMeta {
  path: string;
  label: string;
}

export const appRoutes: AppRouteMeta[] = [
  { path: "/", label: "nav.home" },
  { path: "/ranking", label: "route.ranking" },
  { path: "/search", label: "route.search" },
  { path: "/references", label: "route.references" },
  { path: "/recommend", label: "route.recommend" },
  { path: "/play", label: "route.play" },
  { path: "/explore", label: "route.explore" },
  { path: "/calendar", label: "route.calendar" },
  { path: "/reviews", label: "route.reviews" },
  { path: "/community", label: "route.community" },
  { path: "/market", label: "route.market" },
  { path: "/shaper", label: "route.shaper" },
  { path: "/library", label: "route.library" },
  { path: "/notifications", label: "route.notifications" },
  { path: "/cuts", label: "route.cuts" },
  { path: "/pricing", label: "route.pricing" },
  { path: "/studio/analytics", label: "route.creatorAnalytics" },
  { path: "/onboarding/taste", label: "route.recommend" },
  { path: "/compare", label: "route.compare" },
  { path: "/insights", label: "route.insights" },
  { path: "/sitemap", label: "route.sitemap" },
  { path: "/admin", label: "route.admin" },
  { path: "/authors", label: "route.authors" },
  { path: "/news", label: "route.news" },
  { path: "/about", label: "route.about" },
  { path: "/guide", label: "route.guide" },
  { path: "/tags", label: "route.tags" },
  { path: "/random", label: "route.random" },
  { path: "/feedback", label: "route.feedback" },
  { path: "/settings", label: "route.settings" },
  { path: "/community/cafes", label: "route.community_cafes" },
  { path: "/market/browse", label: "route.marketBrowse" },
  { path: "/market/publish", label: "route.marketPublish" },
  { path: "/market/library", label: "route.marketLibrary" },
  { path: "/design", label: "route.design" },
  { path: "/support", label: "route.support" },
  { path: "/business", label: "route.business" },
  { path: "/contact", label: "route.contact" },
  { path: "/terms", label: "route.terms" },
  { path: "/privacy", label: "route.privacy" },
  { path: "/copyright", label: "route.copyright" },
];
