// Generated by scripts/generate-federated-data-plane-policy.mjs.
// Edit config/free-database-federation.json, then regenerate this file.
import type { FederatedDataPlanePolicyDefinition } from "./federated-data-plane.contract";

export const FEDERATED_DATA_PLANE_POLICY = {
  "version": "toonspectrum.free-database-federation.v1",
  "quotaSnapshotMaxAgeSeconds": 900,
  "providers": {
    "cloudflare-d1": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "turso-libsql": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 3
    },
    "tidb-cloud-starter": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "cockroachdb-basic": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "azure-cosmos-free": {
      "billingBoundary": "free-allowance-with-app-cap",
      "applicationHardCapRatio": 0.75,
      "trafficWeight": 1
    },
    "aws-dynamodb-free": {
      "billingBoundary": "free-allowance-with-app-cap",
      "applicationHardCapRatio": 0.7,
      "trafficWeight": 1
    },
    "firestore-free": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "firebase-rtdb-free": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "mongodb-atlas-m0": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "convex-free": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "appwrite-free": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "neon-free": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "supabase-free": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    },
    "upstash-redis-free": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.75,
      "trafficWeight": 1
    },
    "bigquery-sandbox": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.75,
      "trafficWeight": 1
    },
    "motherduck-lite": {
      "billingBoundary": "hard-stop-free",
      "applicationHardCapRatio": 0.8,
      "trafficWeight": 1
    }
  },
  "shards": {
    "crdb-ledger": {
      "provider": "cockroachdb-basic",
      "domains": [
        "payment-ledger",
        "entitlement-ledger",
        "idempotency-receipts"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "tidb-identity": {
      "provider": "tidb-cloud-starter",
      "domains": [
        "identity",
        "accounts",
        "sessions",
        "authorization"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "tidb-projects": {
      "provider": "tidb-cloud-starter",
      "domains": [
        "creator-projects",
        "work-metadata",
        "revision-metadata"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "tidb-commerce": {
      "provider": "tidb-cloud-starter",
      "domains": [
        "marketplace",
        "catalog-authority",
        "order-state"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "tidb-community": {
      "provider": "tidb-cloud-starter",
      "domains": [
        "community",
        "social-graph",
        "comments",
        "reactions"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "tidb-collaboration": {
      "provider": "tidb-cloud-starter",
      "domains": [
        "collaboration",
        "messaging",
        "team-workspace"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "cosmos-project-documents": {
      "provider": "azure-cosmos-free",
      "domains": [
        "project-manifests",
        "document-snapshots",
        "large-json-state"
      ],
      "virtualShardCount": 8,
      "writeMode": "partition-key-authority"
    },
    "dynamodb-audit-events": {
      "provider": "aws-dynamodb-free",
      "domains": [
        "append-only-audit",
        "delivery-receipts",
        "usage-events"
      ],
      "virtualShardCount": 4,
      "writeMode": "partition-key-authority"
    },
    "turso-public-catalog": {
      "provider": "turso-libsql",
      "domains": [
        "public-catalog",
        "public-creator-profile",
        "public-search-read-model"
      ],
      "virtualShardCount": 32,
      "writeMode": "hash-sharded-authority"
    },
    "d1-edge-index": {
      "provider": "cloudflare-d1",
      "domains": [
        "edge-catalog-index",
        "ranking-snapshot",
        "route-manifest"
      ],
      "virtualShardCount": 8,
      "writeMode": "derived-replica"
    },
    "firestore-notifications": {
      "provider": "firestore-free",
      "domains": [
        "notification-inbox",
        "activity-inbox",
        "user-device-state"
      ],
      "virtualShardCount": 16,
      "writeMode": "partition-key-authority"
    },
    "firebase-presence": {
      "provider": "firebase-rtdb-free",
      "domains": [
        "presence",
        "typing",
        "ephemeral-room-state"
      ],
      "virtualShardCount": 1,
      "writeMode": "ephemeral-authority"
    },
    "atlas-ai-jobs": {
      "provider": "mongodb-atlas-m0",
      "domains": [
        "ai-job-documents",
        "moderation-evidence",
        "provider-payloads"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "convex-live-review": {
      "provider": "convex-free",
      "domains": [
        "live-review",
        "review-presence",
        "small-reactive-workflows"
      ],
      "virtualShardCount": 4,
      "writeMode": "partition-key-authority"
    },
    "appwrite-feedback": {
      "provider": "appwrite-free",
      "domains": [
        "feedback",
        "support-intake",
        "business-inquiries"
      ],
      "virtualShardCount": 2,
      "writeMode": "partition-key-authority"
    },
    "neon-legacy-compat": {
      "provider": "neon-free",
      "domains": [
        "legacy-postgres-compatibility",
        "migration-bridge"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "supabase-social-compat": {
      "provider": "supabase-free",
      "domains": [
        "social-compatibility",
        "playground",
        "storage-control-metadata"
      ],
      "virtualShardCount": 1,
      "writeMode": "single-authority"
    },
    "upstash-hot-cache": {
      "provider": "upstash-redis-free",
      "domains": [
        "rate-limit",
        "short-idempotency",
        "hot-cache"
      ],
      "virtualShardCount": 64,
      "writeMode": "ephemeral-authority"
    },
    "bigquery-analytics": {
      "provider": "bigquery-sandbox",
      "domains": [
        "analytics-batch",
        "quota-telemetry",
        "offline-funnels"
      ],
      "virtualShardCount": 32,
      "writeMode": "append-only-authority"
    },
    "motherduck-analysis": {
      "provider": "motherduck-lite",
      "domains": [
        "ad-hoc-analysis",
        "exported-parquet",
        "offline-reporting"
      ],
      "virtualShardCount": 1,
      "writeMode": "derived-replica"
    },
    "d1-analytics-buffer": {
      "provider": "cloudflare-d1",
      "domains": [
        "analytics-ingest-buffer"
      ],
      "virtualShardCount": 2,
      "writeMode": "append-only-authority"
    }
  },
  "routes": {
    "critical-ledger-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "crdb-ledger",
      "candidates": [
        "crdb-ledger"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "critical-ledger-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "crdb-ledger",
      "candidates": [
        "crdb-ledger"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "identity-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "tidb-identity",
      "candidates": [
        "tidb-identity"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "identity-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "tidb-identity",
      "candidates": [
        "tidb-identity"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "project-metadata-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "tidb-projects",
      "candidates": [
        "tidb-projects"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "project-metadata-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "tidb-projects",
      "candidates": [
        "tidb-projects"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "commerce-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "tidb-commerce",
      "candidates": [
        "tidb-commerce"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "commerce-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "tidb-commerce",
      "candidates": [
        "tidb-commerce"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "community-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "tidb-community",
      "candidates": [
        "tidb-community"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "community-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "tidb-community",
      "candidates": [
        "tidb-community"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "collaboration-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "tidb-collaboration",
      "candidates": [
        "tidb-collaboration"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "collaboration-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "tidb-collaboration",
      "candidates": [
        "tidb-collaboration"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "project-document-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "cosmos-project-documents",
      "candidates": [
        "cosmos-project-documents"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "project-document-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "cosmos-project-documents",
      "candidates": [
        "cosmos-project-documents"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "public-catalog-read": {
      "operation": "read",
      "consistency": "derived",
      "authority": "turso-public-catalog",
      "candidates": [
        "d1-edge-index",
        "turso-public-catalog"
      ],
      "allowReadFallback": true,
      "trafficDistribution": "weighted-rendezvous"
    },
    "public-catalog-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "turso-public-catalog",
      "candidates": [
        "turso-public-catalog"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "audit-event-write": {
      "operation": "write",
      "consistency": "replicated",
      "authority": "dynamodb-audit-events",
      "candidates": [
        "dynamodb-audit-events"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "notification-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "firestore-notifications",
      "candidates": [
        "firestore-notifications"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "notification-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "firestore-notifications",
      "candidates": [
        "firestore-notifications"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "presence-read": {
      "operation": "read",
      "consistency": "ephemeral",
      "authority": "firebase-presence",
      "candidates": [
        "firebase-presence"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "presence-write": {
      "operation": "write",
      "consistency": "ephemeral",
      "authority": "firebase-presence",
      "candidates": [
        "firebase-presence"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "ai-job-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "atlas-ai-jobs",
      "candidates": [
        "atlas-ai-jobs"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "ai-job-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "atlas-ai-jobs",
      "candidates": [
        "atlas-ai-jobs"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "live-review-read": {
      "operation": "read",
      "consistency": "ephemeral",
      "authority": "convex-live-review",
      "candidates": [
        "convex-live-review"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "live-review-write": {
      "operation": "write",
      "consistency": "ephemeral",
      "authority": "convex-live-review",
      "candidates": [
        "convex-live-review"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "feedback-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "appwrite-feedback",
      "candidates": [
        "appwrite-feedback"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "feedback-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "appwrite-feedback",
      "candidates": [
        "appwrite-feedback"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "legacy-compat-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "neon-legacy-compat",
      "candidates": [
        "neon-legacy-compat"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "legacy-compat-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "neon-legacy-compat",
      "candidates": [
        "neon-legacy-compat"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "social-compat-read": {
      "operation": "read",
      "consistency": "authoritative",
      "authority": "supabase-social-compat",
      "candidates": [
        "supabase-social-compat"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "social-compat-write": {
      "operation": "write",
      "consistency": "authoritative",
      "authority": "supabase-social-compat",
      "candidates": [
        "supabase-social-compat"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "hot-cache-read": {
      "operation": "read",
      "consistency": "ephemeral",
      "authority": "upstash-hot-cache",
      "candidates": [
        "upstash-hot-cache"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "hot-cache-write": {
      "operation": "write",
      "consistency": "ephemeral",
      "authority": "upstash-hot-cache",
      "candidates": [
        "upstash-hot-cache"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "analytics-event-write": {
      "operation": "write",
      "consistency": "derived",
      "authority": "d1-analytics-buffer",
      "candidates": [
        "d1-analytics-buffer"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    },
    "analytics-read": {
      "operation": "read",
      "consistency": "derived",
      "authority": "bigquery-analytics",
      "candidates": [
        "motherduck-analysis",
        "bigquery-analytics"
      ],
      "allowReadFallback": true,
      "trafficDistribution": "weighted-rendezvous"
    },
    "analytics-batch-load": {
      "operation": "write",
      "consistency": "derived",
      "authority": "bigquery-analytics",
      "candidates": [
        "bigquery-analytics"
      ],
      "allowReadFallback": false,
      "trafficDistribution": "headroom"
    }
  }
} as const satisfies FederatedDataPlanePolicyDefinition;
