import { useEffect, useState } from "react";

import { CollabField, CollabNotice, collabButton, collabInput, collabPrimary } from "../collaboration-ui";

import type { CreatorTeam, CreatorTeamGroup, CreatorTeamInvite, CreatorTeamMember } from "../../../../../../packages/contracts/src/creator-hiring";

import { api, getApiErrorMessage } from "@/infrastructure/api";

const root = "/collaborations/teams";
export function CreatorTeamsPanel({ actor }: { actor: string }) {
  const [teams, setTeams] = useState<CreatorTeam[]>([]), [invitations, setInvitations] = useState<CreatorTeamInvite[]>([]), [selected, setSelected] = useState("");
  const [name, setName] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [refresh, setRefresh] = useState(0);
  useEffect(() => { const c = new AbortController(); void Promise.all([api.get<CreatorTeam[]>(root, { signal: c.signal }), api.get<CreatorTeamInvite[]>(`${root}/invitations`, { signal: c.signal })]).then(([t, i]) => { if (!c.signal.aborted) { setTeams(t); setInvitations(i); } }).catch(async (e) => { const m = await getApiErrorMessage(e, "팀을 불러오지 못했어요."); if (!c.signal.aborted) setError(m); }); return () => c.abort(); }, [refresh]);
  async function act(work: () => Promise<unknown>) { if (busy) return; setBusy(true); setError(""); try { await work(); setRefresh((v) => v + 1); } catch (e) { setError(await getApiErrorMessage(e, "팀 요청을 처리하지 못했어요.")); } finally { setBusy(false); } }
  const team = teams.find((t) => t.id === selected);
  return <section className="space-y-4 rounded-2xl border border-line p-5"><h2 className="text-xl font-bold">내 팀·그룹</h2><p className="text-sm text-fg-3">팀은 구성원 정리와 회의·알림을 위한 공간입니다. 초대 수락이나 그룹 가입으로 원고와 다른 사람의 이력서 권한이 생기지 않습니다.</p>{error && <CollabNotice error>{error}</CollabNotice>}
    <form className="flex items-end gap-3" onSubmit={(e) => { e.preventDefault(); void act(async () => { const v = await api.post<{ id: string }>(root, { name }); setSelected(v.id); setName(""); }); }}><CollabField label="새 팀 이름"><input required maxLength={100} className={collabInput} value={name} onChange={(e) => setName(e.target.value)} /></CollabField><button className={collabPrimary} disabled={busy} type="submit">팀 만들기</button></form>
    {invitations.map((i) => <article key={i.teamId} className="space-y-2 rounded border border-line p-3"><h3 className="font-bold">{i.teamName}의 팀 초대</h3><p className="text-sm">{new Date(i.expiresAt).toLocaleString("ko-KR")}까지 유효</p><div className="flex gap-2">{[true, false].map((accept) => <button key={String(accept)} className={collabButton} disabled={busy} onClick={() => { void act(() => api.post(`${root}/${i.teamId}/respond`, { accept, inviteRevision: i.revision })); }}>{accept ? "내 계정으로 초대 수락" : "거절"}</button>)}</div></article>)}
    <div className="flex flex-wrap gap-2">{teams.map((t) => <button key={t.id} className={collabButton} aria-pressed={selected === t.id} onClick={() => setSelected(t.id)}>{t.name} · {t.memberCount}명</button>)}</div>{teams.length === 0 && !error && <p>참여 중인 팀이 없어요.</p>}
    {team && <TeamDetails key={`${team.id}:${refresh}`} team={team} actor={actor} changed={() => setRefresh((v) => v + 1)} />}
  </section>;
}
function TeamDetails({ team, actor, changed }: { team: CreatorTeam; actor: string; changed: () => void }) {
  const [members, setMembers] = useState<CreatorTeamMember[]>([]), [groups, setGroups] = useState<CreatorTeamGroup[]>([]);
  const [name, setName] = useState(team.name), [target, setTarget] = useState("");
  const [edit, setEdit] = useState<{ id: string | null; name: string; memberIds: string[] } | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const path = `${root}/${team.id}`, owner = team.myRole === "owner";
  useEffect(() => { const c = new AbortController(); void Promise.all([api.get<CreatorTeamMember[]>(`${path}/members`, { signal: c.signal }), api.get<CreatorTeamGroup[]>(`${path}/groups`, { signal: c.signal })]).then(([m, g]) => { if (!c.signal.aborted) { setMembers(m); setGroups(g); } }).catch(async (e) => { const message = await getApiErrorMessage(e, "팀 구성을 불러오지 못했어요."); if (!c.signal.aborted) setError(message); }); return () => c.abort(); }, [path]);
  async function act(work: () => Promise<unknown>) { if (busy) return; setBusy(true); setError(""); try { await work(); changed(); } catch (e) { setError(await getApiErrorMessage(e, "팀을 변경하지 못했어요.")); } finally { setBusy(false); } }
  return <div className="space-y-4 border-t border-line pt-4"><h3 className="text-lg font-bold">{team.name}</h3>{error && <CollabNotice error>{error}</CollabNotice>}
    {owner && <><form className="flex items-end gap-3" onSubmit={(e) => { e.preventDefault(); void act(() => api.patch(path, { name, expectedRevision: team.revision })); }}><CollabField label="팀 이름 변경"><input required maxLength={100} className={collabInput} value={name} onChange={(e) => setName(e.target.value)} /></CollabField><button type="submit" className={collabButton} disabled={busy}>이름 저장</button></form>
      <form className="flex items-end gap-3" onSubmit={(e) => { e.preventDefault(); void act(() => api.post(`${path}/invitations`, { targetAccountId: target })); }}><CollabField label="초대할 계정 ID" hint="상대방 프로필 주소 /u/ 뒤의 계정 ID · 7일간 유효"><input required maxLength={128} className={collabInput} value={target} onChange={(e) => setTarget(e.target.value)} /></CollabField><button type="submit" className={collabButton} disabled={busy}>계정 지정 초대</button></form></>}
    <ul className="space-y-2">{members.map((m) => <li key={m.userId} className="flex flex-wrap items-center justify-between gap-2 rounded border border-line p-3"><span>{m.displayName} · {m.role === "owner" ? "소유자" : m.status === "active" ? "구성원" : "초대 대기"}{m.inviteExpiresAt ? ` (${new Date(m.inviteExpiresAt).toLocaleDateString("ko-KR")}까지)` : ""}</span>{m.role !== "owner" && (owner || m.userId === actor) && <button className={collabButton} disabled={busy} onClick={() => { if (globalThis.confirm(m.userId === actor ? "팀에서 탈퇴할까요?" : "구성원 또는 대기 초대를 제거할까요?")) void act(() => api.delete(`${path}/members/${encodeURIComponent(m.userId)}`)); }}>{m.userId === actor ? "팀 탈퇴" : "구성원·초대 제거"}</button>}</li>)}</ul>
    <h4 className="font-bold">이름별 그룹</h4>{owner && <button className={collabButton} onClick={() => setEdit({ id: null, name: "", memberIds: [] })}>그룹 만들기</button>}
    {groups.map((g) => <article key={g.id} className="space-y-2 rounded border border-line p-3"><h5 className="font-semibold">{g.name}</h5><p className="text-sm">{g.memberIds.map((id) => members.find((m) => m.userId === id)?.displayName ?? "구성원").join(" · ") || "구성원 없음"}</p>{owner && <div className="flex gap-2"><button className={collabButton} disabled={busy} onClick={() => setEdit(g)}>그룹·구성원 수정</button><button className={collabButton} disabled={busy} onClick={() => { void act(() => api.delete(`${path}/groups/${g.id}`)); }}>그룹 삭제</button></div>}</article>)}
    {edit && <form className="space-y-3 rounded border border-line p-4" onSubmit={(e) => { e.preventDefault(); const body = { name: edit.name, memberIds: edit.memberIds }; void act(() => edit.id ? api.patch(`${path}/groups/${edit.id}`, body) : api.post(`${path}/groups`, body)); }}><CollabField label="그룹 이름"><input required maxLength={80} className={collabInput} value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></CollabField><fieldset><legend>그룹 구성원</legend>{members.filter((m) => m.status === "active").map((m) => <label key={m.userId} className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={edit.memberIds.includes(m.userId)} onChange={() => setEdit({ ...edit, memberIds: edit.memberIds.includes(m.userId) ? edit.memberIds.filter((id) => id !== m.userId) : [...edit.memberIds, m.userId] })} />{m.displayName}</label>)}</fieldset><button type="submit" className={collabPrimary} disabled={busy}>그룹 저장</button></form>}
  </div>;
}
