import {
  defineStudioBrushCompositionNode as node,
  type StudioBrushCompositionNode,
} from "./studio-brush-composition-types";

export const STUDIO_BRUSH_COMPOSITION_NODES_A: readonly StudioBrushCompositionNode[] =
  Object.freeze([
    node({ id: "direct-input", slot: "motion", label: "다이렉트", provider: "Native Pointer", description: "지연을 최소화한 직접 추종", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "adaptive-ema", slot: "motion", label: "적응형 EMA", provider: "ToonStudio", description: "저속 흔들림은 줄이고 빠른 획은 직접 추종", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "spring-modeler", slot: "motion", label: "스프링 모델러", provider: "ToonStudio", description: "질량·탄성·마찰이 있는 부드러운 필기감", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "google-ink-modeler", slot: "motion", label: "Google Ink 모델러", provider: "Google Ink", description: "예측과 종점 보정을 포함한 모델링된 입력", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "lazy-leash", slot: "motion", label: "풀드 스트링", provider: "lazy-brush", description: "긴 선을 안정적으로 끌어가는 지연형 안정화", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "brush-inertia", slot: "motion", label: "붓 관성", provider: "ToonStudio", description: "큰 촉의 중심이 포인터를 늦게 따라오는 관성", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "webgpu-causal-ink", slot: "carrier", label: "WebGPU 연속 잉크", provider: "ToonStudio WebGPU", description: "저지연 중심선·연속 커버리지", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "perfect-freehand-outline", slot: "carrier", label: "압력 아웃라인", provider: "perfect-freehand", description: "테이퍼가 강한 편집 가능한 외곽선", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "google-ink-mesh", slot: "carrier", label: "Google Ink 메시", provider: "Google Ink", description: "급회전과 코너를 모델링한 메시 스트로크", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "webgpu-stamp-carrier", slot: "carrier", label: "WebGPU 스탬프", provider: "ToonStudio WebGPU", description: "팁·입자·모티프를 호 길이 기준으로 배치", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "webgpu-wet-dabs", slot: "carrier", label: "웻 다브", provider: "ToonStudio WebGPU", description: "수채·수묵용 다층 습식 다브", integration: "connected", rights: "permissive", cost: "balanced", supportedFamilies: ["watercolor"] }),
    node({ id: "webgpu-bristle-ribbon", slot: "carrier", label: "강모 리본", provider: "ToonStudio WebGPU", description: "평행 강모와 필버트·플랫 리본", integration: "connected", rights: "permissive", cost: "balanced", supportedFamilies: ["oil", "brush"] }),
    node({ id: "libmypaint-natural-media", slot: "carrier", label: "MyPaint 자연매체", provider: "libmypaint", description: ".myb 다브·하드니스·스머지 동역학", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "hokusai-myb-worker", slot: "carrier", label: "Hokusai MYB", provider: "Hokusai WASM", description: "Rust/WASM 기반 자연매체 타일 엔진", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "krita-hairy-carrier", slot: "carrier", label: "Krita Hairy", provider: "Krita PaintOp", description: "개별 털의 접촉·벌어짐·갈필", integration: "lab", rights: "copyleft", cost: "intensive" }),
    node({ id: "p5-flow-field-generator", slot: "carrier", label: "p5.brush 플로우필드", provider: "p5.brush", description: "정착형 벡터필드·매스 스트로크 생성", integration: "adapter-ready", rights: "permissive", cost: "intensive" }),
    node({ id: "round-sdf", slot: "tip", label: "원형 SDF", provider: "ToonStudio WebGPU", description: "깨끗한 원형·타원형 촉", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "chisel-ribbon", slot: "tip", label: "치즐 리본", provider: "ToonStudio WebGPU", description: "틸트·회전에 반응하는 평촉", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "image-alpha-stamp", slot: "tip", label: "이미지 알파 팁", provider: "ToonStudio", description: "PNG·SDF 사용자 팁", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "dual-tip-krita", slot: "tip", label: "듀얼 팁", provider: "Krita Core", description: "두 팁의 multiply·screen 마스크 합성", integration: "connected", rights: "copyleft", cost: "balanced" }),
    node({ id: "bristle-tuft", slot: "tip", label: "강모 터프트", provider: "ToonStudio WebGPU", description: "다중 털 뿌리와 접촉면", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "rake-tip", slot: "tip", label: "갈퀴 팁", provider: "ToonStudio WebGPU", description: "평행선·컨투어 해칭 촉", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "normal-map-tip", slot: "tip", label: "노멀맵 팁", provider: "pigment-painter", description: "릴리프·광택을 가진 방향성 팁", integration: "lab", rights: "copyleft", cost: "intensive" }),
    node({ id: "sponge-sdf", slot: "tip", label: "스펀지 팁", provider: "ToonStudio WebGPU", description: "불규칙 공극이 있는 수채·과슈 촉", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "smooth-paper", slot: "surface", label: "매끈한 종이", provider: "ToonStudio", description: "표면 변조가 없는 기준 바탕", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "paper-height-field", slot: "surface", label: "종이 높이 필드", provider: "ToonStudio WebGPU", description: "봉우리·골에 따른 건식 입자 접촉", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "watercolor-paper", slot: "surface", label: "수채지", provider: "ToonStudio WebGPU", description: "높이·흡수율·사이징을 가진 습식 표면", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "paper-fiber-field", slot: "surface", label: "섬유 방향 필드", provider: "Inkwash / MoXi", description: "종이 섬유를 따라 갈라지는 번짐", integration: "adapter-ready", rights: "private-grant", cost: "balanced" }),
    node({ id: "canvas-weave", slot: "surface", label: "캔버스 직조", provider: "ToonStudio WebGPU", description: "경사·위사와 물감 걸림", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "display-film-profile", slot: "surface", label: "화면 필름 프로필", provider: "ToonStudio", description: "유리·무광·종이질감 필름의 가상 마찰", integration: "adapter-ready", rights: "permissive", cost: "light" }),
    node({ id: "scanned-exemplar-surface", slot: "surface", label: "실물 캡처 표면", provider: "RealBrush-derived", description: "스캔한 종이·재료 exemplar atlas", integration: "lab", rights: "permissive", cost: "intensive" }),
  ]);
