import {
  defineStudioBrushCompositionNode as node,
  type StudioBrushCompositionNode,
} from "./studio-brush-composition-types";

export const STUDIO_BRUSH_COMPOSITION_NODES_B: readonly StudioBrushCompositionNode[] =
  Object.freeze([
    node({ id: "ink-deposit", slot: "deposition", label: "잉크", provider: "ToonStudio", description: "깨끗한 잉크 커버리지", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "flat-marker-deposit", slot: "deposition", label: "플랫 마커", provider: "ToonStudio WebGPU", description: "균일한 바디와 누적 제한", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "dry-pigment", slot: "deposition", label: "건식 안료", provider: "ToonStudio WebGPU", description: "흑연·목탄·초크·파스텔 입자", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "wet-pigment", slot: "deposition", label: "습식 안료", provider: "ToonStudio / Inkwash", description: "수분과 함께 이동·정착하는 안료", integration: "connected", rights: "private-grant", cost: "balanced" }),
    node({ id: "water-only", slot: "deposition", label: "순수 물", provider: "Inkwash", description: "새 색 없이 수분·유속만 추가", integration: "connected", rights: "private-grant", cost: "balanced", supportedFamilies: ["watercolor"] }),
    node({ id: "loaded-paint", slot: "deposition", label: "적재 물감", provider: "ToonStudio WebGPU", description: "reservoir에서 소모되는 유화·과슈", integration: "connected", rights: "permissive", cost: "balanced", supportedFamilies: ["oil", "watercolor", "brush"] }),
    node({ id: "height-paint", slot: "deposition", label: "높이 물감", provider: "ToonStudio WebGPU", description: "임파스토 높이와 능선을 함께 도포", integration: "connected", rights: "permissive", cost: "intensive", supportedFamilies: ["oil", "brush"] }),
    node({ id: "aerosol-particle", slot: "deposition", label: "에어·입자", provider: "ToonStudio WebGPU", description: "미스트·스프레이·스플래터", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "motif-deposit", slot: "deposition", label: "모티프", provider: "ToonStudio Pattern", description: "패턴·문양·스탬프 자산 도포", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "rgb-color", slot: "pigment", label: "RGB", provider: "Browser", description: "일반 그래픽 색상 합성", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "spectral-wgsl", slot: "pigment", label: "Spectral.js WGSL", provider: "Spectral.js", description: "스펙트럼 반사율 기반 안료 혼합", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "open-km-wgsl", slot: "pigment", label: "open-km K/S", provider: "open-km", description: "측정 K/S·두께·바탕을 반영하는 KM solver", integration: "lab", rights: "permissive", cost: "intensive" }),
    node({ id: "pigment-painter-lut", slot: "pigment", label: "Pigment LUT", provider: "pigment-painter", description: "WASM 최적화 LUT와 빠른 반복 혼합", integration: "lab", rights: "copyleft", cost: "balanced" }),
    node({ id: "mixbox-lut", slot: "pigment", label: "Mixbox LUT", provider: "Mixbox", description: "대체 불가능성 검증용 latent 안료 혼합", integration: "lab", rights: "private-grant", cost: "balanced" }),
    node({ id: "inkwash-optical-density", slot: "pigment", label: "Inkwash 광학 밀도", provider: "Inkwash", description: "리빙 잉크의 이동·고정 색소 표시 모델", integration: "adapter-ready", rights: "private-grant", cost: "balanced" }),
    node({ id: "rainbow-arc-length", slot: "pigment", label: "거리 기반 레인보우", provider: "ToonStudio WebGPU", description: "획 진행 거리에 고정된 색상 순환", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "no-pickup", slot: "pickup", label: "픽업 없음", provider: "ToonStudio", description: "아래색을 읽지 않는 순수 도포", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "simple-reservoir", slot: "pickup", label: "WebGPU Reservoir", provider: "ToonStudio WebGPU", description: "아래색 픽업·적재·거리 기반 소모", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "libmypaint-smudge", slot: "pickup", label: "MyPaint Smudge", provider: "libmypaint", description: "MYB paint mode와 색상 적재", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "krita-color-smudge", slot: "pickup", label: "Krita Color Smudge", provider: "Krita PaintOp", description: "성숙한 pickup·smear·deposit 조합", integration: "lab", rights: "copyleft", cost: "intensive" }),
    node({ id: "pigment-painter-reservoir", slot: "pickup", label: "Pigment Painter Reservoir", provider: "pigment-painter", description: "scatter pickup과 다색 reservoir", integration: "lab", rights: "copyleft", cost: "intensive" }),
    node({ id: "no-physics", slot: "physics", label: "물리 없음", provider: "ToonStudio", description: "즉시 도포만 수행", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "dry-contact-webgpu", slot: "physics", label: "건식 접촉", provider: "ToonStudio WebGPU", description: "마찰·종이 이빨·마모·가루", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "wet-diffusion-webgpu", slot: "physics", label: "웻 확산", provider: "ToonStudio WebGPU", description: "엣지·과립·간이 확산", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "inkwash-fluid", slot: "physics", label: "Inkwash 리빙 유체", provider: "Inkwash", description: "수분·유속·이동/고정 안료·건조", integration: "connected", rights: "private-grant", cost: "intensive", supportedFamilies: ["watercolor"] }),
    node({ id: "porous-paper", slot: "physics", label: "다공성 종이", provider: "MoXi-derived", description: "섬유·모세관·내부 흡수", integration: "lab", rights: "permissive", cost: "intensive", supportedFamilies: ["watercolor"] }),
    node({ id: "thin-film-drip", slot: "physics", label: "Thin-film 드립", provider: "ToonStudio Research", description: "중력 방향의 얇은 물감막과 드립", integration: "lab", rights: "permissive", cost: "intensive" }),
    node({ id: "bristle-webgpu", slot: "physics", label: "WebGPU 강모", provider: "ToonStudio WebGPU", description: "터프트 벌어짐·복원·물감 소모", integration: "connected", rights: "permissive", cost: "intensive", supportedFamilies: ["oil", "brush"] }),
    node({ id: "particle-webgpu", slot: "physics", label: "WebGPU 입자", provider: "ToonStudio WebGPU", description: "스프레이·충돌·중력·수명", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "reaction-diffusion", slot: "physics", label: "반응확산", provider: "ToonStudio Research", description: "덴드라이트·균열·부식 성장", integration: "lab", rights: "permissive", cost: "intensive" }),
    node({ id: "no-pattern", slot: "pattern", label: "패턴 없음", provider: "ToonStudio", description: "재료 자국만 사용", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "document-grid", slot: "pattern", label: "문서 고정 격자", provider: "ToonStudio WebGPU", description: "스크린톤·격자 위상이 문서에 고정", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "along-path", slot: "pattern", label: "경로 반복", provider: "ToonStudio Pattern", description: "스티치·체인·글리프를 경로에 정렬", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "brick-staggered", slot: "pattern", label: "브릭 하프드롭", provider: "ToonStudio Pattern", description: "벽돌·타일의 staggered 반복", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "weave-grid", slot: "pattern", label: "패브릭 위브", provider: "ToonStudio Pattern", description: "경사·위사가 교차하는 직조 문양", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "blue-noise-scatter", slot: "pattern", label: "Blue-noise 산란", provider: "ToonStudio WebGPU", description: "반복 흔적이 적은 모티프 배치", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "radial-burst", slot: "pattern", label: "방사 버스트", provider: "ToonStudio WebGPU", description: "중심 고정 속도선·방사 모티프", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "kaleido-symmetry", slot: "pattern", label: "칼레이도 대칭", provider: "ToonStudio WebGPU", description: "반사·회전·스파이로 복제", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "p5-flow-field", slot: "pattern", label: "p5.brush 플로우필드", provider: "p5.brush", description: "벡터장 기반 해칭·mass stroke", integration: "adapter-ready", rights: "permissive", cost: "intensive" }),
    node({ id: "foliage-cluster", slot: "pattern", label: "폴리지 클러스터", provider: "ToonStudio Pattern", description: "방향성 잎·꽃·이끼 군집", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "stitch-chain", slot: "pattern", label: "스티치·체인", provider: "ToonStudio Pattern", description: "서로 연결되는 반복 모티프", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "visual-only", slot: "feedback", label: "시각 프리뷰", provider: "ToonStudio", description: "촉·틸트·필압·예측 꼬리 표시", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "hover-footprint", slot: "feedback", label: "호버 접촉면", provider: "Pointer Events", description: "펜 호버 중 촉 방향과 예상 범위 표시", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "scratch-audio", slot: "feedback", label: "마찰음", provider: "WebAudio", description: "속도·압력·종이결 기반 필기음", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "native-haptic", slot: "feedback", label: "네이티브 햅틱", provider: "Native Pencil Bridge", description: "스냅·도구 전환·표면 접촉 햅틱", integration: "lab", rights: "permissive", cost: "light" }),
    node({ id: "vector-path", slot: "output", label: "벡터 경로", provider: "ToonStudio / CanvasKit", description: "편집 가능한 외곽선 경로", integration: "connected", rights: "permissive", cost: "light" }),
    node({ id: "vector-mesh", slot: "output", label: "벡터 메시", provider: "Google Ink / WebGPU", description: "증분 삼각형 메시", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "raster-tiles", slot: "output", label: "래스터 타일", provider: "ToonStudio WebGPU", description: "자연매체·물리 필드용 타일 출력", integration: "connected", rights: "permissive", cost: "balanced" }),
    node({ id: "hybrid-proxy", slot: "output", label: "하이브리드 프록시", provider: "ToonStudio", description: "편집 중심선과 canonical 래스터를 함께 저장", integration: "adapter-ready", rights: "permissive", cost: "balanced" }),
    node({ id: "settled-generator", slot: "output", label: "정착형 생성기", provider: "p5.brush / Worker", description: "라이브가 아닌 완성 결과를 생성", integration: "adapter-ready", rights: "permissive", cost: "intensive" }),
  ]);
