import { describe, expect, it, vi, afterEach } from "vitest";

import { calculateSaju, resolveFortuneBirth, solarTermsForYear, fortuneMonthDays, fortuneKstDate, fortuneTenGod, fortuneLifeNumber, matchFortuneDream, FORTUNE_EXPERIENCES, buildFortuneReading, fortuneReadingText, drawTarot, analyzeCompatibility } from "./index";

afterEach(() => { vi.unstubAllEnvs(); vi.useRealTimers(); });
describe("Korean calendar and pillar boundaries", () => {
  it("uses the known 2000-01-01 day and January pre-sohan month", () => { const chart = calculateSaju("2000-01-01"); expect(chart.dayPillar.kan + chart.dayPillar.ji).toBe("戊午"); expect(chart.monthPillar.ji).toBe("子"); });
  it("does not fabricate a time or count its elements", () => { const chart = calculateSaju("1990-06-15"); expect(chart.birthTimeKnown).toBe(false); expect(chart.hourPillar.kan).toBe(""); expect(Object.values(chart.elementsRatio).reduce((a, b) => a + b, 0)).toBe(100); expect(chart.calculationNotes?.join(" ")).toContain("6글자"); });
  it("distinguishes midnight from unknown birth time", () => { const chart = calculateSaju("1990-06-15", "00:00"); expect(chart.birthTimeKnown).toBe(true); expect(chart.hourPillar.ji).toBe("子"); expect(calculateSaju("1990-06-15", "01:00").hourPillar.ji).toBe("丑"); });
  it("supports both explicit day rollover conventions", () => { expect(calculateSaju("1990-06-15", "23:00").dayPillar).toEqual(calculateSaju("1990-06-15", "12:00").dayPillar); expect(calculateSaju("1990-06-15", "23:00", { dayBoundary: "zi" }).dayPillar).toEqual(calculateSaju("1990-06-16", "00:00").dayPillar); });
  it.each([1900, 2000, 2026, 2050])("has 24 unique ordered solar terms for %i", (year) => { const terms = solarTermsForYear(year); expect(terms).toHaveLength(24); expect(new Set(terms.map((t) => t.name)).size).toBe(24); expect(terms.filter((t) => t.isMonthBoundary)).toHaveLength(12); expect(terms.every((t) => t.atKst.startsWith(String(year)))).toBe(true); expect(terms.map((t) => t.timestamp)).toEqual(terms.map((t) => t.timestamp).sort((a,b) => a-b)); });
  it("changes year/month at 2026 ipchun in KST, not midnight or China time", () => { const term = solarTermsForYear(2026).find((t) => t.name === "입춘")!; expect(term.atKst).toBe("2026-02-04 05:02:08"); expect(calculateSaju("2026-02-04", "05:02").yearPillar.kan).toBe("乙"); expect(calculateSaju("2026-02-04", "05:03").yearPillar.kan).toBe("丙"); expect(calculateSaju("2026-02-04").calculationNotes?.join(" ")).toContain("절입"); });
  it("converts Korean leap months and rejects nonexistent ones", () => { expect(resolveFortuneBirth({date:"2017-05-01",calendar:"lunar",leapMonth:true}).solarDate).toBe("2017-06-24"); expect(() => resolveFortuneBirth({date:"2017-03-01",calendar:"lunar",leapMonth:true})).toThrow(); });
  it.each(["2023-02-29", "2026-04-31", "1899-12-31", "2051-01-01", "2000-00-01", "not-a-date"])("rejects %s without silent date normalization", (date) => expect(() => calculateSaju(date)).toThrow());
  it.each(["24:00", "12:60", "1:00", "NaN"])("rejects malformed time %s", (time) => expect(() => calculateSaju("2000-01-01",time)).toThrow());
  it("uses UTC arithmetic independent of process TZ", () => { vi.stubEnv("TZ", "America/Los_Angeles"); const a=calculateSaju("2000-03-26", "00:30"); vi.stubEnv("TZ", "Asia/Seoul"); expect(calculateSaju("2000-03-26", "00:30")).toEqual(a); expect(fortuneKstDate(new Date("2026-09-12T15:00:00Z"))).toBe("2026-09-13"); });
  it("handles February leap day and Korean lunar calendar day details", () => { const days=fortuneMonthDays("2024-02"); expect(days).toHaveLength(29); expect(days[9].lunar.month).toBe(1); expect(days[9].lunar.day).toBe(1); });
});
describe("fortune experiences", () => {
  const input={birth:{date:"1990-06-15"},partner:{date:"1992-11-23"},date:"2026-09-13",month:"2026-09",year:2026,question:"바다에서 고양이를 만났어요"};
  it("has 29 unique experiences", () => { expect(FORTUNE_EXPERIENCES).toHaveLength(29); expect(new Set(FORTUNE_EXPERIENCES.map((e)=>e.id)).size).toBe(29); });
  it.each(FORTUNE_EXPERIENCES.map((e)=>e.id))("generates %s locally with caveats", async(id) => { const reading=await buildFortuneReading(id,input); expect(reading.id).toBe(id); expect(reading.summary.length).toBeGreaterThan(10); expect(reading.notes[0]).toContain("확률이 아닙니다"); expect(JSON.stringify(reading)).not.toContain("undefined"); });
  it("rejects unknown experience and missing/invalid input", async () => { await expect(buildFortuneReading("not-real")).rejects.toThrow(); await expect(buildFortuneReading("saju")).rejects.toThrow(); await expect(buildFortuneReading("dream",{question:"  "})).rejects.toThrow(); await expect(buildFortuneReading("saju",{birth:{date:"2050-01-01"}})).rejects.toThrow(); });
  it("calculates ten gods using polarity rather than five-group shortcuts", () => { expect(["甲","乙","丙","丁","戊","己","庚","辛","壬","癸"].map((k)=>fortuneTenGod("甲",k))).toEqual(["비견","겁재","식신","상관","편재","정재","편관","정관","편인","정인"]); expect(fortuneTenGod("乙","甲")).toBe("겁재"); });
  it("keeps compatibility symmetric and includes relationship-specific advice", async () => { const a=calculateSaju("1990-06-15"),b=calculateSaju("1992-11-23"); expect(analyzeCompatibility(a,b).score).toBe(analyzeCompatibility(b,a).score); const love=await buildFortuneReading("love-match",input),team=await buildFortuneReading("team-match",input); expect(love.sections.at(-1)).not.toEqual(team.sections.at(-1)); });
  it("uses user choice for three-card tarot without duplicates", async () => { const a=await drawTarot([],"leona",0,"three"),b=await drawTarot([],"leona",1,"three"); expect(new Set(a.cards.map((c)=>c.id)).size).toBe(3); expect(a.cards.map((c)=>c.id)).not.toEqual(b.cards.map((c)=>c.id)); expect((await drawTarot([],"leona",0,"three")).cards).toEqual(a.cards); });
  it("renders seven/12/30 timeline entries with a bounded content index", async () => { for(const [id,length] of [["weekly",7],["yearly",12],["monthly",30]] as const){const r=await buildFortuneReading(id,input);expect(r.trend).toHaveLength(length);expect(r.trend?.every((x)=>x.value>=0&&x.value<=100)).toBe(true);} });
  it("lets the user explicitly choose forward/reverse cycles", async () => { const a=await buildFortuneReading("cycles",{...input,cycleDirection:"forward"}),b=await buildFortuneReading("cycles",{...input,cycleDirection:"reverse"}); expect(a.sections).toHaveLength(8);expect(a.sections[0]).not.toEqual(b.sections[0]);expect(a.notes.join(" ")).toContain("직접 선택"); });
  it("reduces a real date and keeps Korean dream matching useful without claims", () => { expect(fortuneLifeNumber("1990-06-15").number).toBe(4);expect(matchFortuneDream(input.question)).toHaveLength(2);expect(matchFortuneDream("이빨이 빠지는 꿈")[0].items?.join(" ")).toContain("징조가 아닙니다");expect(matchFortuneDream("로봇과 우주선")[0].title).toContain("이름 붙이지"); });
  it("never includes birth time/date or dream original in public saved text", async () => { for(const id of ["saju","numerology","dream"]){const r=await buildFortuneReading(id,input);const text=fortuneReadingText(r);expect(text).not.toContain(input.birth.date);expect(text).not.toContain(input.question);if(id==="numerology")expect(text).not.toContain("1 + 9 + 9 + 0");} });
});
