export const BRUSH_STUDIO_V6_SCHEMA_VERSION = 6 as const;

export type BrushStudioV6QualityGoal = "responsive" | "balanced" | "material" | "cinematic";
export type BrushStudioV6DeviceProfile = "desktop-pen" | "tablet-pen" | "touch-hybrid" | "mouse";
export type BrushStudioV6TouchPolicy = "pen-only" | "pen-draw-finger-pan" | "pen-draw-two-finger-gesture" | "pen-ink-finger-water" | "touch-draw";
export type BrushStudioV6InputTransport = "auto" | "raw-coalesced" | "move-coalesced" | "move-basic";
export type BrushStudioV6FilmProfile = "glass" | "matte" | "paperlike-fine" | "paperlike-rough";
export type BrushStudioV6Slot = "input" | "motion" | "carrier" | "tip" | "surface" | "deposition" | "pickup" | "pigment" | "physics" | "pattern" | "finish" | "output";
export type BrushStudioV6Phase = "hover" | "preview" | "live" | "settle" | "commit" | "export";
export type BrushStudioV6Domain = "main" | "input-worker" | "webgpu" | "wasm-worker" | "webgl-worker" | "cpu-worker";
export type BrushStudioV6Authority = "input" | "motion" | "carrier" | "surface" | "deposition" | "pickup" | "pigment" | "wet" | "bristle" | "particle" | "reaction" | "height" | "pattern" | "composite" | "output";
export type BrushStudioV6PortType = "raw-samples" | "modeled-samples" | "path" | "mesh" | "contact-patches" | "marks" | "paper-field" | "coverage-field" | "pigment-field" | "wet-field" | "velocity-field" | "reservoir-state" | "height-field" | "pattern-field" | "rgba-tiles" | "vector-artifact";
export type BrushStudioV6Capability = "webgpu" | "wasm" | "webgl2" | "shared-array-buffer" | "pointerrawupdate" | "coalesced-events" | "predicted-events" | "pressure" | "tilt" | "twist" | "hover";
export type BrushStudioV6Rights = "internal" | "permissive" | "copyleft" | "private-grant";
export type BrushStudioV6IssueSeverity = "error" | "warning" | "info";
export type BrushStudioV6NodeId = string;

export interface BrushStudioV6NodeDescriptor {
  readonly id: BrushStudioV6NodeId;
  readonly label: string;
  readonly slot: BrushStudioV6Slot;
  readonly provider: string;
  readonly description: string;
  readonly domain: BrushStudioV6Domain;
  readonly phase: BrushStudioV6Phase;
  readonly authority?: BrushStudioV6Authority;
  readonly accepts: readonly BrushStudioV6PortType[];
  readonly emits: readonly BrushStudioV6PortType[];
  readonly requires: readonly BrushStudioV6Capability[];
  readonly rights: BrushStudioV6Rights;
  readonly latency: number;
  readonly fidelity: number;
  readonly uniqueness: number;
  readonly memory: number;
  readonly tags: readonly string[];
}

type CompactNode = readonly [BrushStudioV6NodeId, BrushStudioV6Slot, BrushStudioV6Domain, BrushStudioV6Phase, BrushStudioV6Authority | undefined, BrushStudioV6Rights, requires?: readonly BrushStudioV6Capability[]];
const W = ["webgpu"] as const;
const A = ["wasm"] as const;
const G = ["webgl2"] as const;
const T = ["webgpu", "tilt"] as const;
const NODE_SPECS: readonly CompactNode[] = [
  ["input-pointer-v3", "input", "input-worker", "preview", "input", "internal", ["pressure"]],
  ["motion-direct", "motion", "input-worker", "preview", "motion", "internal"], ["motion-adaptive-ema", "motion", "input-worker", "preview", "motion", "internal"], ["motion-spring", "motion", "input-worker", "preview", "motion", "internal"], ["motion-google-ink", "motion", "wasm-worker", "preview", "motion", "permissive", ["wasm", "predicted-events"]], ["motion-brush-inertia", "motion", "input-worker", "preview", "motion", "internal"], ["motion-lazy-leash", "motion", "input-worker", "preview", "motion", "internal"],
  ["carrier-webgpu-centerline", "carrier", "webgpu", "live", "carrier", "internal", W], ["carrier-perfect-outline", "carrier", "wasm-worker", "live", "carrier", "permissive", A], ["carrier-google-mesh", "carrier", "wasm-worker", "live", "carrier", "permissive", A], ["carrier-webgpu-ribbon", "carrier", "webgpu", "live", "carrier", "internal", T], ["carrier-libmypaint-dabs", "carrier", "wasm-worker", "live", "carrier", "permissive", A], ["carrier-hokusai-dabs", "carrier", "wasm-worker", "live", "carrier", "permissive", A], ["carrier-krita-hairy", "carrier", "wasm-worker", "live", "carrier", "copyleft", A], ["carrier-webgpu-particles", "carrier", "webgpu", "live", "carrier", "internal", W], ["carrier-p5-flow", "carrier", "webgl-worker", "settle", "carrier", "permissive", G],
  ["tip-round-sdf", "tip", "webgpu", "live", undefined, "internal", W], ["tip-chisel-sdf", "tip", "webgpu", "live", undefined, "internal", T], ["tip-grain-exemplar", "tip", "webgpu", "live", undefined, "internal", W], ["tip-krita-dual", "tip", "wasm-worker", "live", undefined, "copyleft", A], ["tip-pigment-normal", "tip", "webgpu", "live", undefined, "copyleft", W], ["tip-motif-atlas", "tip", "webgpu", "live", undefined, "internal", W],
  ["surface-smooth", "surface", "webgpu", "live", "surface", "internal", W], ["surface-kent", "surface", "webgpu", "live", "surface", "internal", W], ["surface-coldpress", "surface", "webgpu", "live", "surface", "internal", W], ["surface-printmaking", "surface", "webgpu", "live", "surface", "internal", W], ["surface-linen", "surface", "webgpu", "live", "surface", "internal", W], ["surface-porous", "surface", "webgpu", "live", "surface", "internal", W], ["surface-realbrush", "surface", "webgpu", "live", "surface", "internal", W],
  ["deposit-ink", "deposition", "webgpu", "live", "deposition", "internal", W], ["deposit-marker", "deposition", "webgpu", "live", "deposition", "internal", W], ["deposit-dry", "deposition", "webgpu", "live", "deposition", "internal", W], ["deposit-wet", "deposition", "webgpu", "live", "deposition", "private-grant", W], ["deposit-oil", "deposition", "webgpu", "live", "deposition", "internal", W], ["deposit-particles", "deposition", "webgpu", "live", "deposition", "internal", W], ["deposit-light", "deposition", "webgpu", "live", "deposition", "internal", W],
  ["pickup-none", "pickup", "webgpu", "live", "pickup", "internal", W], ["pickup-krita-smudge", "pickup", "wasm-worker", "live", "pickup", "copyleft", A], ["pickup-pigment-reservoir", "pickup", "webgpu", "live", "pickup", "copyleft", W],
  ["pigment-rgb", "pigment", "webgpu", "live", "pigment", "internal", W], ["pigment-spectral", "pigment", "webgpu", "live", "pigment", "permissive", W], ["pigment-open-km", "pigment", "webgpu", "live", "pigment", "permissive", W], ["pigment-painter-lut", "pigment", "webgpu", "live", "pigment", "copyleft", W], ["pigment-mixbox", "pigment", "webgpu", "live", "pigment", "private-grant", W], ["pigment-inkwash-density", "pigment", "webgpu", "settle", "pigment", "private-grant", W],
  ["physics-dry-contact", "physics", "webgpu", "live", undefined, "internal", W], ["physics-porous-paper", "physics", "webgpu", "settle", undefined, "internal", W], ["physics-inkwash", "physics", "webgpu", "settle", "wet", "private-grant", W], ["physics-thin-film", "physics", "webgpu", "settle", "wet", "internal", W], ["physics-bristle", "physics", "webgpu", "live", "bristle", "internal", W], ["physics-particles", "physics", "webgpu", "settle", "particle", "internal", W], ["physics-reaction", "physics", "webgpu", "settle", "reaction", "internal", W], ["physics-height", "physics", "webgpu", "settle", "height", "internal", W],
  ["pattern-none", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-dot-tone", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-cross-hatch", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-weave", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-brick", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-foliage", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-stitch", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-kaleido", "pattern", "webgpu", "live", "pattern", "internal", W], ["pattern-flow-field", "pattern", "webgl-worker", "settle", "pattern", "permissive", G], ["pattern-rainbow", "pattern", "webgpu", "live", "pattern", "internal", W],
  ["finish-edge-bloom", "finish", "webgpu", "settle", "composite", "internal", W], ["finish-wet-sheen", "finish", "webgpu", "settle", "composite", "internal", W], ["finish-relief", "finish", "webgpu", "settle", "composite", "internal", W], ["finish-neon", "finish", "webgpu", "live", "composite", "internal", W], ["finish-grain", "finish", "webgpu", "live", "composite", "internal", W], ["finish-chroma", "finish", "webgpu", "settle", "composite", "private-grant", W],
  ["output-raster-tiles", "output", "webgpu", "commit", "output", "internal", W], ["output-hybrid", "output", "webgpu", "commit", "output", "internal", W], ["output-vector", "output", "webgpu", "commit", "output", "internal", W],
];

const LABELS: Readonly<Record<string, string>> = Object.freeze({
  "input-pointer-v3": "Pointer Input V3", "motion-direct": "Direct", "motion-adaptive-ema": "Adaptive EMA", "motion-spring": "Spring", "motion-google-ink": "Google Ink Modeler", "motion-brush-inertia": "Brush Inertia", "motion-lazy-leash": "Lazy Leash",
  "carrier-webgpu-centerline": "WebGPU Centerline", "carrier-perfect-outline": "Perfect Freehand Outline", "carrier-google-mesh": "Google Ink Mesh", "carrier-webgpu-ribbon": "WebGPU Tilt Ribbon", "carrier-libmypaint-dabs": "libmypaint Dabs", "carrier-hokusai-dabs": "Hokusai Dabs", "carrier-krita-hairy": "Krita Hairy Carrier", "carrier-webgpu-particles": "WebGPU Particle Stream", "carrier-p5-flow": "p5.brush Flow Carrier",
  "tip-round-sdf": "Round SDF", "tip-chisel-sdf": "Chisel SDF", "tip-grain-exemplar": "Captured Grain Tip", "tip-krita-dual": "Krita Dual Tip", "tip-pigment-normal": "Normal-mapped Tip", "tip-motif-atlas": "Motif Atlas",
  "surface-smooth": "Smooth Film", "surface-kent": "Kent Paper", "surface-coldpress": "Cold-press Watercolor", "surface-printmaking": "Printmaking Tooth", "surface-linen": "Linen Canvas", "surface-porous": "Porous Fiber", "surface-realbrush": "Captured Material Surface",
  "pickup-none": "No Pickup", "pickup-krita-smudge": "Krita Color Smudge", "pickup-pigment-reservoir": "Pigment Reservoir", "pigment-rgb": "RGB / OKLab", "pigment-spectral": "Spectral WGSL", "pigment-open-km": "Open K/S WGSL", "pigment-painter-lut": "Pigment Painter LUT", "pigment-mixbox": "Mixbox Latent Pigment", "pigment-inkwash-density": "Inkwash Optical Density",
  "physics-dry-contact": "Dry Contact", "physics-porous-paper": "Porous Paper", "physics-inkwash": "Inkwash Wet Flow", "physics-thin-film": "Thin-film Gravity", "physics-bristle": "Bristle Dynamics", "physics-particles": "Particle Ballistics", "physics-reaction": "Reaction–Diffusion", "physics-height": "Height Field",
  "pattern-none": "No Pattern", "pattern-dot-tone": "Document Dot Tone", "pattern-cross-hatch": "Contour Cross Hatch", "pattern-weave": "Fabric Weave", "pattern-brick": "Brick Mortar", "pattern-foliage": "Foliage Cluster", "pattern-stitch": "Stitch / Chain", "pattern-kaleido": "Kaleido Graph", "pattern-flow-field": "Flow-field Mass", "pattern-rainbow": "Rainbow Flow",
  "finish-edge-bloom": "Edge Bloom", "finish-wet-sheen": "Wet Sheen", "finish-relief": "Relief Lighting", "finish-neon": "Neon Bloom", "finish-grain": "Grain Boost", "finish-chroma": "Chromatic Fringe", "output-raster-tiles": "Raster Tile Authority", "output-hybrid": "Hybrid Editable Authority", "output-vector": "Vector Authority",
});

function labelFor(id: string): string { return LABELS[id] ?? id.replace(/^(deposit|surface|carrier|motion|tip|physics|pattern|finish|pigment|pickup|output)-/u, "").split("-").map((part) => part[0]?.toUpperCase() + part.slice(1)).join(" "); }
function providerFor(id: string): string {
  if (id.includes("krita")) return "Krita GPL"; if (id.includes("libmypaint")) return "libmypaint"; if (id.includes("hokusai")) return "Hokusai"; if (id.includes("google")) return "Google Ink"; if (id.includes("perfect")) return "perfect-freehand"; if (id.includes("p5")) return "p5.brush"; if (id.includes("inkwash")) return "Inkwash"; if (id.includes("spectral")) return "Spectral.js"; if (id.includes("open-km")) return "open-km"; if (id.includes("painter")) return "pigment-painter"; if (id.includes("mixbox")) return "Mixbox"; if (id.includes("realbrush") || id.includes("exemplar")) return "RealBrush Exemplar"; return "ToonSpectrum WebGPU";
}
function ports(slot: BrushStudioV6Slot): readonly [readonly BrushStudioV6PortType[], readonly BrushStudioV6PortType[]] {
  const map: Record<BrushStudioV6Slot, readonly [readonly BrushStudioV6PortType[], readonly BrushStudioV6PortType[]]> = {
    input: [[], ["raw-samples"]], motion: [["raw-samples"], ["modeled-samples"]], carrier: [["modeled-samples"], ["path", "mesh", "marks", "contact-patches", "reservoir-state"]], tip: [["path", "mesh", "marks"], ["contact-patches", "height-field"]], surface: [[], ["paper-field"]], deposition: [["contact-patches", "marks", "paper-field"], ["coverage-field", "pigment-field", "height-field"]], pickup: [["contact-patches", "pigment-field"], ["pigment-field", "reservoir-state"]], pigment: [["pigment-field", "coverage-field"], ["pigment-field", "rgba-tiles"]], physics: [["paper-field", "pigment-field", "coverage-field", "height-field"], ["wet-field", "velocity-field", "height-field", "rgba-tiles"]], pattern: [["path", "marks", "coverage-field", "pigment-field"], ["pattern-field", "marks", "pigment-field"]], finish: [["rgba-tiles", "wet-field", "height-field", "paper-field"], ["rgba-tiles"]], output: [["path", "mesh", "rgba-tiles", "coverage-field"], ["rgba-tiles", "vector-artifact"]],
  }; return map[slot];
}
function metric(id: string, domain: BrushStudioV6Domain, kind: "latency" | "fidelity" | "uniqueness" | "memory"): number {
  const external = domain === "wasm-worker" || domain === "webgl-worker"; const physical = /(inkwash|bristle|reaction|height|thin-film|realbrush|krita|open-km)/u.test(id); const procedural = /(kaleido|flow|foliage|stitch|particles)/u.test(id);
  if (kind === "latency") return domain === "webgpu" ? (physical ? 72 : 94) : external ? 58 : 98;
  if (kind === "fidelity") return physical ? 99 : external ? 96 : 92;
  if (kind === "uniqueness") return physical || procedural ? 98 : 72;
  return domain === "webgpu" ? (physical ? 66 : 90) : external ? 64 : 96;
}

export const BRUSH_STUDIO_V6_NODES: readonly BrushStudioV6NodeDescriptor[] = Object.freeze(NODE_SPECS.map(([id, slot, domain, phase, authority, rights, requires = []]) => {
  const [accepts, emits] = ports(slot); const label = labelFor(id);
  return Object.freeze({ id, label, slot, provider: providerFor(id), description: `${label}을(를) V6 품질 그래프의 ${slot} 단계에서 실행합니다.`, domain, phase, authority, accepts, emits, requires: Object.freeze([...requires]), rights, latency: metric(id, domain, "latency"), fidelity: metric(id, domain, "fidelity"), uniqueness: metric(id, domain, "uniqueness"), memory: metric(id, domain, "memory"), tags: Object.freeze([slot, providerFor(id)]) });
}));
const NODE_BY_ID = new Map(BRUSH_STUDIO_V6_NODES.map((entry) => [entry.id, entry]));

export interface BrushStudioV6Slots { readonly input: BrushStudioV6NodeId; readonly motion: BrushStudioV6NodeId; readonly carrier: BrushStudioV6NodeId; readonly tip: BrushStudioV6NodeId; readonly surface: BrushStudioV6NodeId; readonly deposition: BrushStudioV6NodeId; readonly pickup: BrushStudioV6NodeId; readonly pigment: BrushStudioV6NodeId; readonly physics: readonly BrushStudioV6NodeId[]; readonly pattern: BrushStudioV6NodeId; readonly finish: readonly BrushStudioV6NodeId[]; readonly output: BrushStudioV6NodeId; }
export interface BrushStudioV6InputPolicy { readonly transport: BrushStudioV6InputTransport; readonly predictionPreviewOnly: boolean; readonly touchPolicy: BrushStudioV6TouchPolicy; readonly palmRejection: boolean; readonly hoverPreview: boolean; readonly pressureOnset: number; readonly pressureSaturation: number; readonly pressureGamma: number; readonly pressureHysteresis: number; readonly tiltEnabled: boolean; readonly tiltDeadZoneDeg: number; readonly tiltSmoothing: number; readonly twistSmoothing: number; readonly film: BrushStudioV6FilmProfile; readonly audioFeedback: boolean; readonly hapticFeedback: boolean; }
export interface BrushStudioV6Tuning { readonly size: number; readonly opacity: number; readonly flow: number; readonly spacing: number; readonly stabilization: number; readonly surfaceTooth: number; readonly friction: number; readonly absorbency: number; readonly granulation: number; readonly edgeDarkening: number; readonly pickup: number; readonly reservoir: number; readonly wetness: number; readonly diffusion: number; readonly advection: number; readonly evaporation: number; readonly viscosity: number; readonly plasticity: number; readonly gravity: number; readonly bristleStrands: number; readonly bristleIterations: number; readonly particleCount: number; readonly reactionRate: number; readonly patternDensity: number; readonly patternScale: number; readonly patternJitter: number; readonly relief: number; readonly gloss: number; readonly primaryColor: string; readonly secondaryColor: string; }
export interface BrushStudioV6Proofs { readonly mixboxDistinctiveness: { readonly verified: boolean; readonly spectralReproductionFailed: boolean; readonly blindPreference: number; readonly blindDistinguishability: number; readonly meanPathDeltaE: number; }; readonly deterministicPatternSeed: boolean; readonly rasterReceipt: boolean; }
export interface BrushStudioV6Program { readonly schemaVersion: typeof BRUSH_STUDIO_V6_SCHEMA_VERSION; readonly id: string; readonly name: string; readonly description: string; readonly qualityGoal: BrushStudioV6QualityGoal; readonly deviceProfile: BrushStudioV6DeviceProfile; readonly seed: number; readonly input: BrushStudioV6InputPolicy; readonly slots: BrushStudioV6Slots; readonly tuning: BrushStudioV6Tuning; readonly proofs: BrushStudioV6Proofs; }
export interface BrushStudioV6Capabilities { readonly webgpu: boolean; readonly wasm: boolean; readonly webgl2: boolean; readonly sharedArrayBuffer: boolean; readonly pointerRawUpdate: boolean; readonly coalescedEvents: boolean; readonly predictedEvents: boolean; readonly pressure: boolean; readonly tilt: boolean; readonly twist: boolean; readonly hover: boolean; readonly maxTextureDimension2D: number; readonly memoryBudgetMb: number; }
export interface BrushStudioV6Issue { readonly id: string; readonly severity: BrushStudioV6IssueSeverity; readonly title: string; readonly detail: string; readonly fix?: string; }
export interface BrushStudioV6ExecutionPass { readonly id: string; readonly phase: BrushStudioV6Phase; readonly domain: BrushStudioV6Domain; readonly label: string; readonly nodeIds: readonly BrushStudioV6NodeId[]; readonly canonical: boolean; readonly budgetMs: number; }
export interface BrushStudioV6Resource { readonly id: string; readonly format: string; readonly scale: number; readonly owner: BrushStudioV6Authority; readonly estimatedMb: number; }
export interface BrushStudioV6Analysis { readonly valid: boolean; readonly issues: readonly BrushStudioV6Issue[]; readonly nodes: readonly BrushStudioV6NodeDescriptor[]; readonly passes: readonly BrushStudioV6ExecutionPass[]; readonly resources: readonly BrushStudioV6Resource[]; readonly metrics: { readonly handFeel: number; readonly materialFidelity: number; readonly colorFidelity: number; readonly temporalFidelity: number; readonly uniqueness: number; readonly performance: number; readonly determinism: number; }; readonly estimatedInputLatencyMs: number; readonly estimatedFrameCostMs: number; readonly estimatedSettleMs: number; readonly estimatedGpuMemoryMb: number; readonly rightsProfile: "commercial-safe" | "copyleft-distribution" | "private-grant"; readonly resolvedTransport: Exclude<BrushStudioV6InputTransport, "auto">; }
export interface BrushStudioV6Recipe { readonly id: string; readonly label: string; readonly group: string; readonly description: string; readonly create: () => BrushStudioV6Program; }

const GOALS: readonly BrushStudioV6QualityGoal[] = ["responsive", "balanced", "material", "cinematic"];
const DEVICES: readonly BrushStudioV6DeviceProfile[] = ["desktop-pen", "tablet-pen", "touch-hybrid", "mouse"];
const TOUCH: readonly BrushStudioV6TouchPolicy[] = ["pen-only", "pen-draw-finger-pan", "pen-draw-two-finger-gesture", "pen-ink-finger-water", "touch-draw"];
const TRANSPORTS: readonly BrushStudioV6InputTransport[] = ["auto", "raw-coalesced", "move-coalesced", "move-basic"];
const FILMS: readonly BrushStudioV6FilmProfile[] = ["glass", "matte", "paperlike-fine", "paperlike-rough"];
const SINGLE: readonly Exclude<BrushStudioV6Slot, "physics" | "finish">[] = ["input", "motion", "carrier", "tip", "surface", "deposition", "pickup", "pigment", "pattern", "output"];
function obj(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function clamp(value: unknown, min: number, max: number, fallback: number): number { return typeof value === "number" && Number.isFinite(value) ? Math.min(max, Math.max(min, value)) : fallback; }
function int(value: unknown, min: number, max: number, fallback: number): number { return Math.round(clamp(value, min, max, fallback)); }
function pick<T extends string>(values: readonly T[], value: unknown, fallback: T): T { return typeof value === "string" && (values as readonly string[]).includes(value) ? value as T : fallback; }
function text(value: unknown, fallback: string): string { return typeof value === "string" && value.trim() ? value.slice(0, 240) : fallback; }
function nodeFor(id: string): BrushStudioV6NodeDescriptor { return NODE_BY_ID.get(id) ?? BRUSH_STUDIO_V6_NODES[0]!; }
function validNode(value: unknown, slot: BrushStudioV6Slot, fallback: string): string { return typeof value === "string" && NODE_BY_ID.get(value)?.slot === slot ? value : fallback; }
function multi(value: unknown, slot: BrushStudioV6Slot): readonly string[] { return Object.freeze(Array.from(new Set(Array.isArray(value) ? value.filter((id): id is string => typeof id === "string" && NODE_BY_ID.get(id)?.slot === slot) : []))); }
function inputDefaults(): BrushStudioV6InputPolicy { return Object.freeze({ transport: "auto", predictionPreviewOnly: true, touchPolicy: "pen-draw-two-finger-gesture", palmRejection: true, hoverPreview: true, pressureOnset: 0.02, pressureSaturation: 0.94, pressureGamma: 0.82, pressureHysteresis: 0.02, tiltEnabled: true, tiltDeadZoneDeg: 2, tiltSmoothing: 0.18, twistSmoothing: 0.22, film: "glass", audioFeedback: false, hapticFeedback: false }); }
function tuningDefaults(): BrushStudioV6Tuning { return Object.freeze({ size: 18, opacity: 0.95, flow: 0.8, spacing: 0.14, stabilization: 0.18, surfaceTooth: 0.18, friction: 0.18, absorbency: 0.05, granulation: 0, edgeDarkening: 0, pickup: 0, reservoir: 0.4, wetness: 0, diffusion: 0.15, advection: 0.25, evaporation: 0.35, viscosity: 0.45, plasticity: 0.25, gravity: 0.25, bristleStrands: 48, bristleIterations: 4, particleCount: 640, reactionRate: 0.35, patternDensity: 0.55, patternScale: 1, patternJitter: 0.2, relief: 0, gloss: 0.2, primaryColor: "#111827", secondaryColor: "#2563eb" }); }
function proofDefaults(): BrushStudioV6Proofs { return Object.freeze({ mixboxDistinctiveness: Object.freeze({ verified: false, spectralReproductionFailed: false, blindPreference: 0, blindDistinguishability: 0, meanPathDeltaE: 0 }), deterministicPatternSeed: true, rasterReceipt: true }); }
function baseProgram(): BrushStudioV6Program { return Object.freeze({ schemaVersion: 6, id: "clean-ink", name: "클린 잉크", description: "낮은 지연과 매끈한 WebGPU 잉크", qualityGoal: "balanced", deviceProfile: "desktop-pen", seed: 20260909, input: inputDefaults(), slots: Object.freeze({ input: "input-pointer-v3", motion: "motion-adaptive-ema", carrier: "carrier-webgpu-centerline", tip: "tip-round-sdf", surface: "surface-smooth", deposition: "deposit-ink", pickup: "pickup-none", pigment: "pigment-rgb", physics: Object.freeze([]), pattern: "pattern-none", finish: Object.freeze([]), output: "output-hybrid" }), tuning: tuningDefaults(), proofs: proofDefaults() }); }
type Patch = Partial<Omit<BrushStudioV6Program, "schemaVersion" | "input" | "slots" | "tuning" | "proofs">> & { readonly input?: Partial<BrushStudioV6InputPolicy>; readonly slots?: Partial<BrushStudioV6Slots>; readonly tuning?: Partial<BrushStudioV6Tuning>; readonly proofs?: Partial<BrushStudioV6Proofs> & { readonly mixboxDistinctiveness?: Partial<BrushStudioV6Proofs["mixboxDistinctiveness"]> }; };
function patch(program: BrushStudioV6Program, delta: Patch): BrushStudioV6Program { return Object.freeze({ ...program, ...delta, schemaVersion: 6, input: Object.freeze({ ...program.input, ...delta.input }), slots: Object.freeze({ ...program.slots, ...delta.slots, physics: Object.freeze([...(delta.slots?.physics ?? program.slots.physics)]), finish: Object.freeze([...(delta.slots?.finish ?? program.slots.finish)]) }), tuning: Object.freeze({ ...program.tuning, ...delta.tuning }), proofs: Object.freeze({ ...program.proofs, ...delta.proofs, mixboxDistinctiveness: Object.freeze({ ...program.proofs.mixboxDistinctiveness, ...delta.proofs?.mixboxDistinctiveness }) }) }); }
function recipe(id: string, label: string, group: string, description: string, delta: Patch): BrushStudioV6Recipe { return Object.freeze({ id, label, group, description, create: () => patch(baseProgram(), { id, name: label, description, ...delta }) }); }

export const BRUSH_STUDIO_V6_RECIPES: readonly BrushStudioV6Recipe[] = Object.freeze([
  recipe("clean-ink", "클린 잉크", "선화", "낮은 지연과 매끈한 WebGPU 잉크", {}),
  recipe("manga-gpen", "만화 G펜", "선화", "강한 필압 테이퍼와 벡터 외곽선", { slots: { carrier: "carrier-perfect-outline", output: "output-vector" }, tuning: { size: 12, stabilization: 0.24 } }),
  recipe("natural-calligraphy", "자연 캘리그래피", "선화", "치즐 접촉과 자연 잉크량 변화", { slots: { motion: "motion-spring", carrier: "carrier-libmypaint-dabs", tip: "tip-chisel-sdf", surface: "surface-kent", pigment: "pigment-spectral", output: "output-raster-tiles" }, tuning: { size: 26, flow: 0.72, friction: 0.28 } }),
  recipe("velvet-graphite", "벨벳 그래파이트", "건식", "실물 grain과 종이 접촉을 결합한 흑연", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-grain-exemplar", surface: "surface-printmaking", deposition: "deposit-dry", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-raster-tiles" }, tuning: { size: 14, surfaceTooth: 0.78, friction: 0.62, granulation: 0.7 } }),
  recipe("eroding-charcoal", "침식 목탄", "건식", "촉 마모와 가루·스머지가 남는 목탄", { slots: { carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-raster-tiles" }, tuning: { size: 28, surfaceTooth: 0.88, pickup: 0.28, granulation: 0.82 } }),
  recipe("alcohol-bloom", "알코올 블룸 마커", "마커", "용제 확산과 아래색 픽업을 가진 마커", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-chisel-sdf", surface: "surface-kent", deposition: "deposit-marker", pickup: "pickup-krita-smudge", pigment: "pigment-spectral", physics: ["physics-porous-paper"], finish: ["finish-edge-bloom"], output: "output-raster-tiles" }, tuning: { size: 32, absorbency: 0.35, wetness: 0.34, pickup: 0.4, edgeDarkening: 0.32 } }),
  recipe("mineral-bloom", "미네랄 블룸 워시", "습식", "K/S 광물 안료가 수채지 골에 과립 침전", { slots: { motion: "motion-brush-inertia", carrier: "carrier-webgpu-ribbon", surface: "surface-coldpress", deposition: "deposit-wet", pigment: "pigment-open-km", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom", "finish-wet-sheen"], output: "output-raster-tiles" }, tuning: { size: 48, wetness: 0.82, absorbency: 0.72, granulation: 0.82, edgeDarkening: 0.74, diffusion: 0.72 } }),
  recipe("chroma-sumi", "크로마 수묵", "습식", "짙은 먹 중심과 청보라색 섬유 후광", { slots: { carrier: "carrier-hokusai-dabs", surface: "surface-porous", deposition: "deposit-wet", pigment: "pigment-inkwash-density", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-chroma", "finish-edge-bloom"], output: "output-raster-tiles" }, tuning: { size: 30, wetness: 0.68, absorbency: 0.8, edgeDarkening: 0.66, primaryColor: "#111827", secondaryColor: "#4338ca" } }),
  recipe("wax-resist", "왁스 리지스트 수채", "습식", "왁스 마스크를 피해 흐르는 수채", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pigment: "pigment-spectral", physics: ["physics-dry-contact", "physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-raster-tiles" }, tuning: { size: 42, wetness: 0.7, surfaceTooth: 0.72, granulation: 0.48 } }),
  recipe("oil-hair-mixer", "오일 헤어 믹서", "페인트", "개별 강모 reservoir와 K/S 안료를 가진 유화", { slots: { motion: "motion-brush-inertia", carrier: "carrier-krita-hairy", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-open-km", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-raster-tiles" }, tuning: { size: 54, pickup: 0.62, reservoir: 0.78, viscosity: 0.78, plasticity: 0.64, bristleStrands: 96, relief: 0.66, gloss: 0.55 } }),
  recipe("impasto-knife", "임파스토 나이프", "페인트", "높이와 스크레이프가 남는 팔레트 나이프", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-ribbon", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-open-km", physics: ["physics-height"], finish: ["finish-relief"], output: "output-raster-tiles" }, tuning: { size: 72, viscosity: 0.92, plasticity: 0.88, relief: 0.92, gloss: 0.65 } }),
  recipe("dripping-neon", "드리핑 네온 잉크", "FX", "젖은 발광 잉크가 중력으로 흐르는 효과", { slots: { deposition: "deposit-light", physics: ["physics-inkwash", "physics-thin-film"], finish: ["finish-neon", "finish-wet-sheen"], output: "output-raster-tiles" }, tuning: { size: 22, wetness: 0.72, gravity: 0.82, viscosity: 0.22, primaryColor: "#06b6d4", secondaryColor: "#d946ef" } }),
  recipe("dendritic-copper", "덴드라이트 코퍼", "FX", "구리 안료의 가지형 반응 성장", { slots: { carrier: "carrier-webgpu-particles", tip: "tip-grain-exemplar", surface: "surface-porous", deposition: "deposit-particles", pigment: "pigment-open-km", physics: ["physics-porous-paper", "physics-reaction"], finish: ["finish-wet-sheen"], output: "output-raster-tiles" }, tuning: { size: 24, reactionRate: 0.82, absorbency: 0.55, primaryColor: "#b45309", secondaryColor: "#0f766e" } }),
  recipe("holographic-stitch", "홀로그래픽 스티치", "패턴", "트위스트와 색 순환을 가진 연결 문양", { slots: { tip: "tip-motif-atlas", deposition: "deposit-light", pattern: "pattern-stitch", finish: ["finish-neon"], output: "output-hybrid" }, tuning: { size: 16, patternDensity: 0.78, patternScale: 0.72, patternJitter: 0.05, primaryColor: "#0ea5e9", secondaryColor: "#ec4899" } }),
  recipe("moss-flow", "모스 플로우", "패턴", "플로우필드 위에서 성장하는 이끼 군집", { slots: { carrier: "carrier-p5-flow", tip: "tip-motif-atlas", surface: "surface-porous", deposition: "deposit-wet", pigment: "pigment-spectral", physics: ["physics-porous-paper"], pattern: "pattern-foliage", finish: ["finish-grain"], output: "output-raster-tiles" }, tuning: { size: 20, patternDensity: 0.9, patternScale: 0.7, patternJitter: 0.72, absorbency: 0.52, primaryColor: "#365314", secondaryColor: "#65a30d" } }),
  recipe("document-halftone", "문서 고정 하프톤", "만화", "확대·이동에도 위상이 고정되는 망점", { slots: { motion: "motion-direct", pattern: "pattern-dot-tone" }, tuning: { size: 44, patternDensity: 0.62, patternScale: 0.82 } }),
  recipe("kaleido-swarm", "칼레이도 스웜", "프로시저럴", "반사·회전 대칭과 입자 군집을 결합", { slots: { carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", deposition: "deposit-particles", physics: ["physics-particles"], pattern: "pattern-kaleido", finish: ["finish-neon"], output: "output-raster-tiles" }, tuning: { size: 18, particleCount: 1100, patternDensity: 0.8, patternJitter: 0.5, primaryColor: "#7c3aed", secondaryColor: "#22d3ee" } }),
]);

export function brushStudioV6NodesForSlot(slot: BrushStudioV6Slot): readonly BrushStudioV6NodeDescriptor[] { return BRUSH_STUDIO_V6_NODES.filter((entry) => entry.slot === slot); }
export function brushStudioV6Node(id: string): BrushStudioV6NodeDescriptor { return nodeFor(id); }
export function createBrushStudioV6Program(recipeId = "clean-ink"): BrushStudioV6Program { return (BRUSH_STUDIO_V6_RECIPES.find((entry) => entry.id === recipeId) ?? BRUSH_STUDIO_V6_RECIPES[0]!).create(); }

export function normalizeBrushStudioV6Program(value: unknown): BrushStudioV6Program {
  const source = obj(value); if (source.schemaVersion !== 6) return createBrushStudioV6Program();
  const fallback = createBrushStudioV6Program(); const input = obj(source.input); const slots = obj(source.slots); const tuning = obj(source.tuning); const proofs = obj(source.proofs); const mixbox = obj(proofs.mixboxDistinctiveness);
  const normalizedSlots = { ...fallback.slots } as Record<string, string | readonly string[]>; for (const slot of SINGLE) normalizedSlots[slot] = validNode(slots[slot], slot, fallback.slots[slot] as string);
  const hex = (candidate: unknown, defaultValue: string) => typeof candidate === "string" && /^#[0-9a-f]{6}$/iu.test(candidate) ? candidate : defaultValue;
  const numberFields: Readonly<Record<Exclude<keyof BrushStudioV6Tuning, "primaryColor" | "secondaryColor" | "bristleStrands" | "bristleIterations" | "particleCount">, readonly [number, number]>> = { size: [1, 240], opacity: [0.01, 1], flow: [0.01, 1], spacing: [0.01, 4], stabilization: [0, 1], surfaceTooth: [0, 1], friction: [0, 1], absorbency: [0, 1], granulation: [0, 1], edgeDarkening: [0, 1], pickup: [0, 1], reservoir: [0, 1], wetness: [0, 1], diffusion: [0, 1], advection: [0, 1], evaporation: [0, 1], viscosity: [0, 1], plasticity: [0, 1], gravity: [-1, 1], reactionRate: [0, 1], patternDensity: [0, 1], patternScale: [0.1, 4], patternJitter: [0, 1], relief: [0, 1], gloss: [0, 1] };
  const normalizedTuning = { ...fallback.tuning } as Record<string, number | string>; for (const [key, range] of Object.entries(numberFields)) normalizedTuning[key] = clamp(tuning[key], range[0], range[1], fallback.tuning[key as keyof typeof numberFields]);
  normalizedTuning.bristleStrands = int(tuning.bristleStrands, 8, 256, fallback.tuning.bristleStrands); normalizedTuning.bristleIterations = int(tuning.bristleIterations, 1, 12, fallback.tuning.bristleIterations); normalizedTuning.particleCount = int(tuning.particleCount, 16, 4096, fallback.tuning.particleCount); normalizedTuning.primaryColor = hex(tuning.primaryColor, fallback.tuning.primaryColor); normalizedTuning.secondaryColor = hex(tuning.secondaryColor, fallback.tuning.secondaryColor);
  return Object.freeze({ schemaVersion: 6, id: text(source.id, fallback.id), name: text(source.name, fallback.name), description: text(source.description, fallback.description), qualityGoal: pick(GOALS, source.qualityGoal, fallback.qualityGoal), deviceProfile: pick(DEVICES, source.deviceProfile, fallback.deviceProfile), seed: int(source.seed, 1, 2147483647, fallback.seed), input: Object.freeze({ transport: pick(TRANSPORTS, input.transport, fallback.input.transport), predictionPreviewOnly: input.predictionPreviewOnly === undefined ? true : Boolean(input.predictionPreviewOnly), touchPolicy: pick(TOUCH, input.touchPolicy, fallback.input.touchPolicy), palmRejection: input.palmRejection === undefined ? true : Boolean(input.palmRejection), hoverPreview: input.hoverPreview === undefined ? true : Boolean(input.hoverPreview), pressureOnset: clamp(input.pressureOnset, 0, 0.4, fallback.input.pressureOnset), pressureSaturation: clamp(input.pressureSaturation, 0.5, 1, fallback.input.pressureSaturation), pressureGamma: clamp(input.pressureGamma, 0.2, 3, fallback.input.pressureGamma), pressureHysteresis: clamp(input.pressureHysteresis, 0, 0.2, fallback.input.pressureHysteresis), tiltEnabled: input.tiltEnabled === undefined ? true : Boolean(input.tiltEnabled), tiltDeadZoneDeg: clamp(input.tiltDeadZoneDeg, 0, 20, fallback.input.tiltDeadZoneDeg), tiltSmoothing: clamp(input.tiltSmoothing, 0, 1, fallback.input.tiltSmoothing), twistSmoothing: clamp(input.twistSmoothing, 0, 1, fallback.input.twistSmoothing), film: pick(FILMS, input.film, fallback.input.film), audioFeedback: Boolean(input.audioFeedback), hapticFeedback: Boolean(input.hapticFeedback) }), slots: Object.freeze({ ...(normalizedSlots as unknown as BrushStudioV6Slots), physics: multi(slots.physics, "physics"), finish: multi(slots.finish, "finish") }), tuning: Object.freeze(normalizedTuning as unknown as BrushStudioV6Tuning), proofs: Object.freeze({ mixboxDistinctiveness: Object.freeze({ verified: Boolean(mixbox.verified), spectralReproductionFailed: Boolean(mixbox.spectralReproductionFailed), blindPreference: clamp(mixbox.blindPreference, 0, 1, 0), blindDistinguishability: clamp(mixbox.blindDistinguishability, 0, 1, 0), meanPathDeltaE: clamp(mixbox.meanPathDeltaE, 0, 100, 0) }), deterministicPatternSeed: proofs.deterministicPatternSeed === undefined ? true : Boolean(proofs.deterministicPatternSeed), rasterReceipt: proofs.rasterReceipt === undefined ? true : Boolean(proofs.rasterReceipt) }) });
}

export function detectBrushStudioV6Capabilities(): BrushStudioV6Capabilities {
  const nav = typeof navigator === "undefined" ? undefined : navigator as Navigator & { gpu?: unknown }; const win = typeof window === "undefined" ? undefined : window; const proto = typeof PointerEvent === "undefined" ? undefined : PointerEvent.prototype as PointerEvent & { getCoalescedEvents?: unknown; getPredictedEvents?: unknown };
  return Object.freeze({ webgpu: Boolean(nav?.gpu), wasm: typeof WebAssembly !== "undefined", webgl2: typeof document !== "undefined" && Boolean(document.createElement("canvas").getContext("webgl2")), sharedArrayBuffer: typeof SharedArrayBuffer !== "undefined" && Boolean(globalThis.crossOriginIsolated), pointerRawUpdate: Boolean(win && "onpointerrawupdate" in win), coalescedEvents: typeof proto?.getCoalescedEvents === "function", predictedEvents: typeof proto?.getPredictedEvents === "function", pressure: typeof PointerEvent !== "undefined", tilt: Boolean(proto && "tiltX" in proto), twist: Boolean(proto && "twist" in proto), hover: typeof matchMedia === "function" && matchMedia("(hover: hover)").matches, maxTextureDimension2D: 8192, memoryBudgetMb: 512 });
}
export const BRUSH_STUDIO_V6_FULL_CAPABILITIES: BrushStudioV6Capabilities = Object.freeze({ webgpu: true, wasm: true, webgl2: true, sharedArrayBuffer: true, pointerRawUpdate: true, coalescedEvents: true, predictedEvents: true, pressure: true, tilt: true, twist: true, hover: true, maxTextureDimension2D: 16384, memoryBudgetMb: 2048 });
function active(program: BrushStudioV6Program): readonly BrushStudioV6NodeDescriptor[] { return Object.freeze([program.slots.input, program.slots.motion, program.slots.carrier, program.slots.tip, program.slots.surface, program.slots.deposition, program.slots.pickup, program.slots.pigment, ...program.slots.physics, program.slots.pattern, ...program.slots.finish, program.slots.output].map(nodeFor)); }
function capability(c: BrushStudioV6Capabilities, id: BrushStudioV6Capability): boolean { return ({ webgpu: c.webgpu, wasm: c.wasm, webgl2: c.webgl2, "shared-array-buffer": c.sharedArrayBuffer, pointerrawupdate: c.pointerRawUpdate, "coalesced-events": c.coalescedEvents, "predicted-events": c.predictedEvents, pressure: c.pressure, tilt: c.tilt, twist: c.twist, hover: c.hover })[id]; }
function transport(program: BrushStudioV6Program, c: BrushStudioV6Capabilities): Exclude<BrushStudioV6InputTransport, "auto"> {
  if (program.input.transport === "move-basic") return "move-basic";
  if (program.input.transport !== "move-coalesced" && c.pointerRawUpdate && c.coalescedEvents) return "raw-coalesced";
  return c.coalescedEvents ? "move-coalesced" : "move-basic";
}
function issue(id: string, severity: BrushStudioV6IssueSeverity, title: string, detail: string, fix?: string): BrushStudioV6Issue { return Object.freeze({ id, severity, title, detail, ...(fix ? { fix } : {}) }); }
const PHASES: readonly BrushStudioV6Phase[] = ["hover", "preview", "live", "settle", "commit", "export"];
function passes(nodes: readonly BrushStudioV6NodeDescriptor[]): readonly BrushStudioV6ExecutionPass[] {
  const result: BrushStudioV6ExecutionPass[] = [{ id: "hover-main", phase: "hover", domain: "main", label: "호버 촉·접촉면", nodeIds: [], canonical: false, budgetMs: 0.25 }];
  for (const entry of [...nodes].sort((a, b) => PHASES.indexOf(a.phase) - PHASES.indexOf(b.phase))) { const last = result[result.length - 1]; if (last?.phase === entry.phase && last.domain === entry.domain && entry.domain === "webgpu") result[result.length - 1] = { ...last, label: `${last.label} + ${entry.label}`, nodeIds: [...last.nodeIds, entry.id], budgetMs: Number((last.budgetMs + Math.max(0.15, (100 - entry.latency) / 45)).toFixed(2)) }; else result.push({ id: `${entry.phase}-${entry.domain}-${result.length}`, phase: entry.phase, domain: entry.domain, label: entry.label, nodeIds: [entry.id], canonical: entry.phase !== "preview", budgetMs: Number(Math.max(0.2, (100 - entry.latency) / 35).toFixed(2)) }); }
  result.push({ id: "export-webgpu", phase: "export", domain: "webgpu", label: "고품질 타일 재평가·출력", nodeIds: [], canonical: true, budgetMs: 6 }); return Object.freeze(result.map((entry) => Object.freeze({ ...entry, nodeIds: Object.freeze([...entry.nodeIds]) })));
}
function resources(program: BrushStudioV6Program): readonly BrushStudioV6Resource[] { const p = new Set(program.slots.physics); const result: BrushStudioV6Resource[] = [{ id: "coverage", format: "r16float", scale: 1, owner: "deposition", estimatedMb: 8 }, { id: "paper", format: "rgba8unorm", scale: 1, owner: "surface", estimatedMb: 16 }, { id: "color", format: "rgba16float", scale: 1, owner: "pigment", estimatedMb: 32 }]; if (p.has("physics-inkwash")) result.push({ id: "mobile-pigment", format: "rgba16float", scale: 1, owner: "wet", estimatedMb: 32 }, { id: "fixed-pigment", format: "rgba16float", scale: 1, owner: "wet", estimatedMb: 32 }, { id: "wetness", format: "r16float", scale: 1, owner: "wet", estimatedMb: 8 }, { id: "velocity", format: "rg16float", scale: 0.5, owner: "wet", estimatedMb: 4 }, { id: "pressure", format: "r16float", scale: 0.5, owner: "wet", estimatedMb: 2 }); if (p.has("physics-height")) result.push({ id: "height", format: "r16float", scale: 1, owner: "height", estimatedMb: 8 }, { id: "normal", format: "rg16snorm", scale: 1, owner: "height", estimatedMb: 16 }); if (p.has("physics-bristle")) result.push({ id: "bristle-state", format: "storage-buffer", scale: 1, owner: "bristle", estimatedMb: 6 }); if (p.has("physics-reaction")) result.push({ id: "reaction-a", format: "r16float", scale: 0.5, owner: "reaction", estimatedMb: 2 }, { id: "reaction-b", format: "r16float", scale: 0.5, owner: "reaction", estimatedMb: 2 }); if (p.has("physics-particles")) result.push({ id: "particles", format: "storage-buffer", scale: 1, owner: "particle", estimatedMb: 12 }); return Object.freeze(result.map((entry): BrushStudioV6Resource => Object.freeze({ ...entry }))); }

export function analyzeBrushStudioV6Program(input: BrushStudioV6Program, c: BrushStudioV6Capabilities = detectBrushStudioV6Capabilities()): BrushStudioV6Analysis {
  const program = normalizeBrushStudioV6Program(input); const nodes = active(program); const p = new Set(program.slots.physics); const issues: BrushStudioV6Issue[] = [];
  for (const node of nodes) for (const requirement of node.requires) if (!capability(c, requirement)) issues.push(issue(`capability-${node.id}-${requirement}`, "error", `${node.label} 실행 불가`, `${requirement} 기능이 현재 브라우저에 없습니다.`));
  if (program.input.pressureSaturation - program.input.pressureOnset < 0.4) issues.push(issue("pressure-range", "error", "필압 유효 범위가 좁음", "장치 보정 후 사용할 수 있는 필압 구간이 부족합니다."));
  if (!program.input.predictionPreviewOnly) issues.push(issue("prediction-authority", "error", "예측 입력이 canonical 상태를 변경함", "예측 샘플은 수분·안료·히스토리를 바꾸면 안 됩니다."));
  if (program.input.touchPolicy === "pen-ink-finger-water" && !p.has("physics-inkwash")) issues.push(issue("finger-water", "error", "손가락 물붓의 습식 authority 누락", "Inkwash를 추가하세요."));
  if (program.slots.pigment === "pigment-inkwash-density" && !p.has("physics-inkwash")) issues.push(issue("inkwash-density", "error", "광학 밀도에 습식 필드가 없음", "Inkwash를 추가하세요."));
  if (p.has("physics-thin-film") && !(p.has("physics-inkwash") || p.has("physics-height"))) issues.push(issue("thin-film-source", "error", "Thin-film 입력 필드가 없음", "Inkwash 또는 Height Field를 추가하세요."));
  if (program.slots.carrier === "carrier-krita-hairy" && !p.has("physics-bristle")) issues.push(issue("hairy-without-bristle", "error", "Krita Hairy에 강모 역학이 없음", "Bristle Dynamics를 추가하세요."));
  if ((program.slots.tip === "tip-pigment-normal" || program.slots.finish.includes("finish-relief")) && !p.has("physics-height")) issues.push(issue("relief-without-height", "error", "릴리프 높이가 없음", "Height Field를 추가하세요."));
  if (program.slots.finish.some((id) => ["finish-edge-bloom", "finish-wet-sheen", "finish-chroma"].includes(id)) && !(p.has("physics-inkwash") || p.has("physics-porous-paper") || p.has("physics-reaction"))) issues.push(issue("wet-finish-source", "error", "습식 마감 입력이 없음", "습식 물리를 연결하세요."));
  if (program.slots.output === "output-vector" && (program.slots.physics.length > 0 || program.slots.pickup !== "pickup-none")) issues.push(issue("vector-physical-output", "error", "물리 브러시는 순수 벡터 출력 불가", "Raster 또는 Hybrid를 선택하세요."));
  if (program.slots.pattern !== "pattern-none" && !program.proofs.deterministicPatternSeed) issues.push(issue("pattern-seed", "error", "패턴 시드가 비결정적", "결정적 시드를 활성화하세요."));
  if (program.slots.physics.length > 0 && !program.proofs.rasterReceipt) issues.push(issue("raster-receipt", "error", "물리 결과 영수증이 없음", "커밋 타일 영수증을 활성화하세요."));
  if (program.slots.pigment === "pigment-mixbox") { const proof = program.proofs.mixboxDistinctiveness; if (!(proof.verified && proof.spectralReproductionFailed && proof.blindPreference >= 0.65 && proof.blindDistinguishability >= 0.7 && proof.meanPathDeltaE >= 4)) issues.push(issue("mixbox-distinctiveness", "error", "Mixbox 대체 불가능성 미입증", "Spectral 실패·선호 65%·구별 70%·ΔE 4 이상이 필요합니다.")); }
  if (p.has("physics-inkwash") && p.has("physics-thin-film")) issues.push(issue("wet-coupling", "info", "Inkwash→Thin-film 결합", "질량 보존 어댑터를 사용합니다."));
  if (program.tuning.bristleStrands * program.tuning.bristleIterations > 768) issues.push(issue("bristle-cost", "warning", "강모 비용이 높음", "라이브 LOD를 낮추세요."));
  const allocated = resources(program); const chosenTransport = transport(program, c); const inputLatency = 2.4 + (chosenTransport === "move-basic" ? 5 : chosenTransport === "move-coalesced" ? 2 : 0.7) + program.tuning.stabilization * 2.5; const frameCost = 0.7 + nodes.reduce((sum, node) => sum + (100 - node.latency) / 70, 0) + (p.has("physics-bristle") ? program.tuning.bristleStrands * program.tuning.bristleIterations / 520 : 0) + (p.has("physics-particles") ? program.tuning.particleCount / 1250 : 0); const settle = 6 + (p.has("physics-inkwash") ? 72 : 0) + (p.has("physics-thin-film") ? 58 : 0) + (p.has("physics-reaction") ? 84 : 0) + (p.has("physics-height") ? 28 : 0); const memory = allocated.reduce((sum, entry) => sum + entry.estimatedMb, 0); const average = (key: "fidelity" | "uniqueness") => nodes.reduce((sum, node) => sum + node[key], 0) / Math.max(1, nodes.length); const score = (value: number) => Math.round(Math.max(0, Math.min(100, value))); const metrics = Object.freeze({ handFeel: score(102 - inputLatency * 3), materialFidelity: score(average("fidelity") + program.tuning.surfaceTooth * 4 + program.tuning.pickup * 4), colorFidelity: score(program.slots.pigment === "pigment-rgb" ? 68 : 94 + program.tuning.granulation * 5), temporalFidelity: score(55 + program.slots.physics.filter((id) => ["physics-inkwash", "physics-thin-film", "physics-reaction", "physics-height"].includes(id)).length * 11), uniqueness: score(average("uniqueness") + program.slots.physics.length * 2), performance: score(105 - frameCost * 6 - memory * 0.08), determinism: score(100 - (program.proofs.deterministicPatternSeed ? 0 : 24) - (program.proofs.rasterReceipt ? 0 : program.slots.physics.length * 8)) }); const rightsProfile = nodes.some((node) => node.rights === "private-grant") ? "private-grant" : nodes.some((node) => node.rights === "copyleft") ? "copyleft-distribution" : "commercial-safe";
  return Object.freeze({ valid: !issues.some((entry) => entry.severity === "error"), issues: Object.freeze(issues), nodes, passes: passes(nodes), resources: allocated, metrics, estimatedInputLatencyMs: Number(inputLatency.toFixed(1)), estimatedFrameCostMs: Number(frameCost.toFixed(1)), estimatedSettleMs: Math.round(settle), estimatedGpuMemoryMb: Number(memory.toFixed(1)), rightsProfile, resolvedTransport: chosenTransport });
}

export function optimizeBrushStudioV6Program(input: BrushStudioV6Program, capabilities: BrushStudioV6Capabilities = detectBrushStudioV6Capabilities()): BrushStudioV6Program { const program = normalizeBrushStudioV6Program(input); let next = patch(program, { input: { transport: transport(program, capabilities), tiltEnabled: program.input.tiltEnabled && capabilities.tilt, hoverPreview: program.input.hoverPreview && capabilities.hover } }); if (next.slots.pigment === "pigment-mixbox") { const proof = next.proofs.mixboxDistinctiveness; if (!(proof.verified && proof.spectralReproductionFailed && proof.blindPreference >= 0.65 && proof.blindDistinguishability >= 0.7 && proof.meanPathDeltaE >= 4)) next = patch(next, { slots: { pigment: "pigment-spectral" } }); } if (next.qualityGoal === "responsive") next = patch(next, { tuning: { bristleStrands: Math.min(48, next.tuning.bristleStrands), bristleIterations: Math.min(4, next.tuning.bristleIterations), particleCount: Math.min(768, next.tuning.particleCount), diffusion: Math.min(0.55, next.tuning.diffusion) } }); return normalizeBrushStudioV6Program(next); }
export function replaceBrushStudioV6Slot(program: BrushStudioV6Program, slot: Exclude<BrushStudioV6Slot, "input" | "physics" | "finish">, id: string): BrushStudioV6Program { return normalizeBrushStudioV6Program(patch(program, { slots: { [slot]: validNode(id, slot, program.slots[slot] as string) } })); }
export function toggleBrushStudioV6Node(program: BrushStudioV6Program, slot: "physics" | "finish", id: string): BrushStudioV6Program { if (nodeFor(id).slot !== slot) return program; const values = new Set(program.slots[slot]); if (values.has(id)) values.delete(id); else values.add(id); return normalizeBrushStudioV6Program(patch(program, { slots: { [slot]: [...values] } })); }
export function patchBrushStudioV6Tuning(program: BrushStudioV6Program, delta: Partial<BrushStudioV6Tuning>): BrushStudioV6Program { return normalizeBrushStudioV6Program(patch(program, { tuning: delta })); }
export function patchBrushStudioV6Input(program: BrushStudioV6Program, delta: Partial<BrushStudioV6InputPolicy>): BrushStudioV6Program { return normalizeBrushStudioV6Program(patch(program, { input: delta })); }
export function patchBrushStudioV6Proofs(program: BrushStudioV6Program, delta: Patch["proofs"]): BrushStudioV6Program { return normalizeBrushStudioV6Program(patch(program, { proofs: delta })); }
export function patchBrushStudioV6Metadata(program: BrushStudioV6Program, delta: Partial<Pick<BrushStudioV6Program, "name" | "description" | "qualityGoal" | "deviceProfile" | "seed">>): BrushStudioV6Program { return normalizeBrushStudioV6Program(patch(program, delta)); }
