import { defineBrushStudioV6RecipeSeed } from "./brush-studio-v6-recipe-types";

import type { BrushStudioV6RecipeSeed } from "./brush-studio-v6-recipe-types";

export const BRUSH_STUDIO_V6_MIXBOX_RECIPE_SEEDS: readonly BrushStudioV6RecipeSeed[] =
  Object.freeze([
  defineBrushStudioV6RecipeSeed("mixbox-oil-bristle", "Mixbox 강모 유화", "Mixbox 회화", "GPL 강모 어댑터와 reservoir, 높이 도포, Mixbox 안료를 결합한 유화", { slots: { motion: "motion-brush-inertia", carrier: "carrier-krita-hairy", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-mixbox", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 58, pickup: 0.68, reservoir: 0.84, viscosity: 0.82, plasticity: 0.7, bristleStrands: 104, relief: 0.72, gloss: 0.52, primaryColor: "#f2b632", secondaryColor: "#244ac7" } }),
  defineBrushStudioV6RecipeSeed("mixbox-watercolor-bloom", "Mixbox 수채 블룸", "Mixbox 회화", "Hokusai 호환 다브, 한지 결, 습식 확산과 Mixbox 안료를 결합한 수채", { slots: { motion: "motion-brush-inertia", carrier: "carrier-hokusai-dabs", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 46, opacity: 0.72, flow: 0.62, pickup: 0.34, wetness: 0.86, absorbency: 0.76, diffusion: 0.8, granulation: 0.7, edgeDarkening: 0.68, primaryColor: "#f4d03f", secondaryColor: "#2455d6" } }),
  defineBrushStudioV6RecipeSeed("mixbox-gouache-dual", "Mixbox 듀얼 과슈", "Mixbox 회화", "듀얼 팁과 조밀한 습식 도포로 불투명한 두 안료를 섞는 과슈", { slots: { carrier: "carrier-hokusai-dabs", tip: "tip-krita-dual", surface: "surface-kent", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 34, opacity: 0.96, flow: 0.88, pickup: 0.42, wetness: 0.36, absorbency: 0.3, diffusion: 0.24, granulation: 0.18, edgeDarkening: 0.24, primaryColor: "#ffca3a", secondaryColor: "#1982c4" } }),
  defineBrushStudioV6RecipeSeed("mixbox-pastel-smudge", "Mixbox 파스텔 스머지", "Mixbox 회화", "libmypaint 호환 다브, 듀얼 팁, 종이 이빨과 GPL 스머지 어댑터를 결합", { slots: { carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 30, opacity: 0.84, flow: 0.72, pickup: 0.5, surfaceTooth: 0.9, friction: 0.72, granulation: 0.86, primaryColor: "#f6bd60", secondaryColor: "#5e60ce" } }),
  defineBrushStudioV6RecipeSeed("mixbox-alcohol-marker", "Mixbox 듀얼 알코올 마커", "Mixbox 회화", "Krita 호환 듀얼 팁, 다공성 종이와 스머지 어댑터를 결합해 두 펠트 섬유 자국이 겹치는 마커", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-krita-dual", surface: "surface-kent", deposition: "deposit-marker", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 30, opacity: 0.72, flow: 0.68, pickup: 0.56, absorbency: 0.42, edgeDarkening: 0.42, primaryColor: "#ffb703", secondaryColor: "#3a86ff" } }),
  defineBrushStudioV6RecipeSeed("mixbox-palette-knife", "Mixbox 팔레트 나이프", "Mixbox 회화", "넓은 칼날 접촉과 높이 물감, reservoir 안료를 결합한 임파스토", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-ribbon", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-mixbox", physics: ["physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 78, opacity: 0.98, flow: 0.9, pickup: 0.58, reservoir: 0.9, viscosity: 0.94, plasticity: 0.9, relief: 0.96, gloss: 0.62, primaryColor: "#fcbf49", secondaryColor: "#2a6fbb" } }),
  defineBrushStudioV6RecipeSeed("mixbox-color-smudge", "Mixbox 듀얼 컬러 스머지", "Mixbox 회화", "libmypaint 접촉, Krita 호환 듀얼 팁과 젖은 경계 블룸으로 두 안료를 넓게 밀고 당기는 스머지", { slots: { motion: "motion-spring", carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 46, opacity: 0.82, flow: 0.58, pickup: 0.88, wetness: 0.72, diffusion: 0.58, absorbency: 0.46, granulation: 0.28, edgeDarkening: 0.34, primaryColor: "#ffd166", secondaryColor: "#4361ee" } }),
  defineBrushStudioV6RecipeSeed("mixbox-colored-pencil", "Mixbox 컬러 연필", "Mixbox 회화", "libmypaint 접촉, 듀얼 안료 팁과 종이 이빨을 결합한 컬러 연필", { slots: { motion: "motion-adaptive-ema", carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-kent", deposition: "deposit-dry", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 12, opacity: 0.82, flow: 0.64, pickup: 0.28, surfaceTooth: 0.76, friction: 0.66, granulation: 0.7, primaryColor: "#f4a261", secondaryColor: "#457b9d" } }),
  defineBrushStudioV6RecipeSeed("mixbox-charcoal-rake", "Mixbox 컬러 목탄 레이크", "Mixbox 회화", "갈퀴형 리본과 듀얼 팁으로 여러 색 목탄 가루를 긁어 쌓는 브러시", { slots: { motion: "motion-brush-inertia", carrier: "carrier-webgpu-ribbon", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 30, opacity: 0.8, flow: 0.68, pickup: 0.44, surfaceTooth: 0.92, friction: 0.82, granulation: 0.92, primaryColor: "#bc6c25", secondaryColor: "#264653" } }),
  defineBrushStudioV6RecipeSeed("mixbox-pigment-spray", "Mixbox 안료 스프레이", "Mixbox 입자", "GPU 입자와 모티프 팁, 거리별 Mixbox 색 변화를 결합한 안료 분사", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", surface: "surface-smooth", deposition: "deposit-particles", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-particles"], pattern: "pattern-rainbow", finish: [], output: "output-contact-canvas-svg" }, tuning: { size: 34, opacity: 0.74, flow: 0.7, particleCount: 1400, patternDensity: 0.82, patternScale: 0.72, patternJitter: 0.64, primaryColor: "#ffbe0b", secondaryColor: "#3a0ca3" } }),
  defineBrushStudioV6RecipeSeed("mixbox-wax-resist", "Mixbox 왁스 리지스트", "Mixbox 회화", "마른 접촉 저항과 다공성 종이를 통과해 번지는 두 안료 수채", { slots: { motion: "motion-brush-inertia", carrier: "carrier-hokusai-dabs", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-dry-contact", "physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 44, opacity: 0.76, flow: 0.58, surfaceTooth: 0.84, wetness: 0.78, absorbency: 0.68, diffusion: 0.66, granulation: 0.58, edgeDarkening: 0.55, primaryColor: "#ffd166", secondaryColor: "#118ab2" } }),
  defineBrushStudioV6RecipeSeed("mixbox-bristle-calligraphy", "Mixbox 강모 캘리그래피", "Mixbox 회화", "스프링 필기감, 강모 reservoir와 높이 도포를 결합한 두꺼운 회화형 캘리그래피", { slots: { motion: "motion-spring", carrier: "carrier-krita-hairy", tip: "tip-chisel-sdf", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-mixbox", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 46, opacity: 0.96, flow: 0.8, pickup: 0.64, reservoir: 0.82, viscosity: 0.76, plasticity: 0.6, bristleStrands: 88, relief: 0.62, primaryColor: "#e9c46a", secondaryColor: "#264653" } }),
  defineBrushStudioV6RecipeSeed("mixbox-foliage-stamp", "Mixbox 폴리지 스탬프", "Mixbox 입자", "모티프 팁과 입자 군집으로 두 색 잎과 꽃을 경로 주변에 생성", { slots: { motion: "motion-adaptive-ema", carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", surface: "surface-porous", deposition: "deposit-particles", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-particles"], pattern: "pattern-foliage", finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 22, opacity: 0.88, flow: 0.76, particleCount: 980, patternDensity: 0.86, patternScale: 0.78, patternJitter: 0.6, primaryColor: "#588157", secondaryColor: "#dda15e" } }),
  defineBrushStudioV6RecipeSeed("mixbox-neon-wet", "Mixbox 젖은 네온 스티치", "Mixbox FX", "발광 안료 코어와 얇은 막 드립 위에 이동 거리 고정 네온 스티치를 연결하는 습식 FX 브러시", { slots: { motion: "motion-spring", carrier: "carrier-webgpu-centerline", tip: "tip-round-sdf", surface: "surface-smooth", deposition: "deposit-light", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-inkwash", "physics-thin-film"], pattern: "pattern-stitch", finish: ["finish-neon", "finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 24, opacity: 0.86, flow: 0.7, wetness: 0.72, diffusion: 0.44, gravity: 0.82, viscosity: 0.2, patternDensity: 0.78, patternScale: 0.7, patternJitter: 0.22, primaryColor: "#00f5d4", secondaryColor: "#f15bb5" } }),
  defineBrushStudioV6RecipeSeed("mixbox-granulating-ink", "Mixbox 입상 컬러 먹", "Mixbox 회화", "Hokusai 접촉과 종이 섬유, 색 분리·젖은 광택을 함께 정착시키는 컬러 먹", { slots: { motion: "motion-brush-inertia", carrier: "carrier-hokusai-dabs", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom", "finish-wet-sheen", "finish-chroma"], output: "output-contact-canvas-svg" }, tuning: { size: 38, opacity: 0.72, flow: 0.58, pickup: 0.36, wetness: 0.9, absorbency: 0.82, diffusion: 0.84, granulation: 0.9, edgeDarkening: 0.7, primaryColor: "#e9c46a", secondaryColor: "#3a0ca3" } }),
  defineBrushStudioV6RecipeSeed("mixbox-water-brush", "Mixbox 워터 브러시", "Mixbox 회화", "Hokusai 호환 접촉과 순수한 수분 확산으로 아래 안료를 부드럽게 연결하는 물붓", { slots: { motion: "motion-brush-inertia", carrier: "carrier-hokusai-dabs", tip: "tip-round-sdf", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 52, opacity: 0.46, flow: 0.42, wetness: 0.96, absorbency: 0.82, diffusion: 0.92, granulation: 0.38, edgeDarkening: 0.42, primaryColor: "#f9c74f", secondaryColor: "#277da1" } }),
  defineBrushStudioV6RecipeSeed("mixbox-oil-pastel-film", "Mixbox 오일파스텔 필름", "Mixbox 회화", "libmypaint 호환 다브와 듀얼 팁으로 종이 골에 두꺼운 왁스 안료막을 쌓는 오일파스텔", { slots: { motion: "motion-adaptive-ema", carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 26, opacity: 0.94, flow: 0.86, pickup: 0.38, surfaceTooth: 0.82, friction: 0.78, granulation: 0.64, primaryColor: "#f8961e", secondaryColor: "#4361ee" } }),
  defineBrushStudioV6RecipeSeed("mixbox-crosshatch-color", "Mixbox 컬러 크로스해치", "Mixbox 패턴", "치즐 접촉과 문서 고정 교차 해칭을 사용해 두 안료의 명암과 색 변화를 동시에 쌓는 브러시", { slots: { motion: "motion-adaptive-ema", carrier: "carrier-webgpu-ribbon", tip: "tip-chisel-sdf", surface: "surface-kent", deposition: "deposit-dry", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], pattern: "pattern-cross-hatch", finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 18, opacity: 0.78, flow: 0.66, surfaceTooth: 0.62, friction: 0.58, granulation: 0.56, patternDensity: 0.72, patternScale: 0.68, patternJitter: 0.18, primaryColor: "#e76f51", secondaryColor: "#2a9d8f" } }),
  defineBrushStudioV6RecipeSeed("mixbox-reaction-bloom", "Mixbox 반응 블룸", "Mixbox FX", "GPU 입자 시드와 반응 확산을 결합해 두 안료가 가지형 가장자리로 성장하는 실험 회화 브러시", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-particles", tip: "tip-grain-exemplar", surface: "surface-porous", deposition: "deposit-particles", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-particles", "physics-reaction"], pattern: "pattern-none", finish: ["finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 30, opacity: 0.8, flow: 0.72, particleCount: 1280, reactionRate: 0.84, absorbency: 0.58, patternJitter: 0.56, primaryColor: "#f94144", secondaryColor: "#577590" } }),
  defineBrushStudioV6RecipeSeed("mixbox-linen-weave", "Mixbox 리넨 강모", "Mixbox 회화", "리넨 직조 접촉, 강모 저장량과 높이 필드를 결합해 거친 캔버스 능선을 남기는 브러시", { slots: { motion: "motion-brush-inertia", carrier: "carrier-webgpu-ribbon", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-mixbox", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 50, opacity: 0.96, flow: 0.82, pickup: 0.56, reservoir: 0.86, viscosity: 0.84, plasticity: 0.68, bristleStrands: 72, bristleIterations: 6, surfaceTooth: 0.74, relief: 0.7, gloss: 0.42, primaryColor: "#f3722c", secondaryColor: "#277da1" } }),
  defineBrushStudioV6RecipeSeed("mixbox-glaze-marker", "Mixbox 투명 글레이즈", "Mixbox 회화", "얇은 치즐 마커층을 반복해 투명한 안료막과 중간색을 만드는 저비용 글레이즈 브러시", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-ribbon", tip: "tip-chisel-sdf", surface: "surface-smooth", deposition: "deposit-marker", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: [], pattern: "pattern-none", finish: [], output: "output-contact-canvas-svg" }, tuning: { size: 36, opacity: 0.42, flow: 0.48, pickup: 0.34, edgeDarkening: 0.16, primaryColor: "#f9c74f", secondaryColor: "#4d908e" } }),
  defineBrushStudioV6RecipeSeed("mixbox-phyllotaxis-stipple", "Mixbox 잎차례 점묘", "Mixbox 패턴", "균등한 잎차례 점 배치와 종이 이빨을 사용해 두 안료를 촘촘한 점묘로 혼합", { slots: { motion: "motion-direct", carrier: "carrier-cpu-phyllotaxis-stipple-v1", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-dry", pickup: "pickup-none", pigment: "pigment-mixbox", physics: [], pattern: "pattern-none", finish: [], output: "output-contact-canvas-svg" }, tuning: { size: 24, opacity: 0.84, flow: 0.72, surfaceTooth: 0.72, granulation: 0.7, particleCount: 1536, patternDensity: 0.8, patternScale: 0.72, patternJitter: 0.5, primaryColor: "#f9844a", secondaryColor: "#43aa8b" } }),
  defineBrushStudioV6RecipeSeed("mixbox-braided-paint", "Mixbox 브레이드 페인트", "Mixbox 장식", "세 가닥 토폴로지와 듀얼 팁을 사용해 서로 다른 안료가 교차하는 장식용 페인트 끈", { slots: { motion: "motion-direct", carrier: "carrier-cpu-braided-cord-v1", tip: "tip-krita-dual", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: [], pattern: "pattern-none", finish: [], output: "output-contact-canvas-svg" }, tuning: { size: 34, opacity: 0.96, flow: 0.82, pickup: 0.46, plasticity: 0.68, relief: 0.56, patternScale: 0.82, patternJitter: 0.36, primaryColor: "#f6bd60", secondaryColor: "#5e60ce" } }),
  ]);
