import { defineBrushStudioV6RecipeSeed } from "./brush-studio-v6-recipe-types";

import type { BrushStudioV6RecipeSeed } from "./brush-studio-v6-recipe-types";

export const BRUSH_STUDIO_V6_CORE_RECIPE_SEEDS: readonly BrushStudioV6RecipeSeed[] =
  Object.freeze([
  defineBrushStudioV6RecipeSeed("clean-ink", "클린 잉크", "선화", "낮은 지연과 매끈한 WebGPU 잉크", {}),
  defineBrushStudioV6RecipeSeed("manga-gpen", "만화 G펜", "선화", "강한 필압 테이퍼와 벡터 외곽선", { slots: { carrier: "carrier-perfect-outline", output: "output-contact-canvas-svg" }, tuning: { size: 12, stabilization: 0.24 } }),
  defineBrushStudioV6RecipeSeed("natural-calligraphy", "자연 캘리그래피", "선화", "치즐 접촉과 자연 잉크량 변화", { slots: { motion: "motion-spring", carrier: "carrier-libmypaint-dabs", tip: "tip-chisel-sdf", surface: "surface-kent", pigment: "pigment-spectral", output: "output-contact-canvas-svg" }, tuning: { size: 26, flow: 0.72, friction: 0.28 } }),
  defineBrushStudioV6RecipeSeed("velvet-graphite", "벨벳 그래파이트", "건식", "실물 grain과 종이 접촉을 결합한 흑연", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-grain-exemplar", surface: "surface-printmaking", deposition: "deposit-dry", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 14, surfaceTooth: 0.78, friction: 0.62, granulation: 0.7 } }),
  defineBrushStudioV6RecipeSeed("eroding-charcoal", "침식 목탄", "건식", "촉 마모와 가루·스머지가 남는 목탄", { slots: { carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 28, surfaceTooth: 0.88, pickup: 0.28, granulation: 0.82 } }),
  defineBrushStudioV6RecipeSeed("alcohol-bloom", "알코올 블룸 마커", "마커", "용제 확산과 아래색 픽업을 가진 마커", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-chisel-sdf", surface: "surface-kent", deposition: "deposit-marker", pickup: "pickup-krita-smudge", pigment: "pigment-spectral", physics: ["physics-porous-paper"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 32, absorbency: 0.35, wetness: 0.34, pickup: 0.4, edgeDarkening: 0.32 } }),
  defineBrushStudioV6RecipeSeed("mineral-bloom", "미네랄 블룸 워시", "습식", "K/S 광물 안료가 수채지 골에 과립 침전", { slots: { motion: "motion-brush-inertia", carrier: "carrier-webgpu-ribbon", surface: "surface-coldpress", deposition: "deposit-wet", pigment: "pigment-open-km", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom", "finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 48, wetness: 0.82, absorbency: 0.72, granulation: 0.82, edgeDarkening: 0.74, diffusion: 0.72 } }),
  defineBrushStudioV6RecipeSeed("chroma-sumi", "크로마 수묵", "습식", "짙은 먹 중심과 청보라색 섬유 후광", { slots: { carrier: "carrier-hokusai-dabs", surface: "surface-porous", deposition: "deposit-wet", pigment: "pigment-inkwash-density", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-chroma", "finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 30, wetness: 0.68, absorbency: 0.8, edgeDarkening: 0.66, primaryColor: "#111827", secondaryColor: "#4338ca" } }),
  defineBrushStudioV6RecipeSeed("wax-resist", "왁스 리지스트 수채", "습식", "왁스 마스크를 피해 흐르는 수채", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pigment: "pigment-spectral", physics: ["physics-dry-contact", "physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 42, wetness: 0.7, surfaceTooth: 0.72, granulation: 0.48 } }),
  defineBrushStudioV6RecipeSeed("oil-hair-mixer", "오일 헤어 믹서", "페인트", "개별 강모 reservoir와 K/S 안료를 가진 유화", { slots: { motion: "motion-brush-inertia", carrier: "carrier-krita-hairy", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-open-km", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 54, pickup: 0.62, reservoir: 0.78, viscosity: 0.78, plasticity: 0.64, bristleStrands: 96, relief: 0.66, gloss: 0.55 } }),
  defineBrushStudioV6RecipeSeed("impasto-knife", "임파스토 나이프", "페인트", "높이와 스크레이프가 남는 팔레트 나이프", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-ribbon", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-open-km", physics: ["physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 72, viscosity: 0.92, plasticity: 0.88, relief: 0.92, gloss: 0.65 } }),
  defineBrushStudioV6RecipeSeed("dripping-neon", "드리핑 네온 잉크", "FX", "젖은 발광 잉크가 중력으로 흐르는 효과", { slots: { deposition: "deposit-light", physics: ["physics-inkwash", "physics-thin-film"], finish: ["finish-neon", "finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 22, wetness: 0.72, gravity: 0.82, viscosity: 0.22, primaryColor: "#06b6d4", secondaryColor: "#d946ef" } }),
  defineBrushStudioV6RecipeSeed("dendritic-copper", "덴드라이트 코퍼", "FX", "구리 안료의 가지형 반응 성장", { slots: { carrier: "carrier-webgpu-particles", tip: "tip-grain-exemplar", surface: "surface-porous", deposition: "deposit-particles", pigment: "pigment-open-km", physics: ["physics-porous-paper", "physics-reaction"], finish: ["finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 24, reactionRate: 0.82, absorbency: 0.55, primaryColor: "#b45309", secondaryColor: "#0f766e" } }),
  defineBrushStudioV6RecipeSeed("holographic-stitch", "홀로그래픽 스티치", "패턴", "트위스트와 색 순환을 가진 연결 문양", { slots: { tip: "tip-motif-atlas", deposition: "deposit-light", pattern: "pattern-stitch", finish: ["finish-neon"], output: "output-contact-canvas-svg" }, tuning: { size: 16, patternDensity: 0.78, patternScale: 0.72, patternJitter: 0.05, primaryColor: "#0ea5e9", secondaryColor: "#ec4899" } }),
  defineBrushStudioV6RecipeSeed("moss-flow", "모스 플로우", "패턴", "GPU 입자와 잎 군집 문양으로 경로 주변에 성장하는 이끼", { slots: { carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", surface: "surface-porous", deposition: "deposit-wet", pigment: "pigment-spectral", physics: ["physics-porous-paper"], pattern: "pattern-foliage", finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 20, patternDensity: 0.9, patternScale: 0.7, patternJitter: 0.72, absorbency: 0.52, primaryColor: "#365314", secondaryColor: "#65a30d" } }),
  defineBrushStudioV6RecipeSeed("document-halftone", "문서 고정 하프톤", "만화", "확대·이동에도 위상이 고정되는 망점", { slots: { motion: "motion-direct", pattern: "pattern-dot-tone" }, tuning: { size: 44, patternDensity: 0.62, patternScale: 0.82 } }),
  defineBrushStudioV6RecipeSeed("kaleido-swarm", "칼레이도 스웜", "프로시저럴", "반사·회전 대칭과 입자 군집을 결합", { slots: { carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", deposition: "deposit-particles", physics: ["physics-particles"], pattern: "pattern-kaleido", finish: ["finish-neon"], output: "output-contact-canvas-svg" }, tuning: { size: 18, particleCount: 1100, patternDensity: 0.8, patternJitter: 0.5, primaryColor: "#7c3aed", secondaryColor: "#22d3ee" } }),
  ]);
