import { BRUSH_STUDIO_V6_TOPOLOGIES } from "./brush-studio-v6-topology-catalog";

import type { BrushStudioV6ProgramPatch } from "./brush-studio-v6-engine";

export interface BrushStudioV6RecipeSeed {
  readonly id: string;
  readonly label: string;
  readonly group: string;
  readonly description: string;
  readonly delta: BrushStudioV6ProgramPatch;
}

function seed(
  id: string,
  label: string,
  group: string,
  description: string,
  delta: BrushStudioV6ProgramPatch,
): BrushStudioV6RecipeSeed {
  return Object.freeze({ id, label, group, description, delta });
}

export const BRUSH_STUDIO_V6_RECIPE_SEEDS: readonly BrushStudioV6RecipeSeed[] =
  Object.freeze([
  seed("clean-ink", "클린 잉크", "선화", "낮은 지연과 매끈한 WebGPU 잉크", {}),
  seed("manga-gpen", "만화 G펜", "선화", "강한 필압 테이퍼와 벡터 외곽선", { slots: { carrier: "carrier-perfect-outline", output: "output-contact-canvas-svg" }, tuning: { size: 12, stabilization: 0.24 } }),
  seed("natural-calligraphy", "자연 캘리그래피", "선화", "치즐 접촉과 자연 잉크량 변화", { slots: { motion: "motion-spring", carrier: "carrier-libmypaint-dabs", tip: "tip-chisel-sdf", surface: "surface-kent", pigment: "pigment-spectral", output: "output-contact-canvas-svg" }, tuning: { size: 26, flow: 0.72, friction: 0.28 } }),
  seed("velvet-graphite", "벨벳 그래파이트", "건식", "실물 grain과 종이 접촉을 결합한 흑연", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-grain-exemplar", surface: "surface-printmaking", deposition: "deposit-dry", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 14, surfaceTooth: 0.78, friction: 0.62, granulation: 0.7 } }),
  seed("eroding-charcoal", "침식 목탄", "건식", "촉 마모와 가루·스머지가 남는 목탄", { slots: { carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 28, surfaceTooth: 0.88, pickup: 0.28, granulation: 0.82 } }),
  seed("alcohol-bloom", "알코올 블룸 마커", "마커", "용제 확산과 아래색 픽업을 가진 마커", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-chisel-sdf", surface: "surface-kent", deposition: "deposit-marker", pickup: "pickup-krita-smudge", pigment: "pigment-spectral", physics: ["physics-porous-paper"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 32, absorbency: 0.35, wetness: 0.34, pickup: 0.4, edgeDarkening: 0.32 } }),
  seed("mineral-bloom", "미네랄 블룸 워시", "습식", "K/S 광물 안료가 수채지 골에 과립 침전", { slots: { motion: "motion-brush-inertia", carrier: "carrier-webgpu-ribbon", surface: "surface-coldpress", deposition: "deposit-wet", pigment: "pigment-open-km", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom", "finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 48, wetness: 0.82, absorbency: 0.72, granulation: 0.82, edgeDarkening: 0.74, diffusion: 0.72 } }),
  seed("chroma-sumi", "크로마 수묵", "습식", "짙은 먹 중심과 청보라색 섬유 후광", { slots: { carrier: "carrier-hokusai-dabs", surface: "surface-porous", deposition: "deposit-wet", pigment: "pigment-inkwash-density", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-chroma", "finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 30, wetness: 0.68, absorbency: 0.8, edgeDarkening: 0.66, primaryColor: "#111827", secondaryColor: "#4338ca" } }),
  seed("wax-resist", "왁스 리지스트 수채", "습식", "왁스 마스크를 피해 흐르는 수채", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pigment: "pigment-spectral", physics: ["physics-dry-contact", "physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 42, wetness: 0.7, surfaceTooth: 0.72, granulation: 0.48 } }),
  seed("oil-hair-mixer", "오일 헤어 믹서", "페인트", "개별 강모 reservoir와 K/S 안료를 가진 유화", { slots: { motion: "motion-brush-inertia", carrier: "carrier-krita-hairy", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-open-km", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 54, pickup: 0.62, reservoir: 0.78, viscosity: 0.78, plasticity: 0.64, bristleStrands: 96, relief: 0.66, gloss: 0.55 } }),
  seed("impasto-knife", "임파스토 나이프", "페인트", "높이와 스크레이프가 남는 팔레트 나이프", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-ribbon", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-open-km", physics: ["physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 72, viscosity: 0.92, plasticity: 0.88, relief: 0.92, gloss: 0.65 } }),
  seed("mixbox-oil-bristle", "Mixbox 강모 유화", "Mixbox 회화", "GPL 강모 어댑터와 reservoir, 높이 도포, Mixbox 안료를 결합한 유화", { slots: { motion: "motion-brush-inertia", carrier: "carrier-krita-hairy", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-mixbox", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 58, pickup: 0.68, reservoir: 0.84, viscosity: 0.82, plasticity: 0.7, bristleStrands: 104, relief: 0.72, gloss: 0.52, primaryColor: "#f2b632", secondaryColor: "#244ac7" } }),
  seed("mixbox-watercolor-bloom", "Mixbox 수채 블룸", "Mixbox 회화", "Hokusai 호환 다브, 한지 결, 습식 확산과 Mixbox 안료를 결합한 수채", { slots: { motion: "motion-brush-inertia", carrier: "carrier-hokusai-dabs", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 46, opacity: 0.72, flow: 0.62, pickup: 0.34, wetness: 0.86, absorbency: 0.76, diffusion: 0.8, granulation: 0.7, edgeDarkening: 0.68, primaryColor: "#f4d03f", secondaryColor: "#2455d6" } }),
  seed("mixbox-gouache-dual", "Mixbox 듀얼 과슈", "Mixbox 회화", "듀얼 팁과 조밀한 습식 도포로 불투명한 두 안료를 섞는 과슈", { slots: { carrier: "carrier-hokusai-dabs", tip: "tip-krita-dual", surface: "surface-kent", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 34, opacity: 0.96, flow: 0.88, pickup: 0.42, wetness: 0.36, absorbency: 0.3, diffusion: 0.24, granulation: 0.18, edgeDarkening: 0.24, primaryColor: "#ffca3a", secondaryColor: "#1982c4" } }),
  seed("mixbox-pastel-smudge", "Mixbox 파스텔 스머지", "Mixbox 회화", "libmypaint 호환 다브, 듀얼 팁, 종이 이빨과 GPL 스머지 어댑터를 결합", { slots: { carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 30, opacity: 0.84, flow: 0.72, pickup: 0.5, surfaceTooth: 0.9, friction: 0.72, granulation: 0.86, primaryColor: "#f6bd60", secondaryColor: "#5e60ce" } }),
  seed("mixbox-alcohol-marker", "Mixbox 알코올 마커", "Mixbox 회화", "치즐 리본, 다공성 종이, 스머지 어댑터와 안료 혼합을 결합한 마커", { slots: { carrier: "carrier-webgpu-ribbon", tip: "tip-chisel-sdf", surface: "surface-kent", deposition: "deposit-marker", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 28, opacity: 0.7, flow: 0.72, pickup: 0.48, absorbency: 0.38, edgeDarkening: 0.35, primaryColor: "#ffb703", secondaryColor: "#3a86ff" } }),
  seed("mixbox-palette-knife", "Mixbox 팔레트 나이프", "Mixbox 회화", "넓은 칼날 접촉과 높이 물감, reservoir 안료를 결합한 임파스토", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-ribbon", tip: "tip-pigment-normal", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-mixbox", physics: ["physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 78, opacity: 0.98, flow: 0.9, pickup: 0.58, reservoir: 0.9, viscosity: 0.94, plasticity: 0.9, relief: 0.96, gloss: 0.62, primaryColor: "#fcbf49", secondaryColor: "#2a6fbb" } }),
  seed("mixbox-color-smudge", "Mixbox 컬러 스머지", "Mixbox 회화", "획 내부 안료 reservoir를 따라 두 색을 밀고 당기는 스머지 전용 조합", { slots: { motion: "motion-spring", carrier: "carrier-libmypaint-dabs", tip: "tip-round-sdf", surface: "surface-smooth", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-inkwash"], finish: [], output: "output-contact-canvas-svg" }, tuning: { size: 42, opacity: 0.8, flow: 0.62, pickup: 0.82, wetness: 0.58, diffusion: 0.34, primaryColor: "#ffd166", secondaryColor: "#4361ee" } }),
  seed("mixbox-colored-pencil", "Mixbox 컬러 연필", "Mixbox 회화", "libmypaint 접촉, 듀얼 안료 팁과 종이 이빨을 결합한 컬러 연필", { slots: { motion: "motion-adaptive-ema", carrier: "carrier-libmypaint-dabs", tip: "tip-krita-dual", surface: "surface-kent", deposition: "deposit-dry", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 12, opacity: 0.82, flow: 0.64, pickup: 0.28, surfaceTooth: 0.76, friction: 0.66, granulation: 0.7, primaryColor: "#f4a261", secondaryColor: "#457b9d" } }),
  seed("mixbox-charcoal-rake", "Mixbox 컬러 목탄 레이크", "Mixbox 회화", "갈퀴형 리본과 듀얼 팁으로 여러 색 목탄 가루를 긁어 쌓는 브러시", { slots: { motion: "motion-brush-inertia", carrier: "carrier-webgpu-ribbon", tip: "tip-krita-dual", surface: "surface-printmaking", deposition: "deposit-dry", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-dry-contact"], finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 30, opacity: 0.8, flow: 0.68, pickup: 0.44, surfaceTooth: 0.92, friction: 0.82, granulation: 0.92, primaryColor: "#bc6c25", secondaryColor: "#264653" } }),
  seed("mixbox-pigment-spray", "Mixbox 안료 스프레이", "Mixbox 입자", "GPU 입자와 모티프 팁, 거리별 Mixbox 색 변화를 결합한 안료 분사", { slots: { motion: "motion-direct", carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", surface: "surface-smooth", deposition: "deposit-particles", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-particles"], pattern: "pattern-rainbow", finish: [], output: "output-contact-canvas-svg" }, tuning: { size: 34, opacity: 0.74, flow: 0.7, particleCount: 1400, patternDensity: 0.82, patternScale: 0.72, patternJitter: 0.64, primaryColor: "#ffbe0b", secondaryColor: "#3a0ca3" } }),
  seed("mixbox-wax-resist", "Mixbox 왁스 리지스트", "Mixbox 회화", "마른 접촉 저항과 다공성 종이를 통과해 번지는 두 안료 수채", { slots: { motion: "motion-brush-inertia", carrier: "carrier-hokusai-dabs", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-dry-contact", "physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom"], output: "output-contact-canvas-svg" }, tuning: { size: 44, opacity: 0.76, flow: 0.58, surfaceTooth: 0.84, wetness: 0.78, absorbency: 0.68, diffusion: 0.66, granulation: 0.58, edgeDarkening: 0.55, primaryColor: "#ffd166", secondaryColor: "#118ab2" } }),
  seed("mixbox-bristle-calligraphy", "Mixbox 강모 캘리그래피", "Mixbox 회화", "스프링 필기감, 강모 reservoir와 높이 도포를 결합한 두꺼운 회화형 캘리그래피", { slots: { motion: "motion-spring", carrier: "carrier-krita-hairy", tip: "tip-chisel-sdf", surface: "surface-linen", deposition: "deposit-oil", pickup: "pickup-pigment-reservoir", pigment: "pigment-mixbox", physics: ["physics-bristle", "physics-height"], finish: ["finish-relief"], output: "output-contact-canvas-svg" }, tuning: { size: 46, opacity: 0.96, flow: 0.8, pickup: 0.64, reservoir: 0.82, viscosity: 0.76, plasticity: 0.6, bristleStrands: 88, relief: 0.62, primaryColor: "#e9c46a", secondaryColor: "#264653" } }),
  seed("mixbox-foliage-stamp", "Mixbox 폴리지 스탬프", "Mixbox 입자", "모티프 팁과 입자 군집으로 두 색 잎과 꽃을 경로 주변에 생성", { slots: { motion: "motion-adaptive-ema", carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", surface: "surface-porous", deposition: "deposit-particles", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-particles"], pattern: "pattern-foliage", finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 22, opacity: 0.88, flow: 0.76, particleCount: 980, patternDensity: 0.86, patternScale: 0.78, patternJitter: 0.6, primaryColor: "#588157", secondaryColor: "#dda15e" } }),
  seed("mixbox-neon-wet", "Mixbox 젖은 네온", "Mixbox FX", "발광 도포와 안료 혼색, 얇은 막 중력 드립을 동시에 사용하는 네온 잉크", { slots: { motion: "motion-spring", carrier: "carrier-webgpu-centerline", tip: "tip-round-sdf", surface: "surface-smooth", deposition: "deposit-light", pickup: "pickup-none", pigment: "pigment-mixbox", physics: ["physics-inkwash", "physics-thin-film"], pattern: "pattern-none", finish: ["finish-neon", "finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 24, opacity: 0.86, flow: 0.7, wetness: 0.7, diffusion: 0.4, gravity: 0.76, viscosity: 0.24, primaryColor: "#00f5d4", secondaryColor: "#f15bb5" } }),
  seed("mixbox-granulating-ink", "Mixbox 입상 컬러 먹", "Mixbox 회화", "Hokusai 접촉과 종이 섬유, 색 분리·젖은 광택을 함께 정착시키는 컬러 먹", { slots: { motion: "motion-brush-inertia", carrier: "carrier-hokusai-dabs", tip: "tip-grain-exemplar", surface: "surface-coldpress", deposition: "deposit-wet", pickup: "pickup-krita-smudge", pigment: "pigment-mixbox", physics: ["physics-porous-paper", "physics-inkwash"], finish: ["finish-edge-bloom", "finish-wet-sheen", "finish-chroma"], output: "output-contact-canvas-svg" }, tuning: { size: 38, opacity: 0.72, flow: 0.58, pickup: 0.36, wetness: 0.9, absorbency: 0.82, diffusion: 0.84, granulation: 0.9, edgeDarkening: 0.7, primaryColor: "#e9c46a", secondaryColor: "#3a0ca3" } }),
  seed("dripping-neon", "드리핑 네온 잉크", "FX", "젖은 발광 잉크가 중력으로 흐르는 효과", { slots: { deposition: "deposit-light", physics: ["physics-inkwash", "physics-thin-film"], finish: ["finish-neon", "finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 22, wetness: 0.72, gravity: 0.82, viscosity: 0.22, primaryColor: "#06b6d4", secondaryColor: "#d946ef" } }),
  seed("dendritic-copper", "덴드라이트 코퍼", "FX", "구리 안료의 가지형 반응 성장", { slots: { carrier: "carrier-webgpu-particles", tip: "tip-grain-exemplar", surface: "surface-porous", deposition: "deposit-particles", pigment: "pigment-open-km", physics: ["physics-porous-paper", "physics-reaction"], finish: ["finish-wet-sheen"], output: "output-contact-canvas-svg" }, tuning: { size: 24, reactionRate: 0.82, absorbency: 0.55, primaryColor: "#b45309", secondaryColor: "#0f766e" } }),
  seed("holographic-stitch", "홀로그래픽 스티치", "패턴", "트위스트와 색 순환을 가진 연결 문양", { slots: { tip: "tip-motif-atlas", deposition: "deposit-light", pattern: "pattern-stitch", finish: ["finish-neon"], output: "output-contact-canvas-svg" }, tuning: { size: 16, patternDensity: 0.78, patternScale: 0.72, patternJitter: 0.05, primaryColor: "#0ea5e9", secondaryColor: "#ec4899" } }),
  seed("moss-flow", "모스 플로우", "패턴", "플로우필드 위에서 성장하는 이끼 군집", { slots: { carrier: "carrier-p5-flow", tip: "tip-motif-atlas", surface: "surface-porous", deposition: "deposit-wet", pigment: "pigment-spectral", physics: ["physics-porous-paper"], pattern: "pattern-foliage", finish: ["finish-grain"], output: "output-contact-canvas-svg" }, tuning: { size: 20, patternDensity: 0.9, patternScale: 0.7, patternJitter: 0.72, absorbency: 0.52, primaryColor: "#365314", secondaryColor: "#65a30d" } }),
  seed("document-halftone", "문서 고정 하프톤", "만화", "확대·이동에도 위상이 고정되는 망점", { slots: { motion: "motion-direct", pattern: "pattern-dot-tone" }, tuning: { size: 44, patternDensity: 0.62, patternScale: 0.82 } }),
  seed("kaleido-swarm", "칼레이도 스웜", "프로시저럴", "반사·회전 대칭과 입자 군집을 결합", { slots: { carrier: "carrier-webgpu-particles", tip: "tip-motif-atlas", deposition: "deposit-particles", physics: ["physics-particles"], pattern: "pattern-kaleido", finish: ["finish-neon"], output: "output-contact-canvas-svg" }, tuning: { size: 18, particleCount: 1100, patternDensity: 0.8, patternJitter: 0.5, primaryColor: "#7c3aed", secondaryColor: "#22d3ee" } }),
  ...BRUSH_STUDIO_V6_TOPOLOGIES.map((entry) => seed(entry.recipeId, entry.label, entry.group ?? "획 구조·물리", entry.description, {
    slots: { motion: "motion-direct", carrier: entry.id, surface: "surface-kent", pigment: "pigment-spectral" },
    tuning: entry.tuning,
  })),
]);
