/**
 * Closed catalog of motion-coach visuals.
 *
 * Keeping the runtime list beside the type makes preview coverage auditable:
 * every new kind is automatically exercised by reduced-motion and animation tests.
 */
export const STUDIO_TOOL_HINT_PREVIEW_KINDS = [
  "select",
  "transform",
  "pan",
  "ink",
  "pixel-ink",
  "erase",
  "fill",
  "sample",
  "shape",
  "smart-shape",
  "shape-rect",
  "shape-ellipse",
  "text",
  "bubble",
  "comment",
  "image",
  "reference",
  "filter",
  "smudge",
  "liquify",
  "lasso",
  "lasso-fill",
  "marquee-rect",
  "marquee-ellipse",
  "crop",
  "perspective",
  "rotate-view",
  "brush-size",
  "opacity",
  "stabilizer",
  "pressure",
  "symmetry",
  "zoom-view",
  "history",
  "undo",
  "redo",
  "layer",
  "layer-visibility",
  "layer-lock",
  "layer-merge",
  "layer-actions",
  "timeline",
  "keyframe",
  "frame-sequence",
  "frame-capture",
  "frame-playback",
  "frame-reorder",
  "frame-duplicate",
  "frame-delete",
  "onion-skin",
  "timelapse",
  "motion-fx",
  "video-export",
  "audio",
  "object-3d",
  "object-translate",
  "object-rotate",
  "object-scale",
  "object-ground",
  "pose-3d",
  "camera-3d",
  "camera-zoom",
  "camera-reset",
  "camera-orbit",
  "quad-view",
  "lighting-3d",
  "line-art",
  "assets",
  "export",
  "project",
  "fullscreen",
  "settings",
  "save",
  "publish",
  "ai-assist",
] as const;

export type StudioToolHintPreviewKind =
  (typeof STUDIO_TOOL_HINT_PREVIEW_KINDS)[number];
