import { expect, test } from "@playwright/test";

/** Production component and real canvas/recording; only the text AI HTTP boundary is mocked. */
test("promo editor uploads, edits, plans, exports and cancels", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.route("**/api/studio-ai/status", (route) => route.fulfill({ json: { configured: true, requiresAuth: true } }));
  let malformed = false;
  let posted = "";
  await page.route("**/api/studio-ai/chat", (route) => {
    const body = route.request().postDataJSON() as { user: string };
    posted = body.user;
    const data = JSON.parse(body.user) as { panels: { id: string }[] };
    expect(route.request().headers()["idempotency-key"]).toMatch(/^promo-/u);
    return route.fulfill({ json: { provider: "zai", model: "ci-text-fixture", content: malformed ? '{"scenes":[]}' : JSON.stringify({ scenes: [...data.panels].reverse().map((panel, index) => ({ id: panel.id, caption: `예고편 자막 ${index + 1}`, motion: "push-in", weight: 1 })) }) } });
  });
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto("/tools/browser-harnesses/promo-e2e.html");
  await expect(page.getByRole("heading", { level: 1 })).toBeVisible();
  const fixtures = await page.evaluate(() => [0, 1, 2].map((index) => {
    const canvas = document.createElement("canvas");
    canvas.width = 600; canvas.height = 900;
    const context = canvas.getContext("2d");
    if (!context) throw new Error("No canvas context");
    context.fillStyle = ["#192b4f", "#51314b", "#244c4d"][index] ?? "#192b4f";
    context.fillRect(0, 0, 600, 900);
    context.fillStyle = "#e1d5ba";
    context.fillRect(70 + index * 40, 180, 230, 480);
    context.fillStyle = "#f5b47e";
    context.beginPath(); context.arc(320, 250 + index * 150, 110, 0, Math.PI * 2); context.fill();
    context.fillStyle = "#ffffff"; context.font = "bold 48px sans-serif"; context.fillText(`CUT ${index + 1}`, 70, 790);
    return canvas.toDataURL("image/png").split(",")[1] ?? "";
  }));
  await page.locator("#promo-panels").setInputFiles(fixtures.map((data, index) => ({ name: `cut-${index}.png`, mimeType: "image/png", buffer: Buffer.from(data, "base64") })));
  await expect(page.locator(".promo-shot")).toHaveCount(3);
  await page.locator("#promo-work-title").fill("별빛 아래, 우리의 이야기");
  await page.locator("#promo-synopsis").fill("밤의 도시에서 다시 만난 두 사람의 로맨스. 결말은 공개하지 않는다.");
  await page.locator(".promo-shot textarea").first().fill("밤의 도시를 바라보는 주인공");
  await page.getByRole("button", { name: "로컬 연출 템플릿", exact: true }).click();
  await expect(page.locator(".promo-feedback")).toContainText("AI 생성 결과가 아니며");
  await page.getByRole("button", { name: "AI로 홍보 콘티 구성", exact: true }).click();
  await expect(page.locator(".promo-feedback")).toContainText("ci-text-fixture");
  expect(posted).not.toContain("base64");
  expect(posted).not.toContain('"src"');
  await expect(page.locator('input[id^="caption-"]').first()).toHaveValue("예고편 자막 1");
  malformed = true;
  await page.getByRole("button", { name: "AI로 홍보 콘티 구성", exact: true }).click();
  await expect(page.locator(".promo-error")).toContainText("컷 수");
  await expect(page.locator('input[id^="caption-"]').first()).toHaveValue("예고편 자막 1");
  await page.getByRole("button", { name: "로컬 연출 템플릿", exact: true }).click();
  const wav = Buffer.alloc(44 + 16000 * 2);
  wav.write("RIFF"); wav.writeUInt32LE(wav.length - 8, 4); wav.write("WAVEfmt ", 8);
  wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22);
  wav.writeUInt32LE(16000, 24); wav.writeUInt32LE(32000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34);
  wav.write("data", 36); wav.writeUInt32LE(32000, 40);
  for (let index = 0; index < 16000; index += 1) wav.writeInt16LE(Math.round(Math.sin(index * Math.PI * 2 * 220 / 16000) * 6000), 44 + index * 2);
  await page.locator("#promo-audio").setInputFiles({ name: "ci-tone.wav", mimeType: "audio/wav", buffer: wav });
  await expect(page.getByRole("button", { name: "BGM 제거" })).toBeVisible();
  await page.getByRole("button", { name: "재생", exact: true }).click();
  await expect(page.locator(".promo-playback output")).not.toContainText("0.0 /");
  await page.getByRole("button", { name: "일시정지", exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath("promo-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("promo-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1050 });
  const [kit] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "Remotion 프로젝트 ZIP", exact: true }).click()]);
  await kit.saveAs(testInfo.outputPath("render-kit.zip"));
  const [srt] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "자막 SRT", exact: true }).click()]);
  await srt.saveAs(testInfo.outputPath("captions.srt"));
  const [json] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: "프로젝트 JSON 저장", exact: true }).click()]);
  const jsonPath = testInfo.outputPath("project.json");
  await json.saveAs(jsonPath);
  await page.locator("#promo-work-title").fill("변경된 제목");
  await page.locator("#promo-import").setInputFiles(jsonPath);
  await expect(page.locator("#promo-work-title")).toHaveValue("별빛 아래, 우리의 이야기");
  const save = page.getByRole("button", { name: /^영상 저장 ·/u });
  await save.click();
  await expect(page.getByRole("button", { name: "작업 취소", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "작업 취소", exact: true }).click();
  await expect(save).toBeEnabled();
  await expect(page.locator(".promo-feedback")).toContainText("취소");
  const [video] = await Promise.all([page.waitForEvent("download", { timeout: 45_000 }), save.click()]);
  await video.saveAs(testInfo.outputPath(video.suggestedFilename()));
  await expect(page.locator(".promo-feedback")).toContainText("영상 파일을 저장");
  expect(errors).toEqual([]);
});
