export function downloadFile(content: string | Blob, name: string, type = "text/plain;charset=utf-8"): void {
  const blob = typeof content === "string" ? new Blob([content], { type }) : content;
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url; anchor.download = name; anchor.style.display = "none";
  document.body.append(anchor); anchor.click(); anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 15000);
}
/** Rasterize only SVG generated by this module's callers; no external image URLs. */
export async function downloadPng(svg: string, name: string, width = 960, height = 600): Promise<void> {
  const url = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml;charset=utf-8" }));
  try {
    const image = new Image();
    await new Promise<void>((resolve, reject) => {
      const timer = window.setTimeout(() => reject(new Error("이미지 변환 시간이 초과됐습니다. SVG 저장을 사용해 주세요.")), 10000);
      image.onload = () => { clearTimeout(timer); resolve(); };
      image.onerror = () => { clearTimeout(timer); reject(new Error("이 브라우저에서 PNG 변환을 완료하지 못했습니다. SVG 저장을 사용해 주세요.")); };
      image.src = url;
    });
    const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height;
    const context = canvas.getContext("2d");
    if (!context) throw new Error("PNG 변환을 사용할 수 없습니다. SVG 저장을 사용해 주세요.");
    context.drawImage(image, 0, 0, width, height);
    const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((result) => result ? resolve(result) : reject(new Error("PNG 저장 실패. SVG 저장을 사용해 주세요.")), "image/png"));
    downloadFile(blob, name);
  } finally { URL.revokeObjectURL(url); }
}
export async function copyText(text: string): Promise<boolean> {
  try { await navigator.clipboard.writeText(text); return true; } catch { return false; }
}
