import { ArrowRight, Bookmark, Clapperboard, PenLine, RefreshCw, Search, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";

import { PROMOTION_GENRES, PROMOTION_KINDS, PROMOTION_STAGES } from "../../../../../packages/core/src/promotion";
import { usePromotionFeed } from "./use-promotion-feed";
import "./promotion-community.css";

import { useApp } from "@/shared/lib/store";
import { useDocumentTitle } from "@/hooks/use-document-title";

export function PromotionBoardPage() {
  useDocumentTitle("신작·작가 홍보 커뮤니티 · ToonStudio");
  const userId = useApp((state) => state.userId);
  const [params, setParams] = useSearchParams(), [search, setSearch] = useState(params.get("q") ?? "");
  const filters = new URLSearchParams();
  for (const name of ["kind", "stage", "genre", "q", "mine", "saved"]) { const value = params.get(name); if (value) filters.set(name, value); }
  const feed = usePromotionFeed(filters.toString(), userId);
  const setFilter = (name: string, value: string) => setParams((previous) => { const next = new URLSearchParams(previous); if (value && value !== "all") next.set(name, value); else next.delete(name); return next; });
  return <div className="pc-shell">
    <header className="pc-hero"><div><p className="pc-eyebrow"><Sparkles size={16} aria-hidden="true" /> TOONSTUDIO · CREATOR SPOTLIGHT</p><h1>아직 발견하지 못한,<br /><em>당신의 다음 웹툰.</em></h1><p className="pc-lead">첫 연재의 설렘부터 한 편의 트레일러까지.<br />새로운 작가를 만나고, 만드는 과정을 응원해 주세요.</p><div className="pc-actions"><Link className="pc-button pc-primary" to="/community/promote/new"><PenLine size={17} aria-hidden="true" />내 작품 소개하기</Link><Link className="pc-button" to="/collaborate">용역·어시·팀원 찾기 <ArrowRight size={16} aria-hidden="true" /></Link><Link className="pc-button" to="/showcase">창작 갤러리 <ArrowRight size={16} aria-hidden="true" /></Link></div></div><aside className="pc-hero-note"><Clapperboard size={42} aria-hidden="true" /><strong>완성 전의 이야기도,<br />시작하는 작가도 환영해요.</strong><span>직접 창작한 작품 · 제작 과정 · 첫 독자의 피드백</span><p>유료 상단 노출 없이 최신 등록순으로 만나요.</p></aside></header>
    <nav className="pc-quick" aria-label="추천 탐색"><button type="button" onClick={() => { setParams({ stage: "amateur" }); setSearch(""); }}>01 <strong>아마추어 작가 발견</strong><ArrowRight size={16} aria-hidden="true" /></button><button type="button" onClick={() => { setParams({ stage: "debut" }); setSearch(""); }}>02 <strong>첫 작품·신작 모아보기</strong><ArrowRight size={16} aria-hidden="true" /></button><button type="button" onClick={() => { setParams({ kind: "trailer" }); setSearch(""); }}>03 <strong>트레일러 상영관</strong><ArrowRight size={16} aria-hidden="true" /></button></nav>
    <section aria-labelledby="pc-discover-title"><div className="pc-heading"><div><p className="pc-eyebrow">DISCOVER THE NEXT STORY</p><h2 id="pc-discover-title">창작자의 이야기를 만나보세요</h2></div><button className="pc-button" type="button" disabled={feed.loading} onClick={feed.refresh}><RefreshCw size={16} aria-hidden="true" />새로고침</button></div>
      <form className="pc-search" role="search" onSubmit={(event) => { event.preventDefault(); setFilter("q", search.trim()); }}><Search size={19} aria-hidden="true" /><label className="sr-only" htmlFor="pc-search">작품명·제목·태그 검색</label><input id="pc-search" type="search" maxLength={100} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="작품명, 제목, 태그로 검색" /><button className="pc-button" type="submit">검색</button></form>
      <div className="pc-tabs" role="group" aria-label="게시물 유형">{Object.entries({ all: "전체", ...PROMOTION_KINDS }).map(([value, label]) => <button key={value} type="button" aria-pressed={(params.get("kind") ?? "all") === value} onClick={() => setFilter("kind", value)}>{label}</button>)}</div>
      <div className="pc-filters"><label>활동 단계<select value={params.get("stage") ?? "all"} onChange={(event) => setFilter("stage", event.target.value)}><option value="all">모든 작가</option>{Object.entries(PROMOTION_STAGES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>장르<select value={params.get("genre") ?? "all"} onChange={(event) => setFilter("genre", event.target.value)}><option value="all">모든 장르</option>{PROMOTION_GENRES.map((genre) => <option key={genre}>{genre}</option>)}</select></label><button className="pc-button" disabled={!userId} type="button" aria-pressed={params.get("mine") === "true"} onClick={() => setFilter("mine", params.get("mine") === "true" ? "" : "true")}>내 게시물</button><button className="pc-button" disabled={!userId} type="button" aria-pressed={params.get("saved") === "true"} onClick={() => setFilter("saved", params.get("saved") === "true" ? "" : "true")}><Bookmark size={15} aria-hidden="true" />저장한 작품</button>{filters.size > 0 && <button className="pc-text-button" type="button" onClick={() => { setParams({}); setSearch(""); }}>필터 초기화</button>}</div>
      {feed.error && <div className="pc-error" role="alert">{feed.error}<button className="pc-button" type="button" onClick={feed.refresh}>다시 시도</button></div>}
      {feed.loading && <p className="pc-notice" role="status">새로운 작품을 불러오고 있어요.</p>}
      {!feed.loading && !feed.error && feed.page?.items.length === 0 && <div className="pc-empty"><PenLine size={38} aria-hidden="true" /><h3>첫 이야기를 기다리고 있어요</h3><p>조건에 맞는 공개 게시물이 아직 없어요.<br />직접 만든 작품과 작업 과정을 소개해 주세요.</p><Link className="pc-button pc-primary" to="/community/promote/new">첫 소개 작성하기</Link></div>}
      <div className="pc-grid">{feed.page?.items.map((post) => <article className="pc-card" key={post.id}><Link className="pc-card-cover" to={`/community/promote/${encodeURIComponent(post.id)}`}>{post.cover ? <img src={post.cover} alt={`${post.seriesTitle} 표지`} loading="lazy" decoding="async" width={640} height={800} /> : <div className="pc-cover-placeholder"><span>{post.genre}</span><strong>{post.seriesTitle}</strong><PenLine size={28} aria-hidden="true" /></div>}{post.videoUrl && <span className="pc-video-badge"><Clapperboard size={14} aria-hidden="true" />영상</span>}</Link><div className="pc-card-body"><div className="pc-tags"><span>{PROMOTION_STAGES[post.stage]}</span><span>{PROMOTION_KINDS[post.kind]}</span>{post.archived && <span>보관됨</span>}{post.hidden && <span>운영 비공개</span>}</div><h3><Link to={`/community/promote/${encodeURIComponent(post.id)}`}>{post.title}</Link></h3><p>{post.description}</p><div className="pc-card-footer"><Link to={`/u/${encodeURIComponent(post.author.id)}`}>{post.author.name}</Link><time dateTime={post.createdAt}>{new Date(post.createdAt).toLocaleDateString("ko-KR")}</time></div></div></article>)}</div>
      {feed.page?.hasMore && <div className="pc-load-more"><button className="pc-button" type="button" disabled={feed.moreLoading || feed.loading} onClick={() => void feed.loadMore()}>{feed.moreLoading ? "불러오는 중…" : "더 많은 작품 보기"}</button></div>}
    </section><footer className="pc-bottom"><p>읽기는 누구나, 등록·댓글·저장은 로그인 후 이용할 수 있어요. 도용·스팸·괴롭힘은 신고해 주세요.</p><Link to="/community">전체 커뮤니티</Link>{feed.page?.canModerate && <Link to="/community/promote/moderation">홍보 신고 관리</Link>}</footer>
  </div>;
}
