import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import { makeDocument, makeLayer, validateDocument, documentPointCount, drawStroke } from '../../apps/web/public/offline-draw/model.js';
import { makeStory, validateStory, panelSize, multiply, transform, perspective, rayHits } from '../../apps/web/public/spatial-reader/story.js';
const req=createRequire(import.meta.url);let ts;try{ts=req('typescript');}catch{ts=req('/usr/local/slides_js/node_modules/typescript');}
function typescript(file,globals={}){const context={exports:{},Request,Response,URL,AbortController,setTimeout,clearTimeout,fetch,...globals};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);return context.exports;}
const stroke=()=>({tool:'pen',color:'#112233',size:12,points:[{x:30,y:40,p:.2},{x:95,y:70,p:.9}]});
const doc=()=>{const value=makeDocument();value.layers[0].strokes.push(stroke());return value;};
const chapter=()=>({...makeStory(),panels:[{id:'panel1',caption:'한글 자막',seconds:6,aspect:1.5,layers:[{image:'data:image/png;base64,aGVsbG8=',depth:0,x:0,y:0,scale:1}]}]});
// Structural tests deliberately do not claim to decode the placeholder image above.
test('drawing validates and counts exact stroke points',()=>{assert.equal(documentPointCount(validateDocument(doc())),2);});
test('unknown backup fields do not enter state',()=>{const d=doc();d.remoteUrl='https://example.com';d.layers[0].remote='x';assert.equal(validateDocument(d).remoteUrl,undefined);assert.equal(validateDocument(d).layers[0].remote,undefined);});
for(const[name,change]of[
 ['unsupported format',d=>d.format='other'],['future version',d=>d.version=2],['NaN width',d=>d.width=NaN],['pixel budget',d=>{d.width=4096;d.height=4096;}],['fractional width',d=>d.width=1280.5],['no layers',d=>d.layers=[]],['too many layers',d=>d.layers=Array.from({length:9},()=>makeLayer())],['duplicate layer id',d=>d.layers.push(structuredClone(d.layers[0]))],['out of bounds point',d=>d.layers[0].strokes[0].points[0].x=-1],['pressure infinity',d=>d.layers[0].strokes[0].points[0].p=Infinity],['remote image',d=>d.layers[0].raster='https://example.com/image.png'],['SVG image',d=>d.layers[0].raster='data:image/svg+xml;base64,aA=='],['CSS color injection',d=>d.background='url(javascript:x)'],['empty title',d=>d.title=''],['unknown tool',d=>d.layers[0].strokes[0].tool='runScript'],['opacity overflow',d=>d.layers[0].opacity=2],['empty stroke',d=>d.layers[0].strokes[0].points=[]],
])test('drawing rejects '+name,()=>{const d=doc();change(d);assert.throws(()=>validateDocument(d));});
function trace(tool){const calls=[];const ctx=new Proxy({}, {get:(_,key)=>(...args)=>calls.push([key,...args]),set:(_,key,value)=>{calls.push([key,value]);return true;}});drawStroke(ctx,{...stroke(),tool});return calls;}
test('pencil has deterministic reproducible dab texture',()=>{assert.deepEqual(trace('pencil'),trace('pencil'));assert.ok(trace('pencil').some(c=>c[0]==='fillRect'));});
test('brushes use distinct rendering geometry, not only different numbers',()=>{assert.ok(trace('pen').some(c=>c[0]==='arc'));assert.ok(trace('marker').some(c=>c[0]==='ellipse'));assert.ok(trace('eraser').some(c=>c[0]==='globalCompositeOperation'&&c[1]==='destination-out'));});
test('spatial chapter keeps source ordering and Korean captions',()=>{assert.equal(validateStory(chapter()).panels[0].caption,'한글 자막');});
for(const[name,change]of[
 ['empty chapter',v=>v.panels=[]],['remote texture',v=>v.panels[0].layers[0].image='https://example.com/a.png'],['executable SVG',v=>v.panels[0].layers[0].image='data:image/svg+xml;base64,aA=='],['depth over comfort bound',v=>v.panels[0].layers[0].depth=.36],['duplicate panels',v=>v.panels.push(structuredClone(v.panels[0]))],['infinite aspect',v=>v.panels[0].aspect=Infinity],['very fast autoplay',v=>v.panels[0].seconds=1],['too many layers',v=>v.panels[0].layers=Array(5).fill(v.panels[0].layers[0])],
])test('spatial rejects '+name,()=>{const value=chapter();change(value);assert.throws(()=>validateStory(value));});
test('spatial panel fitting respects comfortable width/height bounds',()=>{for(const aspect of [.1,.5,1,2,10]){const[w,h]=panelSize({aspect});assert.ok(w<=2.4+1e-6&&h<=1.6);assert.ok(Math.abs(w/h-aspect)<1e-6);}});
test('matrix identity and translation are correctly column-major',()=>{const t=transform(1,2,-3);assert.ok([...multiply(transform(),t)].every((v,i)=>Math.abs(v-t[i])<1e-6));assert.ok([...multiply(t,transform())].every((v,i)=>Math.abs(v-t[i])<1e-6));assert.deepEqual([...t.slice(12,15)],[1,2,-3]);assert.ok([...perspective(1.5)].every(Number.isFinite));});
test('controller selection handles hit, miss, behind and parallel ray',()=>{const target={x:0,y:0,z:-2,yaw:0,w:1,h:1};assert.ok(rayHits([0,0,0],[0,0,-1],target));assert.ok(!rayHits([2,0,0],[0,0,-1],target));assert.ok(!rayHits([0,0,-3],[0,0,-1],target));assert.ok(!rayHits([0,0,0],[1,0,0],target));});
const emergency='apps/web/src/app/service-worker/emergency-drawing.ts';
test('emergency routes never intercept writes, API, cross-origin or partial requests',()=>{const a=typescript(emergency);const origin='https://studio.test';assert.equal(a.emergencyDrawingPath(new Request(origin+'/offline-draw/'),origin),'/offline-draw/index.html');for(const r of [new Request(origin+'/offline-draw/',{method:'POST'}),new Request(origin+'/api/user'),new Request('https://other.test/offline-draw/'),new Request(origin+'/offline-draw/model.js',{headers:{range:'bytes=0-4'}})])assert.equal(a.emergencyDrawingPath(r,origin),null);});
test('navigation accepts normal responses and refuses 503 preload',async()=>{const a=typescript(emergency);const r=new Request('https://studio.test/studio');assert.equal((await a.navigationWithDeadline(r,Promise.resolve(new Response('ok')),50)).status,200);await assert.rejects(a.navigationWithDeadline(r,Promise.resolve(new Response('bad',{status:503})),50));});
test('navigation hangs are deadline bounded',async()=>{const a=typescript(emergency);const start=Date.now();await assert.rejects(a.navigationWithDeadline(new Request('https://studio.test/studio'),new Promise(()=>{}),15));assert.ok(Date.now()-start<500);});
test('missing or blocked emergency storage does not invent a ready shell',async()=>{const a=typescript(emergency,{caches:{open:async()=>{throw new Error('blocked');}}});assert.equal(await a.readEmergencyDrawing(),undefined);});
async function cacheHarness(bad=false){const stored=new Map();const cache={match:async key=>stored.get(key),delete:async key=>stored.delete(key),put:async(key,r)=>stored.set(key,r)};let calls=0;const g={Response,URL,AbortController,setTimeout,clearTimeout,location:{origin:'https://studio.test'},caches:{open:async()=>cache,delete:async()=>true},fetch:async url=>{calls++;const html=url.endsWith('.html');return new Response('test bytes',{status:bad&&url.endsWith('editor.js')?503:200,headers:{'content-type':html?'text/html':url.endsWith('.css')?'text/css':'application/javascript'}});}};vm.runInNewContext(fs.readFileSync('apps/web/public/offline-draw/cache.js','utf8'),g);return{api:g.ToonLocalCache,stored,get calls(){return calls;}};}
test('offline shell becomes ready only after all eight validated files',async()=>{const h=await cacheHarness();await h.api.prepare();assert.equal(h.stored.size,9);assert.equal(h.calls,8);await h.api.prepare();assert.equal(h.calls,8);});
test('failed shell asset cannot create a ready marker',async()=>{const h=await cacheHarness(true);await assert.rejects(h.api.prepare());assert.equal(h.stored.has('/offline-draw/ready-v2'),false);});
