import type { ResourceSource } from "./sources";

export const ADDITIONAL_RESOURCE_SOURCES: ResourceSource[] = [
  { name: "GBIF", freeKeyless: true, integration: "운영 연결", auth: "없음", rights: "레코드별 확인", importMode: "검색·원문 링크", productRoute: "/research/creatures", termsReviewedAt: "2026-09-25", category: "글로벌 생물종·관찰·분포", status: "종 매칭·이미지 보유 관찰 레코드 검색 구현", commercial: "조건부 상업 이용", url: "https://techdocs.gbif.org/en/openapi/", note: "전 세계 생물 종·관찰 위치·이미지·분포 메타데이터를 크리처 도감과 배경 생태 검수에 연결합니다. 미디어 라이선스는 레코드별로 검사하고 원본 이미지는 직접 반입하지 않습니다." },
  { name: "MET Norway WeatherAPI", freeKeyless: true, integration: "운영 연결", auth: "없음", rights: "출처표시", importMode: "검색·원문 링크", productRoute: "/research/weather-light", termsReviewedAt: "2026-09-25", category: "글로벌 날씨·빛", status: "위치 예보·캐시·식별 User-Agent 구현", commercial: "조건부 상업 이용", url: "https://api.met.no/", note: "도시명 또는 위도·경도로 기온·구름·습도·바람·강수 예보를 조회해 장면 연출 참고로 변환합니다. 실제 안전 판단에는 현지 공식 경보를 확인합니다." },
  { name: "OpenTopography", freeAccess: true, integration: "신청·승인 필요", auth: "API 키", rights: "레코드별 확인", importMode: "레퍼런스 보드", termsReviewedAt: "2026-09-25", category: "고도·DEM·지형", status: "API 키·데이터셋 권리 매핑 준비", commercial: "조건부 상업 이용", url: "https://opentopography.org/developers", note: "고도 데이터를 높이맵·지형 실루엣·3D 배경 블로킹에 연결할 후보입니다. 데이터셋별 출처와 라이선스를 함께 저장합니다." },
  { name: "Google Fonts Developer API", freeAccess: true, integration: "어댑터 구현", auth: "API 키", rights: "레코드별 확인", importMode: "레퍼런스 보드", productRoute: "/research/fonts", termsReviewedAt: "2026-09-25", category: "레터링·폰트", status: "전용 제한키 발급·검색·실제 미리보기 구현·운영 등록 대기", commercial: "조건부 상업 이용", url: "https://developers.google.com/fonts/docs/developer_api", note: "Web Fonts API 전용 제한키로 글꼴 가족·한글 서브셋·굵기·장르를 검색합니다. 실제 글꼴을 미리보되 작품 포함·임베딩·재배포 조건은 각 글꼴 상세 페이지의 라이선스를 최종 기준으로 사용합니다." },
  { name: "MusicBrainz", freeKeyless: true, integration: "운영 연결", auth: "없음", rights: "메타데이터 전용", importMode: "검색·원문 링크", productRoute: "/research/music-metadata", termsReviewedAt: "2026-09-25", category: "음악 메타데이터", status: "음악가 메타데이터 검색·호출 간격 구현", commercial: "조건부 상업 이용", url: "https://musicbrainz.org/doc/MusicBrainz_API", note: "음악가·그룹의 국가·활동 기간·동명이인 메타데이터를 BGM 레퍼런스 보드에 연결합니다. 음원 파일 제공이나 음악 사용 허가 API로 취급하지 않습니다." },
  { name: "Wikimedia Analytics", freeKeyless: true, integration: "운영 연결", auth: "없음", rights: "메타데이터 전용", importMode: "검색·원문 링크", termsReviewedAt: "2026-09-25", productRoute: "/research/open-data/wikimedia", category: "백과 조회 관심 신호", status: "최근 30일 Pageviews 집계 구현", commercial: "조건부 상업 이용", url: "https://api.wikimedia.org/wiki/Analytics_API", note: "한국어 위키백과 문서 조회 변화를 30일 집계 카드로 표시합니다. 사실 검증·독자 수·매출·작품 성공 가능성과 합산하지 않습니다." },
  { name: "GDELT", freeKeyless: true, integration: "기술 검토", auth: "없음", rights: "메타데이터 전용", importMode: "검색·원문 링크", termsReviewedAt: "2026-09-25", category: "글로벌 뉴스 관심 신호", status: "뉴스 노출 시계열·중복 제거 설계", commercial: "조건부 상업 이용", url: "https://www.gdeltproject.org/", note: "키워드·지역·시간대별 뉴스 노출을 소재 탐색 신호로 분리 표시합니다. 사실 판정이나 작품 성공 예측에 사용하지 않습니다." },
  { name: "DPLA", freeAccess: true, integration: "운영 연결", auth: "API 키", rights: "레코드별 확인", importMode: "검색·원문 링크", termsReviewedAt: "2026-09-25", productRoute: "/research/open-data/dpla", category: "미국 문화유산 통합검색", status: "무료 키 발급·운영 비밀 등록·검색 어댑터 구현", commercial: "조건부 상업 이용", url: "https://pro.dp.la/developers", note: "미국 도서관·박물관·아카이브의 통합 메타데이터를 검색합니다. 이미지·원문은 직접 가져오지 않고 에셋 권리는 원 제공기관을 최종 기준으로 사용합니다." },
  { name: "Internet Archive", freeKeyless: true, integration: "운영 연결", auth: "없음", rights: "레코드별 확인", importMode: "검색·원문 링크", productRoute: "/research/archive", termsReviewedAt: "2026-09-25", category: "도서·잡지·영상·음원", status: "메타데이터 discovery 검색 구현", commercial: "조건부 상업 이용", url: "https://archive.org/developers/index-apis.html", note: "역사 도서·잡지·영상·음원 항목의 메타데이터와 원문 링크를 제공합니다. 컬렉션과 파일마다 권리가 달라 직접 다운로드·반입은 제공하지 않습니다." },
  { name: "WordPress REST API", integration: "기술 검토", auth: "OAuth", rights: "메타데이터 전용", importMode: "검색·원문 링크", termsReviewedAt: "2026-09-25", category: "연재·공지 배포", status: "사용자 사이트별 인증·게시 미리보기 설계", commercial: "조건부 상업 이용", url: "https://developer.wordpress.org/rest-api/", note: "사용자가 연결한 작품 사이트에 에피소드 소개·썸네일·공지 초안을 게시하는 후보입니다. 게시 전 미리보기와 명시적 승인, 사이트별 토큰 격리를 요구합니다." },
  { name: "Mastodon API", integration: "기술 검토", auth: "OAuth", rights: "메타데이터 전용", importMode: "검색·원문 링크", termsReviewedAt: "2026-09-25", category: "소셜 배포", status: "인스턴스별 OAuth·게시 승인 설계", commercial: "조건부 상업 이용", url: "https://docs.joinmastodon.org/api/", note: "연재 공개 알림을 인스턴스별 형식으로 변환하는 후보입니다. 사용자 승인 없이 게시하지 않고 토큰을 서버 비밀로 격리합니다." },
  { name: "Bluesky API", integration: "기술 검토", auth: "OAuth", rights: "메타데이터 전용", importMode: "검색·원문 링크", termsReviewedAt: "2026-09-25", category: "소셜 배포", status: "OAuth·게시 미리보기 설계", commercial: "조건부 상업 이용", url: "https://docs.bsky.app/", note: "에피소드 공개 카드와 링크 게시 후보입니다. 사용자 승인·게시 전 미리보기·토큰 회전 정책을 먼저 구현합니다." },
  { name: "Discord Webhook", integration: "기술 검토", auth: "OAuth", rights: "메타데이터 전용", importMode: "검색·원문 링크", termsReviewedAt: "2026-09-25", category: "커뮤니티 공지 배포", status: "채널별 webhook 비밀·게시 승인 설계", commercial: "조건부 상업 이용", url: "https://discord.com/developers/docs/resources/webhook", note: "연재·협업 공지를 사용자가 연결한 채널에 보내는 후보입니다. webhook URL은 브라우저·로그·문서에 노출하지 않습니다." },
];
