import {
  formatI18nTemplate,
  translateCurrentStaticSourceText,
} from "@/shared/lib/i18n-bilingual-copy";
import { PromoCameraEditor } from "./PromoCameraEditor";
import { PROMO_EFFECTS, PROMO_MOTIONS, PROMO_MOTION_LABELS, PROMO_TRANSITIONS, PROMO_MAX_PANELS } from "./promo-model";

import type { PromoPanel, PromoScene } from "./promo-model";

export function PromoPanelEditor({ scene, index, count, disabled, onChange, onMove, onRemove, onDuplicate, onSeek, onSeekFrame, onForeground }: {
  scene: PromoScene; index: number; count: number; disabled: boolean;
  onSeekFrame?: (frame: number) => void;
  onDuplicate?: () => void; onSeek?: () => void; onForeground?: (file: File) => void;
  onChange: (patch: Partial<PromoPanel>) => void; onMove: (direction: -1 | 1) => void; onRemove: () => void;
}) {
  const { panel } = scene;
  return (
    <fieldset className="promo-shot" disabled={disabled}>
      <legend>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 ")}{index + 1} · {(scene.duration / 30).toFixed(1)}{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "초")}</legend>
      <img src={panel.src} alt={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 {v0} 원본"), { v0: String(index + 1) })} className="promo-shot-image" />
      <div className="promo-shot-fields">
        <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "description-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 설명 ")}<span className="promo-muted">{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "AI가 참고할 내용")}</span></label>
        <textarea id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "description-{v0}"), { v0: String(panel.id) })} maxLength={500} rows={2} placeholder={translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "누가, 어디서, 어떤 감정으로 무엇을 하나요?")} value={panel.description} onChange={(event) => onChange({ description: event.target.value })} />
        <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "caption-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "영상 자막")}</label>
        <input id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "caption-{v0}"), { v0: String(panel.id) })} maxLength={120} value={panel.caption} onChange={(event) => onChange({ caption: event.target.value })} />
        <div className="promo-inline-grid">
          <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "motion-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "카메라 모션")}<select id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "motion-{v0}"), { v0: String(panel.id) })} value={panel.motion} onChange={(event) => onChange({ motion: event.target.value as PromoPanel["motion"] })}>{PROMO_MOTIONS.map((motion) => <option key={motion} value={motion}>{PROMO_MOTION_LABELS[motion]}</option>)}</select></label>
          <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "fit-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "화면 맞춤")}<select id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "fit-{v0}"), { v0: String(panel.id) })} value={panel.fit} onChange={(event) => onChange({ fit: event.target.value as PromoPanel["fit"] })}><option value="contain">{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "원본 전체 보기")}</option><option value="cover">{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "화면 채우기 (크롭)")}</option></select></label>
          <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "weight-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "상대 길이")}<select id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "weight-{v0}"), { v0: String(panel.id) })} value={panel.weight} onChange={(event) => onChange({ weight: Number(event.target.value) })}>{[0.5, 1, 1.5, 2, 3].map((weight) => <option key={weight} value={weight}>{weight}{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "배")}</option>)}{![0.5, 1, 1.5, 2, 3].includes(panel.weight) ? <option value={panel.weight}>{panel.weight}{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "배 (AI)")}</option> : null}</select></label>
        </div>
        <details className="promo-shot-direction">
          <summary>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "키프레임 · 전환 · 효과 · 초점 · 2.5D 전경")}</summary>
          <PromoCameraEditor scene={scene} onChange={onChange} onSeek={onSeekFrame} />
          <div className="promo-inline-grid">
            <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "transition-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "장면 전환")}<select id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "transition-{v0}"), { v0: String(panel.id) })} value={panel.transition ?? translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "fade")} onChange={(event) => onChange({ transition: event.target.value as PromoPanel["transition"] })}>{Object.entries(PROMO_TRANSITIONS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
            <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "effect-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "분위기 효과")}<select id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "effect-{v0}"), { v0: String(panel.id) })} value={panel.effect ?? translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "none")} onChange={(event) => onChange({ effect: event.target.value as PromoPanel["effect"] })}>{Object.entries(PROMO_EFFECTS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
          </div>
          <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "intensity-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "움직임 강도 ")}{((panel.intensity ?? 1) * 100).toFixed(0)}%<input id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "intensity-{v0}"), { v0: String(panel.id) })} type="range" min={0} max={2} step={0.05} value={panel.intensity ?? 1} onChange={(event) => onChange({ intensity: Number(event.target.value) })} /></label>
          {panel.fit === "cover" ? <>
            <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "focus-x-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "가로 초점")}<input id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "focus-x-{v0}"), { v0: String(panel.id) })} type="range" min={0} max={1} step={0.01} value={panel.focusX ?? 0.5} onChange={(event) => onChange({ focusX: Number(event.target.value) })} /></label>
            <label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "focus-y-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "세로 초점")}<input id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "focus-y-{v0}"), { v0: String(panel.id) })} type="range" min={0} max={1} step={0.01} value={panel.focusY ?? 0.5} onChange={(event) => onChange({ focusY: Number(event.target.value) })} /></label>
          </> : null}
          {onForeground ? <><label htmlFor={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "foreground-{v0}"), { v0: String(panel.id) })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "분리한 캐릭터 전경 · 투명 PNG/WebP")}<input id={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "en", "foreground-{v0}"), { v0: String(panel.id) })} type="file" accept="image/png,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) onForeground(file); event.target.value = ""; }} /></label><p className="promo-muted">{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "배경과 별도로 준비한 투명 캐릭터를 올리면 서로 다른 속도로 움직입니다. 자동 배경 제거·깊이 추정은 수행하지 않습니다.")}</p></> : null}
          {panel.foregroundSrc ? <button type="button" onClick={() => onChange({ foregroundSrc: undefined })}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "전경 제거")}</button> : null}
        </details>
        <div className="promo-shot-actions">
          {onSeek ? <button type="button" aria-label={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 {v0} 미리보기"), { v0: String(index + 1) })} onClick={onSeek}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "미리보기")}</button> : null}
          {onDuplicate ? <button type="button" aria-label={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 {v0} 복제"), { v0: String(index + 1) })} disabled={count >= PROMO_MAX_PANELS} onClick={onDuplicate}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "복제")}</button> : null}
          <button type="button" aria-label={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 {v0} 앞으로 이동"), { v0: String(index + 1) })} disabled={index === 0} onClick={() => onMove(-1)}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "앞으로")}</button>
          <button type="button" aria-label={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 {v0} 뒤로 이동"), { v0: String(index + 1) })} disabled={index === count - 1} onClick={() => onMove(1)}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "뒤로")}</button>
          <button type="button" aria-label={formatI18nTemplate(translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "컷 {v0} 삭제"), { v0: String(index + 1) })} onClick={onRemove}>{translateCurrentStaticSourceText("domains.creator.promo.PromoPanelEditor", "ko", "삭제")}</button>
        </div>
      </div>
    </fieldset>
  );
}
