import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  canonicalizeCreatorMarketplaceJson,
  creatorMarketplaceJsonByteSize,
} from "../apps/web/src/shared/lib/creator-marketplace-resource-contract";

import { buildMarketCc0ReleaseManifests } from "./seed/market-cc0-release-manifests";

const root = resolve(import.meta.dirname, "..");
const output = resolve(
  root,
  "apps/web/src/shared/lib/creator-marketplace-cc0-starter.generated.ts",
);

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function stableUuid(seed: string): string {
  const hex = sha256(seed).slice(0, 32).split("");
  hex[12] = "5";
  hex[16] = ["8", "9", "a", "b"][parseInt(hex[16]!, 16) % 4]!;
  const value = hex.join("");
  return `${value.slice(0, 8)}-${value.slice(8, 12)}-${value.slice(12, 16)}-${value.slice(16, 20)}-${value.slice(20)}`;
}
const publisher = Object.freeze({
  id: "00000000-0000-4000-8000-0000000000c0",
  name: "ToonSpectrum 검수 CC0",
  avatar: "#3b82f6",
});
const timestamp = "2026-09-18T00:00:00.000Z";

const manifests = buildMarketCc0ReleaseManifests();
const buckets = [
  manifests.filter((manifest) => manifest.tags.includes("배경")),
  manifests.filter((manifest) => manifest.tags.includes("2D 소품")),
  manifests.filter((manifest) => manifest.tags.includes("3D PBR")),
  manifests.filter((manifest) => manifest.tags.includes("재질")),
  manifests.filter((manifest) => manifest.tags.includes("연출 효과")),
];
const orderedManifests = Array.from({ length: Math.max(...buckets.map((bucket) => bucket.length)) }, (_, index) =>
  buckets.flatMap((bucket) => bucket[index] ? [bucket[index]!] : []),
).flat();

const records = orderedManifests.map((manifest) => {
  const { rightsConfirmed: _rightsConfirmed, ...publicManifest } = manifest;
  return {
    ...publicManifest,
    id: stableUuid(manifest.packageId),
    manifestHash: sha256(canonicalizeCreatorMarketplaceJson(manifest)),
    manifestByteSize: creatorMarketplaceJsonByteSize(manifest),
    publisher,
    createdAt: timestamp,
    updatedAt: timestamp,
    isOwner: false,
    access: "free",
  };
});

const source = `// Generated by scripts/generate-market-cc0-starter-records.mts.\n`
  + `import type { CreatorMarketplaceResourceRecord } from "./creator-marketplace-resource-contract";\n\n`
  + `export const CREATOR_MARKETPLACE_CC0_STARTER_RECORDS: readonly CreatorMarketplaceResourceRecord[] = ${JSON.stringify(records, null, 2)};\n`;

if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8") !== source) {
    throw new Error("Marketplace CC0 starter records are stale");
  }
} else {
  await writeFile(output, source, "utf8");
}
