import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { parseStudioCc0Catalog } from "../apps/web/src/domains/creator/studio-cc0-asset-delivery";
import { isStudioCc0MarketplaceReady } from "../apps/web/src/domains/creator/studio-cc0-curation";

const MARKET_KIND_ORDER = Object.freeze([
  "background",
  "prop-image",
  "model",
  "surface-texture",
  "effect-mask",
] as const);
const marketKindOrder = new Map(MARKET_KIND_ORDER.map((kind, index) => [kind, index]));
const root = resolve(import.meta.dirname, "..");
const catalog = parseStudioCc0Catalog(JSON.parse(await readFile(resolve(root, "apps/web/public/assets/studio/cc0-20260906/manifest.json"), "utf8")));
const selected = catalog
  .filter(isStudioCc0MarketplaceReady)
  .toSorted((left, right) =>
    (marketKindOrder.get(left.kind) ?? Number.MAX_SAFE_INTEGER)
      - (marketKindOrder.get(right.kind) ?? Number.MAX_SAFE_INTEGER)
    || left.category.localeCompare(right.category, "en")
    || left.name.localeCompare(right.name, "ko")
    || left.id.localeCompare(right.id, "en"),
  );
if (selected.length === 0) throw new Error("No marketplace-ready CC0 assets");
const output = resolve(root, "apps/web/src/domains/creator/studio-marketplace-cc0-catalog.generated.ts");
const source = '// Generated by scripts/generate-market-cc0-catalog.mts.\nimport type { StudioCc0Asset } from "./studio-cc0-asset-delivery";\n\n'
  + `export const STUDIO_MARKETPLACE_CC0_ASSETS: readonly StudioCc0Asset[] = ${JSON.stringify(selected, null, 2)};\n`;
if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8") !== source) throw new Error("Market CC0 registry is stale");
} else { await writeFile(output, source); }
