import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { parseStudioCc0Catalog } from "../apps/web/src/domains/creator/studio-cc0-asset-delivery";
import { getStudioCc0ReviewStatus, isStudioCc0EligibleForNewSelection } from "../apps/web/src/domains/creator/studio-cc0-curation";

const ids = [
  "polyhaven-background-wide-street-01", "polyhaven-background-rooftop-night",
  "polyhaven-background-rooitou-park", "polyhaven-background-cayley-interior",
  "polyhaven-painted-wooden-chair-01-cutout", "polyhaven-ceramic-vase-04-cutout",
  "polyhaven-wooden-display-shelves-01-cutout", "polyhaven-brass-diya-lantern-cutout",
  "polyhaven-painted-wooden-chair-01", "polyhaven-dining-chair-02",
  "polyhaven-wooden-display-shelves-01", "polyhaven-ceramic-vase-04",
  "polyhaven-round-wooden-table-01", "polyhaven-sofa-02",
];
const root = resolve(import.meta.dirname, "..");
const catalog = parseStudioCc0Catalog(JSON.parse(await readFile(resolve(root, "apps/web/public/assets/studio/cc0-20260906/manifest.json"), "utf8")));
const selected = ids.map(id => {
  const asset = catalog.find(item => item.id === id);
  if (!asset || !isStudioCc0EligibleForNewSelection(asset) || getStudioCc0ReviewStatus(asset) !== "contact-sheet-reviewed") throw new Error(`Unreviewed asset: ${id}`);
  return asset;
});
const output = resolve(root, "apps/web/src/domains/creator/studio-marketplace-cc0-catalog.generated.ts");
const source = '// Generated by scripts/generate-market-cc0-catalog.mts.\nimport type { StudioCc0Asset } from "./studio-cc0-asset-delivery";\n\n'
  + `export const STUDIO_MARKETPLACE_CC0_ASSETS: readonly StudioCc0Asset[] = ${JSON.stringify(selected, null, 2)};\n`;
if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8") !== source) throw new Error("Market CC0 registry is stale");
} else { await writeFile(output, source); }
