#!/usr/bin/env python3
"""Apply the physical-GPU provenance patch to the all-brush benchmark sources."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def replace_once(source: str, before: str, after: str, label: str) -> str:
    count = source.count(before)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return source.replace(before, after, 1)


GPU_ADAPTER_HELPER = r'''async function inspectGpuAdapter(page: Page): Promise<GpuAdapterEvidence> {
  const unavailable: GpuAdapterEvidence = Object.freeze({
    available: false,
    adapterClass: "unavailable",
    isFallbackAdapter: null,
    adapterFingerprint: null,
    vendor: "",
    architecture: "",
    device: "",
    description: "",
  });
  if (!WEBGPU) return unavailable;
  return page.evaluate(async () => {
    type AdapterInfoLike = Readonly<{
      vendor?: unknown;
      architecture?: unknown;
      device?: unknown;
      description?: unknown;
    }>;
    type AdapterLike = Readonly<{
      info?: AdapterInfoLike;
      isFallbackAdapter?: unknown;
    }>;
    type NavigatorWithGpu = Navigator & Readonly<{
      gpu?: Readonly<{
        requestAdapter(options?: Readonly<{ powerPreference?: "high-performance" }>):
          Promise<AdapterLike | null>;
      }>;
    }>;
    const gpu = (navigator as NavigatorWithGpu).gpu;
    if (!gpu) return null;
    const adapter = await gpu.requestAdapter({ powerPreference: "high-performance" });
    if (!adapter) return null;
    const info = adapter.info ?? {};
    const text = (value: unknown): string =>
      typeof value === "string" ? value.trim() : "";
    const vendor = text(info.vendor);
    const architecture = text(info.architecture);
    const device = text(info.device);
    const description = text(info.description);
    const isFallbackAdapter = typeof adapter.isFallbackAdapter === "boolean"
      ? adapter.isFallbackAdapter
      : null;
    const adapterFingerprint = [vendor, architecture, device, description]
      .filter((value) => value.length > 0)
      .join(":") || null;
    const identity = adapterFingerprint?.toLowerCase() ?? "";
    const software = /swiftshader|llvmpipe|lavapipe|software|warp|basic render/u
      .test(identity);
    const adapterClass = isFallbackAdapter === true || software
      ? "software" as const
      : adapterFingerprint
        ? "hardware" as const
        : "unknown" as const;
    return {
      available: true,
      adapterClass,
      isFallbackAdapter,
      adapterFingerprint,
      vendor,
      architecture,
      device,
      description,
    };
  }).then((result) => result ?? unavailable).catch(() => unavailable);
}
'''


GENERATED_EVIDENCE_FUNCTION = r'''function generatedEvidenceSource(input: Readonly<{
  generatedAt: string;
  expiresAt: string;
  sourceCommit: string | null;
  digest: string;
  measurementRunCount: number;
  measuredBrushCount: number;
  hardwareAdapterFingerprints: readonly string[];
  approved: readonly string[];
  rejected: readonly string[];
}>): string {
  const literal = (values: readonly string[]) => JSON.stringify(values, null, 2)
    .split("\n")
    .map((line, index) => index === 0 ? line : `  ${line}`)
    .join("\n");
  return `/** Generated by scripts/aggregate-studio-all-brush-long-stroke.mts. */\n`
    + `export const STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_SCHEMA_VERSION = 2 as const;\n`
    + `export const STUDIO_BRUSH_GPU_QUALITY_EVIDENCE = Object.freeze({\n`
    + `  schemaVersion: STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_SCHEMA_VERSION,\n`
    + `  rendererContractVersion: ${STUDIO_BRUSH_GPU_QUALITY_RENDER_CONTRACT_VERSION},\n`
    + `  generatedAt: ${JSON.stringify(input.generatedAt)},\n`
    + `  expiresAt: ${JSON.stringify(input.expiresAt)},\n`
    + `  sourceCommit: ${JSON.stringify(input.sourceCommit)},\n`
    + `  benchmarkDigest: ${JSON.stringify(input.digest)},\n`
    + `  measurementRunCount: ${input.measurementRunCount},\n`
    + `  measuredBrushCount: ${input.measuredBrushCount},\n`
    + `  hardwareClass: ${input.hardwareAdapterFingerprints.length > 0 ? '"hardware"' : 'null'} as "hardware" | null,\n`
    + `  hardwareAdapterFingerprints: Object.freeze(${literal(input.hardwareAdapterFingerprints)} as string[]),\n`
    + `  approvedBrushIds: Object.freeze(${literal(input.approved)} as string[]),\n`
    + `  rejectedBrushIds: Object.freeze(${literal(input.rejected)} as string[]),\n`
    + `});\n`;
}'''


def patch_verifier() -> None:
    path = ROOT / "scripts/verify-studio-long-stroke.mts"
    source = path.read_text(encoding="utf-8")
    source = replace_once(
        source,
        '''interface SurfaceEvidence {
  readonly gpuEverActive: boolean;
  readonly gpuEverAuthorized: boolean;
  readonly gpuSurfaceKinds: readonly string[];
  readonly refusedStrokeNotices: number;
}
type GateGlobals = typeof globalThis & {''',
        '''interface SurfaceEvidence {
  readonly gpuEverActive: boolean;
  readonly gpuEverAuthorized: boolean;
  readonly gpuSurfaceKinds: readonly string[];
  readonly refusedStrokeNotices: number;
}
interface GpuAdapterEvidence {
  readonly available: boolean;
  readonly adapterClass: "hardware" | "software" | "unknown" | "unavailable";
  readonly isFallbackAdapter: boolean | null;
  readonly adapterFingerprint: string | null;
  readonly vendor: string;
  readonly architecture: string;
  readonly device: string;
  readonly description: string;
}
type GateGlobals = typeof globalThis & {''',
        "verifier adapter interface",
    )
    source = replace_once(
        source,
        '''function log(message: string): void {
  console.log(`[verify-studio-long-stroke] ${message}`);
}''',
        GPU_ADAPTER_HELPER + '''
function log(message: string): void {
  console.log(`[verify-studio-long-stroke] ${message}`);
}''',
        "verifier adapter helper",
    )
    source = replace_once(
        source,
        '''    await page.goto(studioUrl, { waitUntil: "domcontentloaded", timeout: 60_000 });
    await page.locator(".konvajs-content").first().waitFor({ state: "visible", timeout: 60_000 })''',
        '''    await page.goto(studioUrl, { waitUntil: "domcontentloaded", timeout: 60_000 });
    const gpuAdapter = await inspectGpuAdapter(page);
    report.gpuAdapter = gpuAdapter;
    log(`gpu adapter: ${gpuAdapter.adapterClass} · ${gpuAdapter.adapterFingerprint ?? "unidentified"}`);
    await page.locator(".konvajs-content").first().waitFor({ state: "visible", timeout: 60_000 })''',
        "verifier adapter capture",
    )
    path.write_text(source, encoding="utf-8")


def patch_aggregator() -> None:
    path = ROOT / "scripts/aggregate-studio-all-brush-long-stroke.mts"
    source = path.read_text(encoding="utf-8")
    source = replace_once(
        source,
        '''import {
  electStudioBrushGpuQuality,
  type StudioBrushCrossEngineQualityEvidence,
  type StudioBrushGpuQualityPolicyKind,
  type StudioBrushLongStrokePerformanceEvidence,
  type StudioBrushLongStrokeQualityEvidence,
} from "../src/domains/creator/brush/studio-brush-gpu-quality-election";''',
        '''import {
  STUDIO_BRUSH_GPU_QUALITY_RENDER_CONTRACT_VERSION,
  electStudioBrushGpuQuality,
  type StudioBrushCrossEngineQualityEvidence,
  type StudioBrushGpuExecutionEvidence,
  type StudioBrushGpuQualityPolicyKind,
  type StudioBrushLongStrokePerformanceEvidence,
  type StudioBrushLongStrokeQualityEvidence,
} from "../src/domains/creator/brush/studio-brush-gpu-quality-election";
import {
  STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_MAX_AGE_MS,
} from "../src/domains/creator/brush/studio-brush-gpu-quality-evidence";''',
        "aggregator imports",
    )
    source = replace_once(
        source,
        '''  readonly surfaceEvidence?: {
    readonly gpuEverActive?: boolean;
    readonly gpuEverAuthorized?: boolean;
    readonly gpuSurfaceKinds?: readonly string[];
    readonly refusedStrokeNotices?: number;
  };
}''',
        '''  readonly surfaceEvidence?: {
    readonly gpuEverActive?: boolean;
    readonly gpuEverAuthorized?: boolean;
    readonly gpuSurfaceKinds?: readonly string[];
    readonly refusedStrokeNotices?: number;
  };
  readonly gpuAdapter?: {
    readonly available?: boolean;
    readonly adapterClass?: "hardware" | "software" | "unknown" | "unavailable";
    readonly isFallbackAdapter?: boolean | null;
    readonly adapterFingerprint?: string | null;
  };
}''',
        "aggregator adapter report type",
    )
    source = replace_once(
        source,
        '''async function qualityPolicy(item: StudioBrushCatalogItem): Promise<StudioBrushGpuQualityPolicyKind> {''',
        '''function gpuExecutionEvidence(
  report: LongStrokeReport | null,
): StudioBrushGpuExecutionEvidence {
  const adapter = report?.gpuAdapter;
  const adapterClass = adapter?.adapterClass;
  return {
    adapterClass: adapterClass === "hardware"
      || adapterClass === "software"
      || adapterClass === "unknown"
      || adapterClass === "unavailable"
        ? adapterClass
        : "unavailable",
    isFallbackAdapter: typeof adapter?.isFallbackAdapter === "boolean"
      ? adapter.isFallbackAdapter
      : null,
    adapterFingerprint: typeof adapter?.adapterFingerprint === "string"
      && adapter.adapterFingerprint.length > 0
        ? adapter.adapterFingerprint
        : null,
  };
}

async function qualityPolicy(item: StudioBrushCatalogItem): Promise<StudioBrushGpuQualityPolicyKind> {''',
        "aggregator adapter projection",
    )
    source = replace_once(
        source,
        '''      gpu: {
        quality: qualityEvidence(gpu.report, gpuAnalysis),
        performance: performanceEvidence(gpu.report),
      },
      crossEngine: cross,''',
        '''      gpu: {
        quality: qualityEvidence(gpu.report, gpuAnalysis),
        performance: performanceEvidence(gpu.report),
      },
      gpuExecution: gpuExecutionEvidence(gpu.report),
      crossEngine: cross,''',
        "aggregator election input",
    )
    source = replace_once(
        source,
        '''      gpu: {
        verifierOk: gpu.report?.ok ?? false,
        quality: qualityEvidence(gpu.report, gpuAnalysis),
        performance: performanceEvidence(gpu.report),
        report: relative(INPUT_ROOT, join(gpu.caseRoot, "report.json")),
      },''',
        '''      gpu: {
        verifierOk: gpu.report?.ok ?? false,
        quality: qualityEvidence(gpu.report, gpuAnalysis),
        performance: performanceEvidence(gpu.report),
        execution: gpuExecutionEvidence(gpu.report),
        report: relative(INPUT_ROOT, join(gpu.caseRoot, "report.json")),
      },''',
        "aggregator report adapter evidence",
    )
    function_start = source.index("function generatedEvidenceSource(")
    function_end = source.index("\n\nasync function main", function_start)
    source = source[:function_start] + GENERATED_EVIDENCE_FUNCTION + source[function_end:]
    source = replace_once(
        source,
        '''  const generatedAt = new Date().toISOString();
  const sourceCommit = process.env.GITHUB_SHA ?? null;
  const approved = cases''',
        '''  const generatedAt = new Date().toISOString();
  const expiresAt = new Date(
    Date.parse(generatedAt) + STUDIO_BRUSH_GPU_QUALITY_EVIDENCE_MAX_AGE_MS,
  ).toISOString();
  const sourceCommit = process.env.GITHUB_SHA ?? null;
  const hardwareAdapterFingerprints = [...new Set(cases.flatMap((entry) =>
    entry.gpu.execution.adapterClass === "hardware"
      && entry.gpu.execution.isFallbackAdapter !== true
      && entry.gpu.execution.adapterFingerprint
        ? [entry.gpu.execution.adapterFingerprint]
        : []
  ))].sort();
  // A single hosted shard sweep remains diagnostic-only. Product admission requires three
  // independent measurements on a non-fallback physical adapter.
  const measurementRunCount = 1;
  const approved = cases''',
        "aggregator evidence metadata",
    )
    source = replace_once(
        source,
        '''    kind: "toonspectrum-all-brush-screen-fill-gpu-election-v1",
    generatedAt,
    sourceCommit,
    benchmarkDigest,''',
        '''    kind: "toonspectrum-all-brush-screen-fill-gpu-election-v2",
    generatedAt,
    expiresAt,
    sourceCommit,
    rendererContractVersion: STUDIO_BRUSH_GPU_QUALITY_RENDER_CONTRACT_VERSION,
    measurementRunCount,
    hardwareClass: hardwareAdapterFingerprints.length > 0 ? "hardware" : null,
    hardwareAdapterFingerprints,
    benchmarkDigest,''',
        "aggregator report metadata",
    )
    source = replace_once(
        source,
        '    `- GPU 품질 승인: ${approved.length}`,',
        '''    `- GPU 품질 승인 후보: ${approved.length}`,
    `- 물리 GPU 증거: ${hardwareAdapterFingerprints.length > 0 ? hardwareAdapterFingerprints.join(", ") : "없음(진단 전용)"}`,
    `- 반복 측정: ${measurementRunCount}회 (자동 승격 최소 3회)`,
    `- 증거 만료: ${expiresAt}`,''',
        "aggregator report prose",
    )
    source = replace_once(
        source,
        '''    "질감·형태·라이브/커밋 연속성이 먼저이며, 성능이 빨라도 품질 축 하나가 열화되면 기존 경로를 유지한다. 품질이 동등하고 p95가 5% 이내의 비열화 범위면 GPU를 우선한다.",''',
        '''    "질감·형태·라이브/커밋 연속성이 먼저이며, 성능이 빨라도 품질 축 하나가 열화되면 기존 경로를 유지한다. 비폴백 물리 GPU가 확인되고 품질이 거의 동일하며 p95가 2% 이내일 때만 승격 후보가 된다. 자동 승격에는 같은 렌더 계약에서 세 번의 독립 측정이 필요하다.",''',
        "aggregator quality-first prose",
    )
    source = replace_once(
        source,
        '''  writeFileSync(GENERATED_EVIDENCE_PATH, generatedEvidenceSource({
    generatedAt,
    sourceCommit,
    digest: benchmarkDigest,
    measuredBrushCount: cases.length,
    approved,
    rejected,
  }));''',
        '''  writeFileSync(GENERATED_EVIDENCE_PATH, generatedEvidenceSource({
    generatedAt,
    expiresAt,
    sourceCommit,
    digest: benchmarkDigest,
    measurementRunCount,
    measuredBrushCount: cases.length,
    hardwareAdapterFingerprints,
    approved,
    rejected,
  }));''',
        "aggregator generated evidence call",
    )
    path.write_text(source, encoding="utf-8")


def patch_workflow() -> None:
    path = ROOT / ".github/workflows/studio-all-brush-long-stroke-quality.yml"
    source = path.read_text(encoding="utf-8")
    source = replace_once(
        source,
        '''            src/domains/creator/brush/studio-brush-gpu-quality-election.test.ts \\
            src/domains/creator/live/studio-live-ink-lane-admission.test.ts''',
        '''            src/domains/creator/brush/studio-brush-gpu-quality-election.test.ts \\
            src/domains/creator/brush/studio-brush-gpu-quality-evidence.test.ts \\
            src/domains/creator/live/studio-live-ink-lane-admission.test.ts''',
        "benchmark evidence tests",
    )
    source = replace_once(
        source,
        '''            src/domains/creator/brush/studio-brush-gpu-quality-evidence.ts \\
            src/domains/creator/brush/studio-brush-gpu-quality-evidence.generated.ts \\
''',
        '''            src/domains/creator/brush/studio-brush-gpu-quality-evidence.ts \\
            src/domains/creator/brush/studio-brush-gpu-quality-evidence.test.ts \\
            src/domains/creator/brush/studio-brush-gpu-quality-evidence.generated.ts \\
''',
        "benchmark evidence lint",
    )
    path.write_text(source, encoding="utf-8")


def main() -> None:
    patch_verifier()
    patch_aggregator()
    patch_workflow()


if __name__ == "__main__":
    main()
