// Isolated fixture adapters; production renderers and accounts are never mutated here.
import { defaultStudioAppSettings } from "../../src/domains/creator/studio-app-settings";
import { DEFAULT_STUDIO_LIVING_INK_MATERIAL_CONTROLS } from "../../src/domains/creator/studio-living-ink-gpu-protocol";
import { StudioBrushLibraryPanel, StudioBrushStudio, StudioShapePickerGrid, StudioUnifiedBrushPicker, loadStudioBrushStudio } from "../../src/domains/creator/studio-page-lazy-ui";
import { DEFAULT_STUDIO_PRO_DRAW_PREFS } from "../../src/domains/creator/studio-pro-draw-prefs";
import { StudioMobileSheetHandle } from "../../src/domains/creator/StudioMobileSheetHandle";

import type { NormalizedStudioBrushDynamicsSettings } from "../../src/domains/creator/brush/studio-brush-dynamics";
import type { StudioBrushSnapshot } from "../../src/domains/creator/brush/studio-brush-library";
import type { StudioLeftToolRailClientInput } from "../../src/domains/creator/editor-client/studio-left-tool-rail-client";
import type { StudioWorkspaceState } from "../../src/domains/creator/studio-workspaces";
import type { StudioMobileEditingDockHandlers, StudioMobileEditingDockProps } from "../../src/domains/creator/StudioMobileEditingDock";

export function createMobileHandlers(): StudioMobileEditingDockHandlers {
  return {
    activateCanvasTool: () => undefined,
    applyBuiltInBrushPreset: () => undefined,
    applyBrushDefaultRestoreTransaction: () => undefined,
    applyDynamicsPreset: () => undefined,
    applySavedBrush: () => undefined,
    dismissBrushManager: () => undefined,
    dismissMobileHint: () => undefined,
    duplicateSelected: () => undefined,
    editSelectionText: () => undefined,
    fitCanvasToWidth: () => undefined,
    openBrushManager: () => undefined,
    openInspectorRoute: () => undefined,
    openStudioFilter: () => undefined,
    queueBrushDelete: () => undefined,
    redo: () => undefined,
    removeSelected: () => undefined,
    reorder: () => undefined,
    restoreBrushDefaults: () => undefined,
    toggleAdvancedFill: () => undefined,
    toggleSelectionLock: () => undefined,
    toggleStudioCommentPinPlacement: () => undefined,
    undo: () => undefined,
  };
}


export function createMobileProps(
  overrides: Partial<StudioMobileEditingDockProps> = {},
): StudioMobileEditingDockProps {
  return {
    touchPreferences: { twoFinger: "pan-zoom", threeFinger: "undo" },
    activeCatalogBrushId: "gpen",
    activeCatalogBrushName: "G펜",
    activeSavedBrushId: null,
    activeSurfaceReviewLocked: false,
    advancedFillActive: false,
    advancedFillUnsupportedReason: null,
    brush: "gpen",
    brushCatalogHandlers: {
      close: () => undefined,
      selectBrushId: () => undefined,
      toggle: () => undefined,
      toggleFavorite: () => undefined,
    },
    brushCatalogItems: [],
    brushCatalogOpen: false,
    brushDefaultRestore: {
      sourceName: "G펜",
      modifiedCount: 0,
      loading: false,
      available: true,
      undoAvailable: false,
    },
    brushDynamics: {} as NormalizedStudioBrushDynamicsSettings,
    brushManagerSheetRef: { current: null },
    brushOpacity: 1,
    collaborationDocumentLocked: false,
    commentPinArmed: false,
    color: "#111111",
    colorBlindPreview: "none",
    colorVisionSheetRef: { current: null },
    currentBrushSnapshot: {} as StudioBrushSnapshot,
    drawMode: "pen",
    drawShape: "rect",
    drawSheetRef: { current: null },
    eraseToIntersection: false,
    filterMutationLocked: false,
    filterPreparationBusy: false,
    filterTargetLabel: "현재 페이지 합성본",
    filterUnavailableReason: null,
    hi: 0,
    history: [[], []],
    isMobile: false,
    livingInk: {
      supported: false,
      physicalModeEnabled: false,
      onPhysicalModeEnabledChange: () => undefined,
      state: "ready",
      mode: "ink",
      onModeChange: () => undefined,
      scope: "all",
      onScopeChange: () => undefined,
      selectionAvailable: false,
      busy: false,
      fixAvailable: false,
      onFix: () => undefined,
      onClear: () => undefined,
      material: DEFAULT_STUDIO_LIVING_INK_MATERIAL_CONTROLS,
      materialLocked: false,
      onMaterialChange: () => undefined,
    },
    marqueeIds: [],
    mobileBrushDockButtonRef: { current: null },
    mobileKeyboardInset: 0,
    mobileQuickActionsButton: <button type="button">빠른 작업</button>,
    mobileSheet: null,
    postCorrection: 0,
    preserveCorners: true,
    pressureCurve: 1,
    proDrawPrefs: DEFAULT_STUDIO_PRO_DRAW_PREFS,
    quickActionsOpen: false,
    savedBrushes: [],
    selected: null,
    selectionLocked: false,
    selectionTextEditLabel: null,
    setBrushDynamics: () => undefined,
    setBrushOpacity: () => undefined,
    setColor: () => undefined,
    setColorBlindPreview: () => undefined,
    setDrawMode: () => undefined,
    setDrawShape: () => undefined,
    setEraseToIntersection: () => undefined,
    setMarqueeIds: () => undefined,
    setMenu: () => undefined,
    setMobileSheet: () => undefined,
    setPostCorrection: () => undefined,
    setPreserveCorners: () => undefined,
    setPressureCurve: () => undefined,
    setQuickStartOpen: () => undefined,
    setSavedBrushes: () => undefined,
    setSelectedId: () => undefined,
    setShapeFill: () => undefined,
    setStabilizer: () => undefined,
    setStabilizerMode: () => undefined,
    setStampTuning: () => undefined,
    setStrokeWidth: () => undefined,
    setTiltEnabled: () => undefined,
    setTipAngle: () => undefined,
    setTipRoundness: () => undefined,
    setTool: () => undefined,
    setUseVelocityPressure: () => undefined,
    setVelocitySensitivity: () => undefined,
    setZoom: () => undefined,
    shapeFill: false,
    showMobileHint: false,
    stabilizer: 0,
    stabilizerMode: "standard",
    stableHandlers: createMobileHandlers(),
    stampTuning: null,
    strokeWidth: 4,
    tiltEnabled: false,
    tipAngle: 0,
    tipRoundness: 1,
    tool: "draw",
    ui: {
      StudioBrushLibraryPanel,
      StudioBrushStudio,
      StudioMobileSheetHandle,
      StudioShapePickerGrid,
      StudioUnifiedBrushPicker,
      loadStudioBrushStudio,
    },
    useVelocityPressure: false,
    velocitySensitivity: 1,
    workspaceState: { mobileControlSide: "right" } as StudioWorkspaceState,
    zoom: 1,
    ...overrides,
  };
}


export function createRailInput(): StudioLeftToolRailClientInput {
  return {
    activeSurfaceReviewLocked: false,
    pixelToolTargetAvailable: true,
    rasterRetouchTargetAvailable: true,
    advancedFillActive: false,
    advancedFillUnsupportedReason: null,
    appSettings: defaultStudioAppSettings(),
    appSettingsOpen: false,
    canvasOnlyMode: false,
    commentPinArmed: false,
    cropActive: false,
    drawMode: "pen",
    drawShape: "rect",
    eyedropperActive: false,
    frameAnimOpen: false,
    frameAnimTargetId: null,
    isRailToolVisible: () => true,
    liquifyActive: false,
    mobileImmersive: false,
    perspectiveRulerActive: false,
    pixelForceCircle: false,
    pixelSel: null,
    pixelTool: null,
    quickShapeActive: false,
    railMoreOpen: false,
    referencePanelOpen: false,
    mannequinPoserOpen: false,
    poserVrmOpen: false,
    characterShaperOpen: false,
    bg3dOpen: false,
    hybridDccOpen: false,
    selected: null,
    selectedImageMutationLocked: false,
    dodgeBurnActive: false,
    wetMixActive: false,
    smudgeActive: false,
    tool: "select",
    uiDensityMode: "full",
    viewTransformSuppressed: false,
    viewTool: null,
    activatePrimaryCanvasTool: () => undefined,
    toggleHandTool: () => undefined,
    returnToSelectTool: () => undefined,
    fitCanvasToWidth: () => undefined,
    openFrameAnimationForSelected: () => undefined,
    openPixelSelectionTransform: () => undefined,
    openSelectedLayerCrop: () => undefined,
    toggleBg3dEditor: () => undefined,
    addBubble: () => undefined,
    addText: () => undefined,
    announceDrawingShortcut: () => undefined,
    clearPolyLassoDraft: () => undefined,
    commitAppSettings: () => undefined,
    disarmAllPixelTools: () => undefined,
    onRequestPixelSelection: () => undefined,
    onRequestSelectImage: () => undefined,
    onPickImage: async () => undefined,
    revealDrawToolProperties: () => undefined,
    toggleAdvancedFill: () => undefined,
    toggleDodgeBurnTool: () => undefined,
    toggleWetMixTool: () => undefined,
    toggleLiquifyTool: () => undefined,
    togglePixelMarquee: () => undefined,
    toggleSmudgeTool: () => undefined,
    toggleStudioCommentPinPlacement: () => undefined,
    setAppSettingsInitialTab: () => undefined,
    setAppSettingsOpen: () => undefined,
    setDrawShape: () => undefined,
    setEyedropperActive: () => undefined,
    setMenu: () => undefined,
    setPerspectiveRulerActive: () => undefined,
    setPixelForceCircle: () => undefined,
    setPixelTool: () => undefined,
    setQuickShapeActive: () => undefined,
    setRailMoreOpen: () => undefined,
    setReferencePanelOpen: () => undefined,
    setViewTool: () => undefined,
  };
}
