import { defineAppRoutes } from "../app-route-definition";
import {
  AboutPage,
  AccessibilityPage,
  ContactPage,
  CopyrightPage,
  CrawlerPolicyPage,
  DataSourcesPage,
  DesignSystemPage,
  FeedbackPage,
  HelpCenterPage,
  PrivacyPage,
  ProductPrinciplesPage,
  SitemapPage,
  SupportPage,
  TechnologyPage,
  TermsPage,
  WebtoonWorkflowPage,
} from "./legal-route-pages";

export const legalRoutes = defineAppRoutes([
  { id: "legal-about", path: "/about", element: <AboutPage /> },
  { id: "legal-about-workflow", path: "/about/workflow", element: <WebtoonWorkflowPage /> },
  { id: "legal-about-technology", path: "/about/technology", element: <TechnologyPage /> },
  { id: "legal-about-principles", path: "/about/principles", element: <ProductPrinciplesPage /> },
  { id: "legal-help", path: "/help", element: <HelpCenterPage /> },
  { id: "legal-accessibility", path: "/accessibility", element: <AccessibilityPage /> },
  { id: "legal-data-sources", path: "/about/data", element: <DataSourcesPage /> },
  { id: "legal-crawler-policy", path: "/about/crawler", element: <CrawlerPolicyPage /> },
  { id: "legal-design", path: "/design", element: <DesignSystemPage /> },
  { id: "legal-sitemap", path: "/sitemap", element: <SitemapPage /> },
  { id: "legal-terms", path: "/terms", element: <TermsPage /> },
  { id: "legal-privacy", path: "/privacy", element: <PrivacyPage /> },
  { id: "legal-copyright", path: "/copyright", element: <CopyrightPage /> },
  { id: "legal-contact", path: "/contact", element: <ContactPage /> },
  { id: "legal-support", path: "/support", element: <SupportPage /> },
  { id: "legal-feedback", path: "/feedback", element: <FeedbackPage /> },
]);
