import { defineAppRoutes } from "../app-route-definition";
import {
  AboutPage,
  AccessibilityPage,
  BusinessPage,
  ContactPage,
  CopyrightPage,
  CreatorSupportPage,
  CrawlerPolicyPage,
  DataSourcesPage,
  DesignSystemPage,
  EngineeringDeckPage,
  EngineeringFieldNotesPage,
  EngineeringGuidesPage,
  EngineeringLicensesPage,
  EngineeringPlaybookPage,
  EngineeringReferencesPage,
  EngineeringStoryPage,
  EngineeringVideosPage,
  FeedbackPage,
  HelpCenterPage,
  PrivacyPage,
  ProductPrinciplesPage,
  SitemapPage,
  SupportPage,
  SupportUsPage,
  TechnologyPage,
  TermsPage,
  WebtoonWorkflowPage,
} from "./legal-route-pages";

export const legalRoutes = defineAppRoutes([
  { id: "legal-about", path: "/about", element: <AboutPage /> },
  {
    id: "legal-about-workflow",
    path: "/about/workflow",
    element: <WebtoonWorkflowPage />,
  },
  {
    id: "legal-about-technology",
    path: "/about/technology",
    element: <TechnologyPage />,
  },
  {
    id: "legal-about-technology-story",
    path: "/about/technology/story",
    element: <EngineeringStoryPage />,
  },
  {
    id: "legal-about-technology-playbook",
    path: "/about/technology/playbook",
    element: <EngineeringPlaybookPage />,
  },
  {
    id: "legal-about-technology-guides",
    path: "/about/technology/guides",
    element: <EngineeringGuidesPage />,
  },
  {
    id: "legal-about-technology-references",
    path: "/about/technology/references",
    element: <EngineeringReferencesPage />,
  },
  {
    id: "legal-about-technology-field-notes",
    path: "/about/technology/field-notes",
    element: <EngineeringFieldNotesPage />,
  },
  {
    id: "legal-about-technology-deck",
    path: "/about/technology/deck",
    element: <EngineeringDeckPage />,
  },
  {
    id: "legal-about-technology-videos",
    path: "/about/technology/videos",
    element: <EngineeringVideosPage />,
  },
  {
    id: "legal-about-technology-licenses",
    path: "/about/technology/licenses",
    element: <EngineeringLicensesPage />,
  },
  {
    id: "legal-about-principles",
    path: "/about/principles",
    element: <ProductPrinciplesPage />,
  },
  { id: "legal-help", path: "/help", element: <HelpCenterPage /> },
  { id: "legal-accessibility", path: "/accessibility", element: <AccessibilityPage /> },
  { id: "legal-data-sources", path: "/about/data", element: <DataSourcesPage /> },
  { id: "legal-crawler-policy", path: "/about/crawler", element: <CrawlerPolicyPage /> },
  { id: "legal-design", path: "/design", element: <DesignSystemPage /> },
  { id: "legal-sitemap", path: "/sitemap", element: <SitemapPage /> },
  { id: "legal-terms", path: "/terms", element: <TermsPage /> },
  { id: "legal-privacy", path: "/privacy", element: <PrivacyPage /> },
  { id: "legal-copyright", path: "/copyright", element: <CopyrightPage /> },
  { id: "legal-contact", path: "/contact", element: <ContactPage /> },
  { id: "legal-business", path: "/business", element: <BusinessPage /> },
  { id: "legal-support-us", path: "/support-us", element: <SupportUsPage /> },
  { id: "legal-creator-support", path: "/support-creators", element: <CreatorSupportPage /> },
  { id: "legal-support", path: "/support", element: <SupportPage /> },
  { id: "legal-feedback", path: "/feedback", element: <FeedbackPage /> },
]);